/* Perguntas autorais: pontos de partida para investigação, sem aulas expositivas. */
(function(g){'use strict';
const questions={
'fund-contagem':'Mudar a disposição dos objetos altera a quantidade da coleção?',
'fund-decimal':'O que acontece com o valor de um algarismo quando ele muda de posição?',
'fund-agrupamentos':'Quando é possível repartir os objetos sem deixar resto?',
'fund-padroes':'Como prever um termo que ainda não aparece na sequência?',
'fund-malha':'Dois retângulos com a mesma área precisam ter o mesmo perímetro?',
'fund-pesquisa':'Que conclusão os dados sustentam e que conclusão eles não permitem?',
'fund-chances':'A frequência observada precisa ser igual à chance teórica?',
'fund-percurso':'Mudar a ordem dos deslocamentos altera a chegada ou o trajeto?',
'fund-expressoes':'Como parênteses e ordem das operações alteram o resultado?',
'fund-fracoes':'Como reconhecer que duas frações diferentes representam a mesma quantidade?',
'fund-divisibilidade':'Que padrões dos divisores ajudam a prever fatores comuns?',
'fund-proporcoes':'Como distinguir variação direta, inversa e percentual?',
'fund-unidades':'O número muda na conversão; a grandeza representada também muda?',
'fund-conjuntos':'Quando a união tem menos elementos que a soma das quantidades dos conjuntos?',
'fund-logica':'Que proposições possuem a mesma tabela de valores lógicos?',
'fund-algebra':'Expressões com a mesma curva têm necessariamente o mesmo domínio?',
'fund-equacoes':'Como verificar se uma solução encontrada realmente satisfaz a equação?',
'fund-inequacoes':'Como raízes e sinal dos coeficientes determinam os intervalos de solução?',
'fund-composicao':'Trocar a ordem da composição preserva o resultado?',
'fund-exponenciais':'Como a base altera crescimento, decrescimento e domínio?',
'fund-progressoes':'Diferença constante e razão constante produzem o mesmo crescimento?',
'fund-trigonometria':'O que se repete ao acrescentar uma volta ao ângulo?',
'fund-triangulos':'Quais conjuntos de três medidas formam um triângulo?',
'fund-medidas-planas':'Como área e perímetro variam quando uma medida é duplicada?',
'fund-solidos':'Sólidos com a mesma altura e base podem ter volumes diferentes?',
'fund-complexos':'Como multiplicar por i altera a posição de um número complexo?',
'fund-combinatoria':'Por que considerar a ordem muda a quantidade de agrupamentos?',
'fund-estatistica':'Qual medida de tendência central é mais afetada por um valor extremo?',
'fund-juros':'Quando os crescimentos simples e compostos começam a se afastar?',
'fund-funcoes':'Como uma alteração na expressão aparece no gráfico?',
'fund-modelos':'Qual modelo representa melhor a variação que você deseja investigar?',
'geo-distancias':'Como justificar a distância e o ponto médio a partir do desenho?',
'geo-retas-medidas':'Como reconhecer paralelismo e perpendicularidade nas representações?',
'geo-circunferencia':'Que alterações fazem duas circunferências se tocarem ou deixarem de se cruzar?',
'geo-conicas':'Como os parâmetros alteram focos, eixos e abertura de uma cônica?',
'geo-conica-geral':'Que mudanças nos coeficientes alteram a classificação da cônica?',
'geo-reta-plano':'Em que condições uma reta cruza, pertence ou é paralela a um plano?',
'geo-planos':'O que muda na interseção quando os vetores normais se alinham?',
'geo-coordenadas':'O mesmo ponto pode ter mais de uma representação de coordenadas?',
'geo-quadricas':'O que as diferentes vistas revelam sobre uma superfície?',
'geo-poligonos':'Como a ordem dos vértices afeta orientação e área calculada?',
'geo-plano':'Que propriedades da construção permanecem quando seus pontos mudam?',
'geo-espaco':'Como distinguir retas paralelas, concorrentes e reversas no espaço?',
'alg-produtos':'Quando o produto escalar se anula e o que isso revela?',
'alg-produto-misto':'O que significa um produto misto nulo para o volume?',
'alg-matrizes':'Trocar a ordem de multiplicação de matrizes preserva o produto?',
'alg-sistemas':'Que mudanças tornam um sistema único, indeterminado ou impossível?',
'alg-bases':'Qual vetor pode ser retirado sem alterar o espaço gerado?',
'alg-gram-schmidt':'A ortogonalização muda o espaço gerado pelos vetores?',
'alg-transformacoes':'Que transformações preservam distâncias, ângulos ou alinhamento?',
'alg-autovalores':'Quais direções são preservadas por uma transformação?',
'alg-minimos-quadrados':'Como um ponto distante dos demais altera a reta ajustada?',
'alg-vetores':'Como origem, direção e módulo aparecem na representação vetorial?',
'alg-parametric':'A trajetória muda se apenas a velocidade de parametrização mudar?',
'calc1-aproximacoes':'A aproximação pela esquerda concorda com a aproximação pela direita?',
'calc1-epsilon-delta':'Um mesmo δ atende a todos os valores de ε que você escolheu?',
'calc1-derivacao':'Como as derivadas sucessivas descrevem a variação de uma função?',
'calc1-tangentes':'Como a secante se aproxima da tangente quando o incremento diminui?',
'calc1-implicitas':'Em quais pontos a derivação implícita deixa de fornecer uma inclinação finita?',
'calc1-taxas':'Como as taxas relacionadas mudam quando a configuração geométrica muda?',
'calc1-analise':'O sinal da derivada e a concavidade confirmam o que o gráfico sugere?',
'calc1-otimizacao':'O extremo do intervalo ocorre em um ponto crítico ou em uma extremidade?',
'calc1-newton':'Como a estimativa inicial afeta a convergência do método de Newton?',
'calc1-lhopital':'A hipótese de indeterminação é atendida antes de comparar derivadas?',
'calc1-taylor':'Onde o polinômio aproxima bem a função e onde o erro cresce?',
'calc1-riemann':'O refinamento das partições sempre aumenta a soma de Riemann?',
'calc1-fundamental':'Como a derivada da acumulação se relaciona ao integrando?',
'calc1-limites':'Um gráfico aparentemente contínuo é suficiente para concluir continuidade?',
'calc1-derivadas':'Que relação existe entre a inclinação local e o crescimento da função?',
'calc2-primitivas':'Como confirmar uma primitiva por derivação?',
'calc2-substituicao':'Como a troca de variável altera integrando, diferencial e limites?',
'calc2-partes':'Diferentes escolhas de fatores tornam a integral mais simples?',
'calc2-fracoes-parciais':'A decomposição preserva a função em todos os pontos do domínio original?',
'calc2-substituicao-trig':'Quais restrições do triângulo e do domínio acompanham a substituição?',
'calc2-quadratura':'Como as regras de integração respondem ao mesmo refinamento?',
'calc2-improprias':'Valores numéricos próximos são suficientes para concluir convergência?',
'calc2-areas':'Como cruzamentos e intervalo alteram a área entre as curvas?',
'calc2-cascas':'Que escolhas geométricas justificam o raio e a altura de cada casca?',
'calc2-arcos':'Como uma deformação da curva altera comprimento e área de revolução?',
'calc2-aplicacoes':'O resultado mantém significado físico quando se alteram as unidades?',
'calc2-parametricas-medidas':'A parametrização altera a curva, sua orientação ou apenas sua velocidade?',
'calc2-edo':'Como condição inicial e passo numérico alteram a solução aproximada?',
'calc2-sequencias':'Uma sequência de termos que tende a zero garante soma convergente?',
'calc2-criterios':'Quais hipóteses permitem aplicar o critério de convergência escolhido?',
'calc2-series-potencias':'As extremidades do intervalo se comportam como seus pontos interiores?',
'calc2-superficies':'Como se relacionam cortes, curvas de nível e superfície?',
'calc2-limites-caminhos':'Concordância entre alguns caminhos prova a existência do limite?',
'calc2-parciais':'Como derivadas parciais e Hessiana descrevem o comportamento local?',
'calc2-direcionais':'Qual direção produz a maior variação local da função?',
'calc2-duplas':'Como os limites descrevem a região e influenciam a integral?',
'calc2-polares':'Que erro surge quando o fator radial do jacobiano é omitido?',
'calc2-triplas':'Como os limites de integração delimitam o sólido?',
'calc2-jacobiano':'O que o jacobiano informa sobre a mudança local de área?',
'calc2-lagrange':'Os candidatos encontrados atendem à restrição e garantem um extremo global?',
'calc2-campos':'Que padrões visuais correspondem à divergência e ao rotacional?',
'calc2-integral-linha':'Trocar o sentido do caminho altera o trabalho?',
'calc2-fluxo-superficie':'Como a orientação da superfície altera o sinal do fluxo?',
'calc2-integracao':'Como raios interno e externo determinam o sólido de revolução?',
'calc2-integrais':'Como distinguir integral com sinal e área geométrica?',
'calc2-parametric':'Como identificar orientação, interseções e repetição na curva?',
'calc2-curvas3d':'Que informação sobre a curva se perde em cada projeção plana?'
};
const examples={
'fund-contagem':['Mantenha A e B; altere apenas os objetos por fileira. Depois altere apenas B.','Construa duas coleções iguais com disposições diferentes.'],
'fund-fracoes':['Compare 1/2 e 2/4. Depois examine 2/3 e 5/6, usando soma e diferença.','Encontre uma fração entre 1/2 e 3/4 e justifique.'],
'fund-malha':['Registre 6 × 4 e 8 × 3. Compare área e perímetro.','Encontre dois retângulos com o mesmo perímetro e áreas diferentes.'],
'fund-chances':['Mantenha as fichas e o identificador; compare 10, 100 e 1000 sorteios.','Crie um evento impossível e um evento certo. Explique sem usar apenas o resultado.'],
'fund-estatistica':['Registre a amostra padrão. Depois substitua o maior valor por 90.','Crie duas amostras com a mesma média e dispersões diferentes.'],
'fund-juros':['Fixe capital e taxa. Compare períodos curtos e longos.','Que informações seriam necessárias para comparar investimentos reais?'],
'calc1-tangentes':['Fixe a função e o ponto. Reduza sucessivamente o incremento da secante.','Teste um ponto em que não exista derivada e justifique a diferença.'],
'calc1-riemann':['Mantenha função e intervalo. Varie a quantidade de partições e a regra.','Busque uma função em que as aproximações ocorram por lados diferentes.'],
'calc2-areas':['Mantenha o intervalo e uma curva. Altere a outra e observe interseções.','Proponha um caso em que a integral da diferença não seja a área geométrica.']
};
function get(id){const lab=g.OrbisCatalog.labs[id];if(!lab)throw new Error('Laboratório desconhecido.');const q=questions[id];if(!q)throw new Error('Roteiro ausente: '+id);return {labId:id,title:lab.title,question:q,goal:'Construir e justificar uma resposta à pergunta usando resultados do laboratório.',experiment:examples[id]?.[0]||'Registre uma configuração inicial. Altere uma entrada por vez, mantendo as demais. Compare pelo menos dois ensaios válidos e explique as diferenças.',challenge:examples[id]?.[1]||'Crie outro caso para testar sua conclusão. Procure um contraexemplo ou explicite os limites em que ela vale.',criteria:'Previsão justificada; comparação de ensaios; uso de valores e representações; conclusão com limites; nova questão.',audience:'',duration:'',mode:'individual ou dupla'};}
g.OrbisInquiryCatalog={get,questions};
})(window);
