/* OrbisV: investigação local, roteiros docentes e evidências formativas. */
(function(g){'use strict';
const KEY='orbisvInquiryV1',MAX=8,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),copy=v=>JSON.parse(JSON.stringify(v));
const fields=['prediction','comparison','conclusion','extension','selfAssessment','feedback'];
let data={format:'orbisv-inquiry',version:1,drafts:{},plans:{},lastLabId:null},activeId=null,host=null,loadWarning='';
const $=id=>document.getElementById(id),lab=id=>g.OrbisCatalog.labs[id];
function text(v,max=4000){if(typeof v!=='string'||v.length>max)throw new Error('Texto do roteiro ou registro inválido.');return v;}
function cleanPlan(p){if(!p||!lab(p.labId))throw new Error('Laboratório do roteiro desconhecido.');const b=g.OrbisInquiryCatalog.get(p.labId),o={labId:p.labId};for(const k of ['title','question','goal','experiment','challenge','criteria','audience','duration','mode'])o[k]=text(p[k]??b[k],k==='title'?140:4000);if(!o.question.trim())throw new Error('O roteiro precisa de uma pergunta.');return o;}
function clean(raw){if(!raw||!lab(raw.labId))throw new Error('Investigação de laboratório desconhecido.');const o={labId:raw.labId,stage:Number.isInteger(raw.stage)&&raw.stage>=0&&raw.stage<4?raw.stage:0,updatedAt:typeof raw.updatedAt==='string'?raw.updatedAt:'',trials:[]};for(const k of fields)o[k]=text(raw[k]??'');if(!Array.isArray(raw.trials)||raw.trials.length>MAX)throw new Error('Use até oito ensaios por investigação.');o.trials=raw.trials.map(t=>{if(!t||!Array.isArray(t.metrics)||t.metrics.length>60||!t.values||typeof t.values!=='object'||Array.isArray(t.values))throw new Error('Ensaio inválido.');const values={};if(Object.keys(t.values).length>60)throw new Error('Ensaio muito extenso.');for(const [k,v] of Object.entries(t.values))values[text(k,120)]=text(String(v),4000);return {at:text(t.at||'',60),values,metrics:t.metrics.map(m=>({label:text(m.label,200),value:typeof m.value==='number'&&Number.isFinite(m.value)?m.value:text(String(m.value),5000)}))};});if(raw.plan)o.plan=cleanPlan(raw.plan);return o;}
try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(raw){if(raw.format!=='orbisv-inquiry'||raw.version!==1)throw new Error();for(const [id,v] of Object.entries(raw.drafts||{})){if(lab(id)){const c=clean(v);if(c.labId!==id)throw new Error();data.drafts[id]=c;}}for(const [id,v] of Object.entries(raw.plans||{})){const p=cleanPlan(v);if(p.labId!==id)throw new Error();data.plans[id]=p;}data.lastLabId=lab(raw.lastLabId)?raw.lastLabId:null;}}catch{loadWarning='Não foi possível ler investigações anteriores. Uma cópia foi preservada para recuperação.';try{const old=localStorage.getItem(KEY);if(old)localStorage.setItem('orbisvInquiryRecoveryV1',old);}catch{}}
function message(s,error=false){const n=(host&&!host.hidden?host.querySelector('#iqStatus'):null)||$('teacherStatus');if(n){n.textContent=s;n.classList.toggle('error',error);}else if(error)g.OrbisVRuntime?.AppUI.showToast(s,true);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(data));return true;}catch{message('Sem espaço para salvar. Exporte o roteiro e registre os resultados no Caderno.',true);return false;}}
function plan(id){return data.plans[id]||g.OrbisInquiryCatalog.get(id);}
function draft(id){return data.drafts[id]||(data.drafts[id]={labId:id,stage:0,prediction:'',comparison:'',conclusion:'',extension:'',selfAssessment:'',feedback:'',trials:[]});}
function touch(){const d=draft(activeId);d.updatedAt=new Date().toISOString();persist();}
function current(id){const s=g.OrbisWorkbench?.experiment?.();if(s?.labId===id)return s;if(lab(id)?.kind==='scene'&&document.body.classList.contains('platform-editor-open')){const r=g.OrbisVRuntime;return {labId:id,values:{'Objetos da cena':r.objects.items.map(o=>r.AppUI.objectLabel(o)).join('; ').slice(0,4000),'Vista':r.engine.getView().viewMode||'2d'},result:{metrics:[{label:'Objetos construídos',value:r.objects.items.length}]}};}return null;}
function available(){const b=$('iqCapture');if(b)b.disabled=!current(activeId);}
function progress(d){return [!!d.prediction.trim(),d.trials.length>=2,!!d.comparison.trim(),!!d.conclusion.trim()&&!!d.extension.trim()];}
function curriculumHtml(id){const c=g.OrbisCurriculum.info(id);return `<details class="iq-curriculum"><summary>${c.codes.length?'BNCC · apoio parcial':'Extensão universitária / aprofundamento'}</summary><p>${esc(c.scope)}</p>${c.codes.length?`<p class="iq-codes">${c.codes.map(esc).join(' · ')}</p>`:''}<button type="button" class="platform-link" data-platform-page="curriculum">Consultar organização curricular</button></details>`;}
function render(){if(!host||!activeId)return;const d=draft(activeId),p=plan(activeId),labels=['Prever','Experimentar','Comparar','Concluir'],done=progress(d);
 host.innerHTML=`<div class="iq-title"><span class="platform-kicker">CADERNO DE INVESTIGAÇÃO</span><h2>Meu registro</h2></div><p class="iq-question">${esc(p.question)}</p><nav class="iq-steps" aria-label="Etapas da investigação">${labels.map((s,i)=>`<button type="button" data-iq-stage="${i}" aria-pressed="${d.stage===i}"${d.stage===i?' aria-current="step"':''}>${i+1}. ${s}${done[i]?' · registrado':''}</button>`).join('')}</nav><div class="iq-page">
${d.stage===0?`<label for="iqPrediction">O que você espera? Por quê?</label><textarea id="iqPrediction" data-iq-field="prediction" maxlength="4000" rows="6" placeholder="Registre sua previsão antes de calcular.">${esc(d.prediction)}</textarea><details><summary>Objetivo e proposta</summary><p>${esc(p.goal)}</p><p>${esc(p.experiment)}</p></details>`:''}
${d.stage===1?`<p>${esc(p.experiment)}</p><button type="button" class="platform-primary" id="iqCapture">Capturar ensaio atual</button><p class="iq-help">Calcule e revele o resultado no laboratório antes de capturar. Até 8 ensaios por investigação.</p><div id="iqTrials">${trialsHtml(d)}</div>`:''}
${d.stage===2?`<p>Compare as entradas e os resultados registrados. O que mudou? O que permaneceu?</p>${comparisonHtml(d)}<label for="iqComparison">Evidências e comparação</label><textarea id="iqComparison" data-iq-field="comparison" maxlength="4000" rows="5" placeholder="Cite os ensaios e os valores que sustentam sua observação.">${esc(d.comparison)}</textarea>`:''}
${d.stage===3?`<label for="iqConclusion">Conclusão e limites</label><textarea id="iqConclusion" data-iq-field="conclusion" maxlength="4000" rows="4" placeholder="Sua previsão se confirmou? Justifique; exemplos não são uma demonstração geral.">${esc(d.conclusion)}</textarea><p>${esc(p.challenge)}</p><label for="iqExtension">Novo problema ou contraexemplo</label><textarea id="iqExtension" data-iq-field="extension" maxlength="4000" rows="3">${esc(d.extension)}</textarea><label for="iqAssessment">Como você avalia sua explicação?</label><select id="iqAssessment" data-iq-field="selfAssessment"><option value="">Escolha uma reflexão</option>${['Preciso de ajuda para interpretar','Consigo comparar os casos','Consigo justificar e apontar limites'].map(x=>`<option${d.selfAssessment===x?' selected':''}>${esc(x)}</option>`).join('')}</select><details><summary>Critérios para conversar com o professor</summary><p>${esc(p.criteria)}</p></details><button type="button" class="platform-primary" id="iqRecord">Registrar investigação no Caderno</button><button type="button" class="platform-secondary" id="iqNew">Nova investigação neste laboratório</button>`:''}
</div><div class="iq-step-actions">${d.stage>0?'<button type="button" class="platform-secondary" data-iq-previous>Anterior</button>':''}${d.stage<3?'<button type="button" class="platform-primary" data-iq-next>Continuar registro</button>':''}</div><p class="iq-status" id="iqStatus" role="status" aria-live="polite">${esc(loadWarning||'Rascunho salvo neste dispositivo. Acesso livre às etapas.')}</p>${curriculumHtml(activeId)}`;
 host.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.iqStage!==undefined){d.stage=Number(b.dataset.iqStage);touch();render();}if(b.hasAttribute('data-iq-next')){d.stage=Math.min(3,d.stage+1);touch();render();}if(b.hasAttribute('data-iq-previous')){d.stage=Math.max(0,d.stage-1);touch();render();}if(b.id==='iqCapture')capture();if(b.id==='iqRecord')record();if(b.id==='iqNew')newInvestigation();};
 host.oninput=e=>{const k=e.target.dataset.iqField;if(fields.includes(k)){d[k]=e.target.value.slice(0,4000);touch();message('Rascunho salvo neste dispositivo.');}};
 available();
}
function trialsHtml(d){return d.trials.length?d.trials.map((t,i)=>`<details class="iq-trial"><summary>Ensaio ${i+1} · ${new Date(t.at).toLocaleTimeString('pt-BR')}</summary><dl>${Object.entries(t.values).map(([k,v])=>`<div><dt>${esc(lab(d.labId).fields?.find(f=>f.key===k)?.label||k)}</dt><dd>${esc(v)}</dd></div>`).join('')}${t.metrics.map(m=>`<div><dt>${esc(m.label)}</dt><dd>${esc(g.LabKit.fmt(m.value))}</dd></div>`).join('')}</dl></details>`).join(''):'<p class="iq-help">Nenhum ensaio capturado.</p>';}
function comparisonHtml(d){if(d.trials.length<2)return '<p class="iq-help">Capture pelo menos dois ensaios para compará-los aqui.</p>';const a=d.trials.at(-2),b=d.trials.at(-1),changed=Object.keys(b.values).filter(k=>a.values[k]!==b.values[k]);return `<p class="iq-help">Últimos ensaios: ${d.trials.length-1} e ${d.trials.length}. ${changed.length} entrada(s) alterada(s).</p><div class="iq-table"><table><caption>Comparação dos últimos ensaios</caption><thead><tr><th scope="col">Item</th><th scope="col">Anterior</th><th scope="col">Atual</th></tr></thead><tbody>${changed.map(k=>`<tr><th scope="row">${esc(lab(d.labId).fields?.find(f=>f.key===k)?.label||k)}</th><td>${esc(a.values[k])}</td><td>${esc(b.values[k])}</td></tr>`).join('')}${b.metrics.map(m=>{const old=a.metrics.find(x=>x.label===m.label);return old?`<tr><th scope="row">${esc(m.label)}</th><td>${esc(g.LabKit.fmt(old.value))}</td><td>${esc(g.LabKit.fmt(m.value))}</td></tr>`:'';}).join('')}</tbody></table></div>`;}
function capture(){const d=draft(activeId),s=current(activeId);if(!s){message('Calcule e revele o resultado antes de capturar.',true);return;}if(d.trials.length>=MAX){message('Oito ensaios registrados. Conclua e inicie outra investigação para continuar.',true);return;}const t={at:new Date().toISOString(),values:copy(s.values),metrics:copy(s.result.metrics)};if(d.trials.length&&JSON.stringify(d.trials.at(-1).values)===JSON.stringify(t.values)){message('As entradas são iguais às do último ensaio. Altere uma condição para comparar.',true);return;}d.trials.push(t);touch();render();message('Ensaio '+d.trials.length+' capturado.');}
function snapshot(id=activeId){if(!id)return null;const d=copy(draft(id));d.plan=copy(plan(id));return clean(d);}
function summary(raw){const d=raw,p=d.plan||plan(d.labId);return ['Pergunta: '+p.question,'Previsão: '+d.prediction,...d.trials.map((t,i)=>'Ensaio '+(i+1)+'\n'+Object.entries(t.values).map(([k,v])=>`${lab(d.labId).fields?.find(f=>f.key===k)?.label||k}: ${v}`).join('\n')+'\n'+t.metrics.map(m=>`${m.label}: ${g.LabKit.fmt(m.value)}`).join('\n')),'Comparação: '+d.comparison,'Conclusão e limites: '+d.conclusion,'Novo problema: '+d.extension,'Autoavaliação: '+d.selfAssessment].join('\n\n');}
function record(){const d=draft(activeId);if(!d.trials.length){message('Capture um ensaio para vincular evidências à investigação.',true);return;}if(!d.conclusion.trim()){message('Escreva sua conclusão antes de registrar a investigação.',true);return;}const snap=snapshot();g.OrbisPlatform.recordInvestigation(snap,summary(snap));}
async function newInvestigation(){const ok=await g.OrbisVRuntime.AppUI.confirm('Registre primeiro no Caderno o que deseja conservar. O rascunho atual deste laboratório será substituído.','Iniciar outra investigação?');if(!ok)return;delete data.drafts[activeId];persist();render();}
function mount(id,node){activeId=id;host=node;data.lastLabId=id;persist();render();}
function unmount(){if(host){host.innerHTML='';if(host.id==='nativeInquiryPanel'){host.hidden=true;document.querySelector('[data-native-inquiry]')?.setAttribute('aria-expanded','false');}}host=null;activeId=null;}
function restore(raw){const d=clean(raw);data.drafts[d.labId]=d;if(d.plan)data.plans[d.labId]=cleanPlan(d.plan);data.lastLabId=d.labId;persist();}
function evidenceHtml(raw){const d=clean(raw);return `<details class="iq-saved"><summary>Processo de investigação · ${d.trials.length} ensaio(s)</summary><p>${esc(d.plan?.question||plan(d.labId).question)}</p>${fields.filter(k=>!['feedback','selfAssessment'].includes(k)).map(k=>`<section><h3>${({prediction:'Previsão',comparison:'Comparação',conclusion:'Conclusão',extension:'Novo problema'})[k]}</h3><p class="iq-prewrap">${esc(d[k]||'Não registrado.')}</p></section>`).join('')}${trialsHtml(d)}<p>Autoavaliação: ${esc(d.selfAssessment||'Não registrada.')}</p></details><label for="noteTeacherFeedback">Devolutiva do professor</label><textarea id="noteTeacherFeedback" data-note-feedback maxlength="4000" rows="3" placeholder="Comente as evidências, a argumentação e o próximo passo.">${esc(d.feedback)}</textarea>`;}
function teacherHtml(){return `<section class="platform-catalog-head"><div><span class="platform-kicker">MEDIAÇÃO E PLANEJAMENTO</span><h1>Roteiros do professor</h1><p>Prepare uma pergunta, organize os testes e combine como as descobertas serão discutidas.</p></div></section><div class="teacher-layout"><aside><label for="teacherLab">Laboratório do roteiro</label><select id="teacherLab">${g.OrbisCatalog.areas.map(a=>`<optgroup label="${esc(a.title)}">${a.labs.map(l=>`<option value="${l.id}">${esc(l.title)}</option>`).join('')}</optgroup>`).join('')}</select><div id="teacherCurriculum"></div><div class="teacher-guidance"><h2>Conversa sobre evidências</h2><p>Peça uma previsão antes da simulação. Combine uma condição a alterar e dê tempo para justificar resultados inesperados.</p><p>Em dupla, uma pessoa opera e outra registra; depois troquem os papéis. Ao final, comparem argumentos e busquem limites ou contraexemplos.</p><p>O preenchimento do registro indica participação na atividade; a aprendizagem é avaliada pelo professor a partir das evidências.</p><a href="docs/GUIA_PEDAGOGICO.md" download>Baixar guia pedagógico</a></div></aside><form id="teacherForm"><div class="teacher-fields">${[['title','Título'],['audience','Turma / público'],['duration','Tempo previsto'],['mode','Organização da atividade'],['question','Pergunta de investigação'],['goal','Objetivo observável'],['experiment','Protocolo de exploração'],['challenge','Transferência: novo problema'],['criteria','Critérios de apreciação']].map(([k,label])=>`<label for="teacher-${k}">${label}${['title','audience','duration','mode'].includes(k)?`<input id="teacher-${k}" name="${k}" maxlength="${k==='title'?140:4000}">`:`<textarea id="teacher-${k}" name="${k}" rows="3" maxlength="4000"></textarea>`}</label>`).join('')}</div><div class="platform-actions"><button class="platform-primary" type="submit">Salvar roteiro</button><button class="platform-secondary" id="teacherOpen" type="button">Abrir investigação</button><button class="platform-secondary" id="teacherExport" type="button">Exportar roteiro</button><button class="platform-secondary" id="teacherImportButton" type="button">Importar roteiro</button></div><input id="teacherImport" type="file" accept=".json,application/json" hidden><p id="teacherStatus" role="status" aria-live="polite">Os roteiros ficam neste dispositivo. Exporte o arquivo para usar em outra máquina ou distribuir à turma.</p></form></div>`;}
function bindTeacher(){const selector=$('teacherLab');if(!selector)return;let selected=data.lastLabId||g.OrbisCatalog.areas[0].labs[0].id;selector.value=selected;
const fill=()=>{const p=plan(selected);for(const k of Object.keys(p))if($('teacher-'+k))$('teacher-'+k).value=p[k];$('teacherCurriculum').innerHTML=curriculumHtml(selected);};
const read=()=>cleanPlan({labId:selected,...Object.fromEntries(new FormData($('teacherForm')))});
const save=()=>{const p=read();data.plans[selected]=p;if(!persist())throw new Error('Não foi possível salvar o roteiro neste dispositivo.');return p;};
selector.onchange=()=>{try{save();selected=selector.value;fill();message('Roteiro anterior salvo.');}catch(e){selector.value=selected;message(e.message,true);}};
$('teacherForm').onsubmit=e=>{e.preventDefault();try{save();message('Roteiro salvo. Será usado neste laboratório.');}catch(err){message(err.message,true);}};
$('teacherOpen').onclick=()=>{try{save();g.OrbisPlatform.openLab(selected);}catch(e){message(e.message,true);}};
$('teacherExport').onclick=()=>{try{const p=save();g.OrbisVRuntime.AppUI.download(JSON.stringify({format:'orbisv-teacher-plan',version:1,plan:p},null,2),'application/json','OrbisV-Roteiro-'+selected+'.json');}catch(e){message(e.message,true);}};
$('teacherImportButton').onclick=()=>$('teacherImport').click();$('teacherImport').onchange=async()=>{try{const f=$('teacherImport').files[0];if(!f)return;if(f.size>128*1024)throw new Error('O roteiro excede 128 KB.');const raw=JSON.parse(await f.text());if(raw.format!=='orbisv-teacher-plan'||raw.version!==1)throw new Error('Formato de roteiro não reconhecido.');const p=cleanPlan(raw.plan);if(data.plans[p.labId]&&JSON.stringify(data.plans[p.labId])!==JSON.stringify(p)){const ok=await g.OrbisVRuntime.AppUI.confirm('O roteiro deste laboratório já foi personalizado. Substituí-lo pelo arquivo importado?','Importar roteiro?');if(!ok)return;}data.plans[p.labId]=p;persist();selected=p.labId;selector.value=selected;fill();message('Roteiro importado. Abra a investigação para utilizá-lo.');}catch(e){message(e.message,true);}finally{$('teacherImport').value='';}};fill();}
g.OrbisInquiry={mount,unmount,available,snapshot,clean,cleanPlan,restore,summary,evidenceHtml,teacherHtml,bindTeacher,plan,progress,lastLab:()=>data.lastLabId,data:()=>copy(data)};
})(window);
