(function(global){
  'use strict';
  const M=(id,category,mode,title,formula,draft,description,tags=[])=>({id,category,mode,title,formula,draft,description,tags});
  const models=[
    M('fn-identity','Fundamentos','function','Função identidade','f(x)=x',{expression:'x',xMin:'-10',xMax:'10'},'Reta que passa pela origem com coeficiente angular 1.'),
    M('fn-constant','Fundamentos','function','Função constante','f(x)=c',{expression:'c',xMin:'-10',xMax:'10'},'Família de retas horizontais controlada pelo parâmetro c.'),
    M('fn-affine','Funções','function','Função afim','f(x)=ax+b',{expression:'a*x+b',xMin:'-10',xMax:'10'},'Modelo geral da função afim, com parâmetros a e b.'),
    M('fn-quadratic-general','Funções','function','Quadrática — forma geral','f(x)=ax²+bx+c',{expression:'a*x^2+b*x+c',xMin:'-10',xMax:'10'},'Forma geral de uma função quadrática.'),
    M('fn-quadratic-vertex','Funções','function','Quadrática — forma canônica','f(x)=a(x−h)²+k',{expression:'a*(x-h)^2+k',xMin:'-10',xMax:'10'},'Destaca vértice, abertura e translações.'),
    M('fn-quadratic-factored','Funções','function','Quadrática — forma fatorada','f(x)=a(x−x₁)(x−x₂)',{expression:'a*(x-x_1)*(x-x_2)',xMin:'-10',xMax:'10'},'Relaciona diretamente as raízes x₁ e x₂.'),
    M('fn-cubic','Funções','function','Função cúbica','f(x)=ax³+bx²+cx+d',{expression:'a*x^3+b*x^2+c*x+d',xMin:'-8',xMax:'8'},'Polinômio cúbico geral.'),
    M('fn-absolute','Funções','function','Valor absoluto','f(x)=a|x−h|+k',{expression:'a*abs(x-h)+k',xMin:'-10',xMax:'10'},'Transformações da função módulo.'),
    M('fn-root','Funções','function','Função raiz','f(x)=a√(x−h)+k',{expression:'a*sqrt(x-h)+k',xMin:'-2',xMax:'12'},'Modelo de radical com translação e escala.'),
    M('fn-reciprocal','Funções','function','Função recíproca','f(x)=a/(x−h)+k',{expression:'a/(x-h)+k',xMin:'-10',xMax:'10'},'Modelo racional com assíntotas vertical e horizontal.'),
    M('fn-inverse-square','Funções','function','Inverso do quadrado','f(x)=a/(x−h)²+k',{expression:'a/(x-h)^2+k',xMin:'-10',xMax:'10'},'Família racional de simetria vertical.'),
    M('fn-exp','Exponenciais','function','Exponencial','f(x)=a·bˣ+k',{expression:'a*b^x+k',xMin:'-6',xMax:'6'},'Crescimento ou decaimento exponencial.'),
    M('fn-exp-e','Exponenciais','function','Exponencial natural','f(x)=a·e^(kx)+c',{expression:'a*exp(k*x)+c',xMin:'-6',xMax:'6'},'Modelo com base e para crescimento e decaimento contínuos.'),
    M('fn-log','Exponenciais','function','Logaritmo decimal','f(x)=a·log(x−h)+k',{expression:'a*log(x-h)+k',xMin:'0.1',xMax:'12'},'Transformações da função logarítmica decimal.'),
    M('fn-ln','Exponenciais','function','Logaritmo natural','f(x)=a·ln(x−h)+k',{expression:'a*ln(x-h)+k',xMin:'0.1',xMax:'12'},'Transformações do logaritmo natural.'),
    M('fn-sine','Trigonometria','function','Senoide geral','f(x)=A·sen(B(x−C))+D',{expression:'a*sin(b*(x-c))+d',xMin:'-2*pi',xMax:'2*pi'},'Amplitude, período, fase e linha média.'),
    M('fn-cosine','Trigonometria','function','Cossenoide geral','f(x)=A·cos(B(x−C))+D',{expression:'a*cos(b*(x-c))+d',xMin:'-2*pi',xMax:'2*pi'},'Forma geral da função cosseno.'),
    M('fn-tangent','Trigonometria','function','Tangente geral','f(x)=A·tg(B(x−C))+D',{expression:'a*tan(b*(x-c))+d',xMin:'-pi',xMax:'pi'},'Família da tangente com assíntotas periódicas.'),
    M('fn-sec','Trigonometria','function','Secante','f(x)=sec(x)',{expression:'sec(x)',xMin:'-2*pi',xMax:'2*pi'},'Função recíproca do cosseno.'),
    M('fn-csc','Trigonometria','function','Cossecante','f(x)=cossec(x)',{expression:'csc(x)',xMin:'-2*pi',xMax:'2*pi'},'Função recíproca do seno.'),
    M('fn-cot','Trigonometria','function','Cotangente','f(x)=cotg(x)',{expression:'cot(x)',xMin:'-2*pi',xMax:'2*pi'},'Função recíproca da tangente.'),
    M('fn-asine','Trigonometria','function','Arco seno','f(x)=arcsen(x)',{expression:'asin(x)',xMin:'-1',xMax:'1'},'Função inversa do seno.'),
    M('fn-acos','Trigonometria','function','Arco cosseno','f(x)=arccos(x)',{expression:'acos(x)',xMin:'-1',xMax:'1'},'Função inversa do cosseno.'),
    M('fn-atan','Trigonometria','function','Arco tangente','f(x)=arctg(x)',{expression:'atan(x)',xMin:'-10',xMax:'10'},'Função inversa da tangente.'),
    M('fn-sinh','Hiperbólicas','function','Seno hiperbólico','f(x)=senh(x)',{expression:'sinh(x)',xMin:'-4',xMax:'4'},'Função hiperbólica seno.'),
    M('fn-cosh','Hiperbólicas','function','Cosseno hiperbólico','f(x)=cosh(x)',{expression:'cosh(x)',xMin:'-4',xMax:'4'},'Catenária básica.'),
    M('fn-tanh','Hiperbólicas','function','Tangente hiperbólica','f(x)=tanh(x)',{expression:'tanh(x)',xMin:'-5',xMax:'5'},'Função sigmoidal hiperbólica.'),
    M('fn-removable','Cálculo','function','Descontinuidade removível','f(x)=(x²−1)/(x−1)',{expression:'(x^2-1)/(x-1)',xMin:'-5',xMax:'5'},'Exemplo clássico para estudo de limite em x=1.'),
    M('fn-asymptote','Cálculo','function','Assíntota vertical','f(x)=1/x',{expression:'1/x',xMin:'-8',xMax:'8'},'Modelo simples para limites laterais e assíntotas.'),
    M('fn-limit-infinity','Cálculo','function','Limite no infinito','f(x)=(2x²+1)/(x²−3)',{expression:'(2*x^2+1)/(x^2-3)',xMin:'-10',xMax:'10'},'Exemplo para análise de comportamento assintótico.'),
    M('par-circle','Paramétricas','parametric','Circunferência paramétrica','x=r cos(t), y=r sen(t)',{xExpr:'r*cos(t)',yExpr:'r*sin(t)',tMin:'0',tMax:'2*pi'},'Circunferência de raio r.'),
    M('par-ellipse','Paramétricas','parametric','Elipse paramétrica','x=a cos(t), y=b sen(t)',{xExpr:'a*cos(t)',yExpr:'b*sin(t)',tMin:'0',tMax:'2*pi'},'Elipse com semieixos a e b.'),
    M('par-lissajous','Paramétricas','parametric','Curva de Lissajous','x=a sen(nt+δ), y=b sen(mt)',{xExpr:'a*sin(n*t+d)',yExpr:'b*sin(m*t)',tMin:'0',tMax:'2*pi'},'Família de curvas periódicas de Lissajous.'),
    M('par-cycloid','Paramétricas','parametric','Cicloide','x=r(t−sen t), y=r(1−cos t)',{xExpr:'r*(t-sin(t))',yExpr:'r*(1-cos(t))',tMin:'0',tMax:'4*pi'},'Trajetória de um ponto em uma circunferência rolante.'),
    M('par-spiral','Paramétricas','parametric','Espiral de Arquimedes','x=t cos(t), y=t sen(t)',{xExpr:'t*cos(t)',yExpr:'t*sin(t)',tMin:'0',tMax:'6*pi'},'Espiral com raio crescendo linearmente com t.'),
    M('par-astroid','Paramétricas','parametric','Astroide','x=a cos³(t), y=a sen³(t)',{xExpr:'a*cos(t)^3',yExpr:'a*sin(t)^3',tMin:'0',tMax:'2*pi'},'Curva algébrica clássica de quatro cúspides.'),
    M('vec-basic','Vetores','vector','Vetor básico','v=(3,4)',{x1:'0',y1:'0',x2:'3',y2:'4'},'Exemplo 3-4-5 para módulo e direção.'),
    M('vec-origin','Vetores','vector','Vetor com origem deslocada','A→B',{x1:'-2',y1:'-1',x2:'3',y2:'2'},'Vetor entre dois pontos distintos da origem.'),
    M('geo-point','Geometria','geometry','Ponto','P=(2,1)',{type:'point',x:'2',y:'1'},'Ponto cartesiano simples.'),
    M('geo-line','Geometria','geometry','Reta — forma geral','2x+3y−6=0',{type:'line',a:'2',b:'3',c:'-6'},'Reta na forma ax+by+c=0.'),
    M('geo-circle','Cônicas','geometry','Circunferência','(x−h)²+(y−k)²=r²',{type:'circle',cx:'0',cy:'0',r:'3'},'Circunferência por centro e raio.'),
    M('geo-ellipse','Cônicas','geometry','Elipse','(x−h)²/a²+(y−k)²/b²=1',{type:'ellipse',cx:'0',cy:'0',ea:'4',eb:'2'},'Elipse por centro e semieixos.'),
    M('geo-triangle','Geometria','geometry','Triângulo','A, B, C',{type:'polygon',vertices:[[-3,-2],[3,-2],[0,3]]},'Triângulo isósceles de referência.'),
    M('geo-square','Geometria','geometry','Quadrado','A, B, C, D',{type:'polygon',vertices:[[-2,-2],[2,-2],[2,2],[-2,2]]},'Quadrado centrado na origem.'),
    M('wash-disk','Cálculo integral','washers','Discos — √x','V=π∫R(x)²dx',{method:'disks',axis:'x',outerExpr:'sqrt(x)',innerExpr:'0',a:'0',b:'4'},'Exemplo de volume por discos em torno do eixo x.'),
    M('wash-ring','Cálculo integral','washers','Anéis — duas curvas','V=π∫(R²−r²)dx',{method:'washers',axis:'x',outerExpr:'sqrt(x)+1',innerExpr:'1',a:'0',b:'4'},'Exemplo de volume por anéis.'),
    M('wash-y','Cálculo integral','washers','Discos em torno de y','V=π∫R(y)²dy',{method:'disks',axis:'y',outerExpr:'sqrt(y)',innerExpr:'0',a:'0',b:'4'},'Exemplo com integração em y.')
  ];
  const categories=[...new Set(models.map(m=>m.category))];
  global.OrbisVModels=Object.freeze({models:Object.freeze(models),categories:Object.freeze(categories),byMode:(mode)=>models.filter(m=>m.mode===mode),find:(id)=>models.find(m=>m.id===id)||null});
})(window);
