(function (global) {
  'use strict';

  const colors = ['#5ac8fa','#b28cff','#ff6fae','#63d391','#ffd166','#ff9f66','#78a7ff','#d29bff'];
  const symbols = [['π','pi'],['√','sqrt('],['x²','^2'],['x³','^3'],['×','*'],['÷','/'],['·','*'],['sin','sin('],['cos','cos('],['tan','tan('],['asin','asin('],['acos','acos('],['sqrt','sqrt('],['log','log('],['ln','ln('],['abs','abs('],['exp','exp('],['τ','tau'],['φ','phi'],['(', '('],[')', ')']];
  const menuHtml = symbols.map(([label, value]) => `<button type="button" data-insert="${value}" aria-label="Inserir ${label}">${label}</button>`).join('');
  const ICON = Object.freeze({ hide: '<svg viewBox="0 0 24 24" width="15" height="15" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6z" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="12" r="2.5" fill="currentColor"/></svg>', show: '<svg viewBox="0 0 24 24" width="15" height="15" aria-hidden="true"><path d="M3 12s3-5.5 9-5.5 9 5.5 9 5.5-3 5.5-9 5.5S3 12 3 12z" fill="none" stroke="currentColor" stroke-width="2"/></svg>' });

  const AppUI = {
    objects: null, engine: null, history: [], activeTab: 'function', editingId: null, statusTimer: null, toastTimer: null,
    init(objects, engine) {
      this.objects = objects; this.engine = engine; this.cache(); this.buildMenus(); this.bindTabs(); this.bindForms(); this.initGeometryFields(); this.bindObjectEvents(); this.loadHistory(); this.objects.load(); this.renderObjects(); this.updatePreviews(); this.updateVectorResult(); this.updateUndoButtons(); this.updateEmptyState();
    },
    cache() {
      this.lastMathInputId='functionExpr';
      this.$ = { tabs:[...document.querySelectorAll('.tab')], panels:[...document.querySelectorAll('.tab-panel')], functionExpr:document.getElementById('functionExpr'), paramX:document.getElementById('paramX'), paramY:document.getElementById('paramY'), tMin:document.getElementById('tMin'), tMax:document.getElementById('tMax'), objectsList:document.getElementById('objectsList'), historyList:document.getElementById('historyList'), geometryType:document.getElementById('geometryType'), geometryFields:document.getElementById('geometryFields'), status:document.getElementById('statusText'), emptyState:document.getElementById('emptyState'), coordinate:document.getElementById('coordinateReadout'), toast:document.getElementById('toast'), addFunction:document.getElementById('addFunctionBtn'), addParam:document.getElementById('addParamBtn'), addVector:document.getElementById('addVectorBtn'), addGeometry:document.getElementById('addGeometryBtn'), clearObjects:document.getElementById('clearObjectsBtn'), clearHistory:document.getElementById('clearHistoryBtn'), undo:document.getElementById('undoBtn'), redo:document.getElementById('redoBtn'), collapse:document.getElementById('collapseControlsBtn'), showControls:document.getElementById('showControlsBtn'), controls:document.querySelector('.controls-panel'), workspace:document.querySelector('.workspace'), shell:document.querySelector('.app-shell') };
    },
    buildMenus() { document.querySelectorAll('.math-menu').forEach((m)=>{m.innerHTML=menuHtml;}); const globalMenu=document.getElementById('globalMathMenu'); if(globalMenu) globalMenu.innerHTML=menuHtml; document.querySelectorAll('.dropdown-btn').forEach((b)=>b.addEventListener('click',()=>{const m=document.getElementById(b.dataset.menu);if(m)m.classList.toggle('hidden');})); const globalBtn=document.getElementById('globalMathBtn'); if(globalBtn)globalBtn.addEventListener('click',()=>{const open=document.getElementById('globalMathMenu')?.classList.toggle('hidden')===false;globalBtn.setAttribute('aria-expanded',String(open));}); document.querySelectorAll('.math-menu [data-insert]').forEach((b)=>b.addEventListener('click',()=>{this.insertAtActive(b.dataset.insert);document.querySelectorAll('.math-menu').forEach(m=>m.classList.add('hidden'));const gb=document.getElementById('globalMathBtn');if(gb)gb.setAttribute('aria-expanded','false');})); document.addEventListener('click',(e)=>{if(!e.target.closest('.math-editor')&&!e.target.closest('.global-math-tools')){document.querySelectorAll('.math-menu').forEach(m=>m.classList.add('hidden'));const gb=document.getElementById('globalMathBtn');if(gb)gb.setAttribute('aria-expanded','false');}}); },
    bindTabs() { this.$.tabs.forEach((tab)=>tab.addEventListener('click',()=>this.setTab(tab.dataset.tab))); },
    setTab(tabName) { this.cancelEdit(); this.activeTab=tabName; this.$.tabs.forEach((t)=>{const active=t.dataset.tab===tabName;t.classList.toggle('active',active);t.setAttribute('aria-selected',String(active));}); this.$.panels.forEach((p)=>{const active=p.dataset.panel===tabName;p.classList.toggle('active',active);p.hidden=!active;}); this.updatePreviews(); },
    bindForms() {
      ['functionExpr','paramX','paramY','tMin','tMax'].forEach(id=>document.getElementById(id).addEventListener('input',()=>{this.normalizeInput(id);this.updatePreviews();this.validateExpressionField(document.getElementById(id));}));
      document.querySelectorAll('input').forEach((input)=>input.addEventListener('focus',()=>{this.lastMathInputId=input.id;}));
      document.querySelectorAll('.clear-field-btn').forEach((btn)=>btn.addEventListener('click',()=>this.clearField(btn.dataset.clear)));
      document.querySelectorAll('.numeric-input').forEach((input)=>{input.addEventListener('input',()=>this.validateNumericField(input));this.validateNumericField(input);});
      this.$.addFunction.addEventListener('click',()=>this.addFunction()); this.$.addParam.addEventListener('click',()=>this.addParametric()); this.$.addVector.addEventListener('click',()=>this.addVector());
      ['vx1','vy1','vx2','vy2','v2x','v2y'].forEach(id=>document.getElementById(id).addEventListener('input',()=>this.updateVectorResult()));
      document.getElementById('dotBtn').addEventListener('click',()=>this.vectorOperation('dot')); document.getElementById('crossBtn').addEventListener('click',()=>this.vectorOperation('cross'));
      document.getElementById('geometryType').addEventListener('change',()=>{this.initGeometryFields();this.updateGeometryPreview();}); this.$.addGeometry.addEventListener('click',()=>this.addGeometry());
      this.$.clearObjects.addEventListener('click',()=>{this.objects.clear();this.persistSession();}); this.$.clearHistory.addEventListener('click',()=>this.clearHistory()); this.$.undo.addEventListener('click',()=>this.undo()); this.$.redo.addEventListener('click',()=>this.redo());
      document.getElementById('resetViewBtn').addEventListener('click',()=>this.engine.center()); document.getElementById('gridBtn').addEventListener('click',(e)=>{this.engine.showGrid=!this.engine.showGrid;e.currentTarget.setAttribute('aria-pressed',String(this.engine.showGrid));this.engine.requestRender();}); document.getElementById('axesBtn').addEventListener('click',(e)=>{this.engine.showAxes=!this.engine.showAxes;e.currentTarget.setAttribute('aria-pressed',String(this.engine.showAxes));this.engine.requestRender();});
      document.getElementById('exportBtn').addEventListener('click',()=>this.engine.exportPng()); document.getElementById('exportSvgBtn').addEventListener('click',()=>this.engine.exportSvg()); document.getElementById('fullscreenBtn').addEventListener('click',()=>this.toggleFullscreen());
      document.querySelectorAll('.quick-grid').forEach((grid)=>grid.addEventListener('click',(e)=>{const btn=e.target.closest('[data-token]');if(btn)this.insertText(btn.dataset.token,grid.dataset.target);}));
      const toggleControls=(force=null)=>{const collapsed=force===null?!this.$.controls.classList.contains('collapsed'):Boolean(force);this.$.controls.classList.toggle('collapsed',collapsed);this.$.workspace?.classList.toggle('controls-collapsed',collapsed);this.$.collapse.setAttribute('aria-pressed',String(collapsed));this.$.collapse.setAttribute('aria-label',collapsed?'Mostrar controles':'Ocultar controles');this.$.collapse.setAttribute('title',collapsed?'Mostrar controles':'Ocultar controles');const leftIcon=this.$.collapse.querySelector('.collapse-icon-left');const rightIcon=this.$.collapse.querySelector('.collapse-icon-right');const collapseText=this.$.collapse.querySelector('.collapse-text');leftIcon?.classList.toggle('hidden',collapsed);rightIcon?.classList.toggle('hidden',!collapsed);if(collapseText)collapseText.textContent=collapsed?'Mostrar controles':'Ocultar controles';this.$.showControls?.classList.toggle('hidden',!collapsed);this.$.showControls?.setAttribute('aria-hidden',String(!collapsed));requestAnimationFrame(()=>requestAnimationFrame(()=>{this.engine.resize();this.engine.requestRender();}));};
      this.$.collapse.addEventListener('click',()=>toggleControls());
      this.$.showControls?.addEventListener('click',()=>toggleControls(false));
      document.querySelectorAll('[data-tooltip]').forEach((el)=>el.setAttribute('title',el.dataset.tooltip));
      this.bindKeyboard();
    },
    bindObjectEvents() { this.objects.onChange=()=>{this.renderObjects();this.engine.invalidateCache();this.engine.requestRender();this.updateUndoButtons();this.updateEmptyState();this.persistSession();}; },
    bindKeyboard() {
      document.addEventListener('keydown',(e)=>{
        const tag=document.activeElement?.tagName;
        if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?this.redo():this.undo();return;}
        if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();this.redo();return;}
        if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='enter'){e.preventDefault();this.addActiveTab();return;}
        if((e.key==='ArrowLeft'||e.key==='ArrowRight')&&tag==='BUTTON'&&document.activeElement?.classList.contains('tab')){e.preventDefault();this.moveTab(e.key==='ArrowRight'?1:-1);return;}
      });
    },
    moveTab(delta){const i=this.$.tabs.findIndex(t=>t.dataset.tab===this.activeTab);const next=(i+delta+this.$.tabs.length)%this.$.tabs.length;this.$.tabs[next].focus();this.setTab(this.$.tabs[next].dataset.tab);},
    addActiveTab(){if(this.activeTab==='function')this.addFunction();else if(this.activeTab==='parametric')this.addParametric();else if(this.activeTab==='vector')this.addVector();else this.addGeometry();},
    normalizeInput(id){const input=document.getElementById(id);if(!input)return;const start=input.selectionStart??input.value.length;const before=input.value;const after=before.replace(/pi\b/gi,'π').replace(/tau\b/gi,'τ').replace(/phi\b/gi,'φ').replace(/sqrt\s*\(/gi,'√(').replace(/\^2(?!\d)/g,'²').replace(/\^3(?!\d)/g,'³').replace(/\*/g,'×').replace(/\//g,'÷').replace(/-/g,'−');if(after!==before){input.value=after;const delta=after.length-before.length;const pos=Math.max(0,Math.min(after.length,start+delta));input.setSelectionRange(pos,pos);}},
    toMathEngine(expr){return MathEngine.normalize(expr);},
    toLatex(expr){let s=String(expr??'').trim().replace(/−/g,'-').replace(/π/g,'\\pi').replace(/τ/g,'\\tau').replace(/φ/g,'\\phi').replace(/²/g,'^{2}').replace(/³/g,'^{3}').replace(/×/g,'\\cdot ').replace(/÷/g,'\\div ').replace(/\b(sin|cos|tan|asin|acos|atan|sinh|cosh|tanh|log|log2|ln|sqrt|abs|exp|sign)\b/g,'\\$1'); s=this.convertFractionsToLatex(s); s=s.replace(/√\(([^()]*)\)/g,'\\sqrt{$1}'); return s||'\\;';},
    convertFractionsToLatex(s){let out=s;for(let i=0;i<3;i++){out=out.replace(/\(([^()]+)\)\s*\\div\s*\(([^()]+)\)/g,'\\frac{$1}{$2}').replace(/\b([0-9]+(?:\.[0-9]+)?)\s*\\div\s*([0-9]+(?:\.[0-9]+)?)/g,'\\frac{$1}{$2}');}return out;},
    renderKatex(target,expr){const el=document.getElementById(target);if(!el)return;if(global.katex)global.katex.render(this.toLatex(expr),el,{throwOnError:false,displayMode:false});else el.textContent=expr;},
    updatePreviews(){this.renderKatex('functionPreview',this.$.functionExpr.value);this.renderKatex('paramPreview',`x(t) = ${this.$.paramX.value}, y(t) = ${this.$.paramY.value}`);this.updateGeometryPreview();},
    insertText(token,target){const input=document.getElementById(target);if(!input)return;const start=input.selectionStart??input.value.length,end=input.selectionEnd??input.value.length;const pretty=token==='pi'?'π':token==='tau'?'τ':token==='phi'?'φ':token==='sqrt('?'√(':token==='*'?'×':token==='/'?'÷':token==='-'?'−':token;input.value=input.value.slice(0,start)+pretty+input.value.slice(end);const pos=start+pretty.length;input.focus();input.setSelectionRange(pos,pos);this.updatePreviews();this.validateExpressionField(input);},
    insertAtActive(token){const candidate=document.activeElement?.classList?.contains('math-input')?document.activeElement.id:this.lastMathInputId;const target=document.getElementById(candidate)||document.getElementById(this.activeTab==='parametric'?'paramX':'functionExpr');this.insertText(token,target.id);},
    clearField(id){const input=document.getElementById(id);if(!input)return;input.value='';this.lastMathInputId=id;input.focus();this.updatePreviews();this.validateExpressionField(input);this.showToast('Campo limpo.');},
    validateNumericField(input){if(!input?.value.trim()){input.classList.remove('valid','invalid');return;}try{this.parseNum(input.value,{pi:Math.PI,tau:2*Math.PI,phi:(1+Math.sqrt(5))/2});input.classList.add('valid');input.classList.remove('invalid');}catch{input.classList.add('invalid');input.classList.remove('valid');}},
    validateExpressionField(input){if(!input?.value.trim()){input.classList.remove('valid','invalid');return;}try{const vars=input.id==='functionExpr'?{x:0}:{x:0,t:0};MathEngine.compile(this.toMathEngine(input.value),vars);input.classList.add('valid');input.classList.remove('invalid');}catch{input.classList.add('invalid');input.classList.remove('valid');}},
    requireNonEmpty(value, message='Preencha o campo antes de adicionar.') {if(!String(value??'').trim()){this.showToast(message,true);return false;}return true;},
    beginEdit(o){this.setTab(o.type==='function'?'function':o.type==='parametric'?'parametric':o.type==='vector'?'vector':'geometry');this.editingId=o.id;if(o.type==='function'){this.$.functionExpr.value=this.display(o.data.expression);}else if(o.type==='parametric'){this.$.paramX.value=this.display(o.data.xExpr);this.$.paramY.value=this.display(o.data.yExpr);this.$.tMin.value=o.data.tMin;this.$.tMax.value=o.data.tMax;}else if(o.type==='vector'){['vx1','vy1','vx2','vy2'].forEach((id,i)=>document.getElementById(id).value=[o.data.x1,o.data.y1,o.data.x2,o.data.y2][i]);}else{this.$.geometryType.value=o.type;this.initGeometryFields();this.fillGeometry(o);}this.$.addFunction.textContent=o.type==='function'?'Salvar alterações':'Adicionar curva';this.$.addParam.textContent=o.type==='parametric'?'Salvar alterações':'Adicionar curva paramétrica';this.$.addVector.textContent=o.type==='vector'?'Salvar alterações':'Adicionar vetor';this.$.addGeometry.textContent=['line','circle','ellipse','point'].includes(o.type)?'Salvar alterações':'Adicionar objeto geométrico';this.updatePreviews();this.showToast('Objeto carregado para edição.');},
    cancelEdit(){this.editingId=null;this.$.addFunction.textContent='Adicionar curva';this.$.addParam.textContent='Adicionar curva paramétrica';this.$.addVector.textContent='Adicionar vetor';this.$.addGeometry.textContent='Adicionar objeto geométrico';},
    addFunction(){if(!this.requireNonEmpty(this.$.functionExpr.value,'Digite uma função, por exemplo x² + sin(x).'))return;const expr=this.toMathEngine(this.$.functionExpr.value);try{MathEngine.compile(expr,{x:0});if(this.editingId){this.objects.update(this.editingId,{expression:expr});this.showToast('Curva atualizada.');}else{const obj=this.objects.add('function',{expression:expr},colors[this.objects.items.length%colors.length]);this.addHistory(`y = ${this.$.functionExpr.value}`,obj);this.showToast('Curva adicionada.');}this.cancelEdit();}catch(e){this.showError(e);}},
    addParametric(){if(!this.requireNonEmpty(this.$.paramX.value,'Preencha x(t).')||!this.requireNonEmpty(this.$.paramY.value,'Preencha y(t).'))return;const xExpr=this.toMathEngine(this.$.paramX.value),yExpr=this.toMathEngine(this.$.paramY.value);try{const tMin=this.parseNum(this.$.tMin.value,{pi:Math.PI}),tMax=this.parseNum(this.$.tMax.value,{pi:Math.PI});MathEngine.compile(xExpr,{t:0});MathEngine.compile(yExpr,{t:0});if(!(tMax>tMin))throw new Error('t máx. deve ser maior que t mín.');const data={xExpr,yExpr,tMin,tMax};if(this.editingId){this.objects.update(this.editingId,data);this.showToast('Curva paramétrica atualizada.');}else{const obj=this.objects.add('parametric',data,colors[this.objects.items.length%colors.length]);this.addHistory(`x(t) = ${this.$.paramX.value}, y(t) = ${this.$.paramY.value}`,obj);this.showToast('Curva paramétrica adicionada.');}this.cancelEdit();}catch(e){this.showError(e);}},
    parseNum(v,vars){const normalized=this.toMathEngine(String(v));if(!normalized.trim())throw new Error('Valor numérico vazio.');const n=Number(normalized);const value=Number.isFinite(n)?n:MathEngine.evalExpr(normalized,vars);if(!Number.isFinite(value))throw new Error('Valor numérico inválido. Use, por exemplo, 1,5 ou 2·π.');return value;},
    addVector(){try{const data={x1:this.parseNum(document.getElementById('vx1').value),y1:this.parseNum(document.getElementById('vy1').value),x2:this.parseNum(document.getElementById('vx2').value),y2:this.parseNum(document.getElementById('vy2').value)};if(this.editingId){this.objects.update(this.editingId,data);this.showToast('Vetor atualizado.');}else{const obj=this.objects.add('vector',data,colors[this.objects.items.length%colors.length]);this.addHistory(`Vetor (${data.x1}, ${data.y1}) → (${data.x2}, ${data.y2})`,obj);this.showToast('Vetor adicionado.');}this.cancelEdit();}catch(e){this.showError(e);}},
    updateVectorResult(){try{const x1=this.parseNum(document.getElementById('vx1').value),y1=this.parseNum(document.getElementById('vy1').value),x2=this.parseNum(document.getElementById('vx2').value),y2=this.parseNum(document.getElementById('vy2').value);const dx=x2-x1,dy=y2-y1;document.getElementById('vectorResult').textContent=`v = (${this.fmt(dx)}, ${this.fmt(dy)}) · ‖v‖ = ${this.fmt(Math.hypot(dx,dy))}`;}catch{document.getElementById('vectorResult').textContent='—';}},
    vectorOperation(type){try{const ax=this.parseNum(document.getElementById('vx2').value)-this.parseNum(document.getElementById('vx1').value),ay=this.parseNum(document.getElementById('vy2').value)-this.parseNum(document.getElementById('vy1').value),bx=this.parseNum(document.getElementById('v2x').value),by=this.parseNum(document.getElementById('v2y').value);const r=type==='dot'?ax*bx+ay*by:ax*by-ay*bx;document.getElementById('vectorOpsResult').textContent=type==='dot'?`v · w = ${this.fmt(r)}`:`v × w = ${this.fmt(r)} k̂`;this.showToast(type==='dot'?'Produto escalar calculado.':'Produto vetorial calculado.');}catch(e){this.showError(e);}},
    fmt(n){return Number(n.toFixed(8)).toString();},
    initGeometryFields(){const type=this.$.geometryType.value;let html='';if(type==='line')html='<div class="three-col"><label>a<input id="ga" class="numeric-input" type="text" value="2"></label><label>b<input id="gb" class="numeric-input" type="text" value="3"></label><label>c<input id="gc" class="numeric-input" type="text" value="-6"></label></div>';else if(type==='circle')html='<div class="three-col"><label>cx<input id="gcx" class="numeric-input" type="text" value="0"></label><label>cy<input id="gcy" class="numeric-input" type="text" value="0"></label><label>r<input id="gr" class="numeric-input" type="text" value="3"></label></div>';else if(type==='ellipse')html='<div class="four-col"><label>cx<input id="ecx" class="numeric-input" type="text" value="0"></label><label>cy<input id="ecy" class="numeric-input" type="text" value="0"></label><label>a<input id="ea" class="numeric-input" type="text" value="4"></label><label>b<input id="eb" class="numeric-input" type="text" value="2"></label></div>';else html='<div class="two-col"><label>x<input id="gpx" class="numeric-input" type="text" value="2"></label><label>y<input id="gpy" class="numeric-input" type="text" value="1"></label></div>';this.$.geometryFields.innerHTML=html;this.$.geometryFields.querySelectorAll('input').forEach((i)=>{i.addEventListener('input',()=>{this.validateNumericField(i);this.updateGeometryPreview();});this.validateNumericField(i);});this.updateGeometryPreview();},
    fillGeometry(o){const map={line:[['ga',o.data.a],['gb',o.data.b],['gc',o.data.c]],circle:[['gcx',o.data.cx],['gcy',o.data.cy],['gr',o.data.r]],ellipse:[['ecx',o.data.cx],['ecy',o.data.cy],['ea',o.data.a],['eb',o.data.b]],point:[['gpx',o.data.x],['gpy',o.data.y]]};(map[o.type]||[]).forEach(([id,v])=>{const el=document.getElementById(id);if(el)el.value=v;});this.updateGeometryPreview();},
    updateGeometryPreview(){const t=this.$.geometryType.value;let text='';try{if(t==='line'){const a=this.parseNum(document.getElementById('ga').value),b=this.parseNum(document.getElementById('gb').value),c=this.parseNum(document.getElementById('gc').value);text=`${this.fmt(a)}x + ${this.fmt(b)}y + ${this.fmt(c)} = 0`;if(Math.abs(a)<1e-12&&Math.abs(b)<1e-12)throw new Error('A e B não podem ser ambos zero.');}else if(t==='circle'){const cx=this.parseNum(document.getElementById('gcx').value),cy=this.parseNum(document.getElementById('gcy').value),r=this.parseNum(document.getElementById('gr').value);if(r<=0)throw new Error('Raio deve ser positivo.');text=`(x − ${this.fmt(cx)})² + (y − ${this.fmt(cy)})² = ${this.fmt(r)}²`;}else if(t==='ellipse'){const cx=this.parseNum(document.getElementById('ecx').value),cy=this.parseNum(document.getElementById('ecy').value),a=this.parseNum(document.getElementById('ea').value),b=this.parseNum(document.getElementById('eb').value);if(a<=0||b<=0)throw new Error('Semieixos devem ser positivos.');text=`(x − ${this.fmt(cx)})² / ${this.fmt(a)}² + (y − ${this.fmt(cy)})² / ${this.fmt(b)}² = 1`;}else{text=`P = (${this.parseNum(document.getElementById('gpx').value)}, ${this.parseNum(document.getElementById('gpy').value)})`;}this.renderKatex('geometryPreview',text);}catch(e){document.getElementById('geometryPreview').textContent=e.message;}},
    addGeometry(){const t=this.$.geometryType.value;try{let data;if(t==='line'){data={a:this.parseNum(document.getElementById('ga').value),b:this.parseNum(document.getElementById('gb').value),c:this.parseNum(document.getElementById('gc').value)};if(Math.abs(data.a)<1e-12&&Math.abs(data.b)<1e-12)throw new Error('A e B não podem ser ambos zero.');}else if(t==='circle'){data={cx:this.parseNum(document.getElementById('gcx').value),cy:this.parseNum(document.getElementById('gcy').value),r:this.parseNum(document.getElementById('gr').value)};if(data.r<=0)throw new Error('Raio deve ser positivo.');}else if(t==='ellipse'){data={cx:this.parseNum(document.getElementById('ecx').value),cy:this.parseNum(document.getElementById('ecy').value),a:this.parseNum(document.getElementById('ea').value),b:this.parseNum(document.getElementById('eb').value)};if(data.a<=0||data.b<=0)throw new Error('Semieixos devem ser positivos.');}else data={x:this.parseNum(document.getElementById('gpx').value),y:this.parseNum(document.getElementById('gpy').value)};if(this.editingId){this.objects.update(this.editingId,data);this.showToast('Objeto geométrico atualizado.');}else{const obj=this.objects.add(t,data,colors[this.objects.items.length%colors.length]);this.addHistory(t==='line'?'Reta':t==='circle'?'Círculo':t==='ellipse'?'Elipse':'Ponto',obj);this.showToast('Objeto geométrico adicionado.');}this.cancelEdit();}catch(e){this.showError(e);}},
    renderObjects(){const list=this.$.objectsList;list.innerHTML='';if(!this.objects.items.length){list.innerHTML='<div class="empty-list">Nenhum objeto adicionado.</div>';return;}this.objects.items.forEach((o)=>{const label=this.objectLabel(o);const row=document.createElement('div');row.className='object-row';row.innerHTML=`<span class="swatch" style="background:${o.color}" aria-hidden="true"></span><button class="object-label" type="button" title="Editar ${this.escape(label)}">${this.escape(label)}</button><button class="row-btn" data-action="toggle" type="button" aria-label="${o.visible?'Ocultar':'Mostrar'} objeto">${o.visible?ICON.hide:ICON.show}</button><button class="row-btn" data-action="delete" type="button" aria-label="Excluir objeto">Excluir</button>`;row.querySelector('[data-action="toggle"]').addEventListener('click',()=>this.objects.toggle(o.id));row.querySelector('[data-action="delete"]').addEventListener('click',()=>{this.objects.remove(o.id);this.showToast('Objeto excluído.');});row.querySelector('.object-label').addEventListener('click',()=>this.beginEdit(o));list.appendChild(row);});},
    escape(s){return String(s).replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));},
    objectLabel(o){if(o.type==='function')return`y = ${this.display(o.data.expression)}`;if(o.type==='parametric')return`x=${this.display(o.data.xExpr)}, y=${this.display(o.data.yExpr)}`;if(o.type==='vector')return`(${o.data.x1}, ${o.data.y1}) → (${o.data.x2}, ${o.data.y2})`;if(o.type==='line')return`${o.data.a}x + ${o.data.b}y + ${o.data.c} = 0`;if(o.type==='circle')return`Círculo (${o.data.cx}, ${o.data.cy}), r=${o.data.r}`;if(o.type==='ellipse')return`Elipse (${o.data.cx}, ${o.data.cy}), a=${o.data.a}, b=${o.data.b}`;return`Ponto (${o.data.x}, ${o.data.y})`;},
    display(s){return String(s).replace(/\bpi\b/g,'π').replace(/\btau\b/g,'τ').replace(/\bphi\b/g,'φ').replace(/sqrt\(/g,'√(').replace(/\^2/g,'²').replace(/\^3/g,'³').replace(/\*/g,'×').replace(/\//g,'÷').replace(/-/g,'−');},
    loadHistory(){try{this.history=JSON.parse(localStorage.getItem('graphCalcHistoryV2')||'[]');if(!Array.isArray(this.history))this.history=[];}catch{this.history=[];}this.renderHistory();},
    addHistory(text,obj=null){const entry={text,time:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),object:obj?{type:obj.type,color:obj.color,data:JSON.parse(JSON.stringify(obj.data))}:null};this.history.unshift(entry);this.history=this.history.slice(0,50);localStorage.setItem('graphCalcHistoryV2',JSON.stringify(this.history));this.renderHistory();},
    renderHistory(){this.$.historyList.innerHTML=this.history.length?this.history.map((h)=>`<button class="history-row" type="button"><span>${this.escape(h.text)}</span><small>${this.escape(h.time)}</small></button>`).join(''):'<div class="empty-list">Sem histórico.</div>';this.$.historyList.querySelectorAll('.history-row').forEach((row,i)=>row.addEventListener('click',()=>this.reuseHistory(this.history[i])));},
    reuseHistory(entry){const text=typeof entry==='string'?entry:entry?.text||'';if(entry?.object){const o=entry.object;this.cancelEdit();this.setTab(o.type==='function'?'function':o.type==='parametric'?'parametric':o.type==='vector'?'vector':'geometry');if(o.type==='function')this.$.functionExpr.value=this.display(o.data.expression);else if(o.type==='parametric'){this.$.paramX.value=this.display(o.data.xExpr);this.$.paramY.value=this.display(o.data.yExpr);this.$.tMin.value=o.data.tMin;this.$.tMax.value=o.data.tMax;}else if(o.type==='vector'){['vx1','vy1','vx2','vy2'].forEach((id,i)=>document.getElementById(id).value=[o.data.x1,o.data.y1,o.data.x2,o.data.y2][i]);}else{this.$.geometryType.value=o.type;this.initGeometryFields();this.fillGeometry({type:o.type,data:o.data});}this.updatePreviews();this.showToast('Objeto recuperado do histórico.');return;}const m=text.match(/^y = (.+)$/);if(m){this.setTab('function');this.$.functionExpr.value=m[1];this.updatePreviews();return;}const p=text.match(/^x\(t\) = (.+), y\(t\) = (.+)$/);if(p){this.setTab('parametric');this.$.paramX.value=p[1];this.$.paramY.value=p[2];this.updatePreviews();}},
    clearHistory(){this.history=[];localStorage.removeItem('graphCalcHistoryV2');this.renderHistory();this.showToast('Histórico limpo.');},
    persistSession(){this.objects.save();},
    undo(){if(this.objects.undo()){this.showToast('Ação desfeita.');}else this.showToast('Nada para desfazer.');this.updateUndoButtons();},
    redo(){if(this.objects.redo()){this.showToast('Ação refeita.');}else this.showToast('Nada para refazer.');this.updateUndoButtons();},
    updateUndoButtons(){this.$.undo.disabled=!this.objects?.undoStack?.length;this.$.redo.disabled=!this.objects?.redoStack?.length;},
    updateEmptyState(){this.$.emptyState.classList.toggle('hidden',this.objects.items.length>0);},
    updateCoordinates(p){const x=Number(p?.x),y=Number(p?.y);this.$.coordinate.textContent=Number.isFinite(x)&&Number.isFinite(y)?`x: ${this.fmt(x)} · y: ${this.fmt(y)}`:'x: — · y: —';},
    setStatus(msg,error=false){this.$.status.textContent=msg;this.$.status.className=error?'error':'';clearTimeout(this.statusTimer);this.statusTimer=setTimeout(()=>{this.$.status.textContent='Pronto';this.$.status.className='';},3000);},
    showError(error){const message=error?.message||'Não foi possível concluir a operação.';this.setStatus(message,true);this.showToast(message,true);},
    showToast(message,error=false){if(!this.$.toast)return;clearTimeout(this.toastTimer);this.$.toast.textContent=message;this.$.toast.className=`toast show${error?' error':''}`;this.toastTimer=setTimeout(()=>this.$.toast.className='toast',3200);},
    toggleFullscreen(){this.$.shell.classList.toggle('fullscreen');requestAnimationFrame(()=>requestAnimationFrame(()=>{this.engine.resize();this.engine.requestRender();}));},
    renderPreview(){/* ponto de extensão */}
  };
  global.AppUI=AppUI;
})(window);
