import {chromium} from 'playwright';
import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),report=[],errors=[];
const server=http.createServer((req,res)=>{let rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(rel.endsWith('/'))rel+='index.html';const f=path.resolve(root,'.'+rel);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json'})[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(res);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({headless:true,...(process.env.ORBISV_CHROMIUM?{executablePath:process.env.ORBISV_CHROMIUM}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'}),page=await context.newPage();page.on('pageerror',e=>{errors.push(e.message);console.log('JS: '+e.message);});page.setDefaultTimeout(10000);
async function test(name,f){try{await f();report.push({name,ok:true});}catch(e){report.push({name,ok:false,error:e.message});console.log(JSON.stringify(report.at(-1)));}}
const go=async id=>{await page.goto(url+'#laboratorio/'+id);await page.waitForFunction(()=>document.body.classList.contains('platform-editor-open'));};
let projectFile;
const close=async id=>page.locator('[data-close-modal="'+id+'"]').click();
const openScene=async()=>{await page.evaluate(()=>OrbisVRuntime.AppUI.closeAllModals());await page.locator('#projectBtn').click();await page.locator('#projectSheet').waitFor();};
try{
await go('fund-funcoes');await page.evaluate(()=>{const u=OrbisVRuntime.AppUI;u.drafts.function.expression='x^2';u.submitCurrent();});
await test('Ações da cena: três grupos e nome editável',async()=>{await openScene();assert.equal(await page.locator('#projectTitle').innerText(),'Ações da cena');assert.equal(await page.locator('#projectSheet .action-section').count(),3);assert.equal(await page.locator('#projectSheet .action-choice').count(),9);await page.locator('#projectNameInput').fill('Parábolas — investigação');assert.equal(await page.evaluate(()=>OrbisVRuntime.AppUI.currentProjectName),'Parábolas — investigação');await page.screenshot({animations:'disabled',path:path.join(root,'tests/acoes-cena-claro.png')});await close('projectSheet');});
await test('Salvar cena conserva objetos e nome no arquivo',async()=>{await openScene();const wait=page.waitForEvent('download');await page.locator('#saveProjectBtn').click();const dl=await wait;projectFile=await dl.path();const p=JSON.parse(fs.readFileSync(projectFile,'utf8'));assert.equal(p.name,'Parábolas — investigação');assert.equal(p.scene.objects.length,1);await page.evaluate(()=>OrbisVRuntime.AppUI.closeAllModals());});
await test('Nova cena pede confirmação e Cancelar conserva a construção',async()=>{await openScene();await page.locator('#newProjectBtn').click();await page.locator('#confirmDialog').waitFor();assert.equal(await page.locator('#confirmOkBtn').evaluate(e=>getComputedStyle(e).borderRadius),'4px');await page.locator('#confirmCancelBtn').click();await page.locator('#projectSheet').waitFor();assert.equal(await page.evaluate(()=>OrbisVRuntime.objects.items.length),1);await close('projectSheet');});
await test('Importar cena: prévia e mesclagem mantêm os dois objetos',async()=>{await openScene();await page.locator('#openProjectBtn').click();await page.locator('#projectFileInput').setInputFiles({name:'parabolas.orbisv',mimeType:'application/json',buffer:fs.readFileSync(projectFile)});await page.locator('#importPreview').waitFor();await page.screenshot({animations:'disabled',path:path.join(root,'tests/importacao-caderno.png')});await page.locator('input[name=importMode][value=merge]').check();await page.locator('#importApplyBtn').click();await page.waitForFunction(()=>OrbisVRuntime.objects.items.length===2);});
await test('Exportação em linhas produz PNG com o gráfico real',async()=>{await openScene();await page.locator('#openExportBtn').click();assert.equal(await page.locator('#exportSheet .export-card').count(),5);await page.screenshot({animations:'disabled',path:path.join(root,'tests/exportacao-caderno.png')});const wait=page.waitForEvent('download');await page.locator('[data-export=png]').click();const dl=await wait,b=fs.readFileSync(await dl.path());assert.equal(b.subarray(1,4).toString(),'PNG');assert.ok(b.readUInt32BE(16)>500);await page.evaluate(()=>OrbisVRuntime.AppUI.closeAllModals());});
await test('Menu do objeto mantém duplicação e exclusão com confirmação',async()=>{await page.locator('[data-inspector-tab=objects]').click();await page.locator('#objectsList [data-action=menu]').first().click();await page.locator('[data-object-action=duplicate]').click();assert.equal(await page.evaluate(()=>OrbisVRuntime.objects.items.length),3);await page.locator('#objectsList [data-action=menu]').first().click();await page.screenshot({animations:'disabled',path:path.join(root,'tests/acoes-objeto.png')});await page.locator('[data-object-action=delete]').click();await page.locator('#confirmCancelBtn').click();assert.equal(await page.evaluate(()=>OrbisVRuntime.objects.items.length),3);});
await test('Preferências de visualização continuam ligadas ao gráfico',async()=>{await page.locator('#settingsBtn').click();await page.locator('#visGridToggle').uncheck();assert.equal(await page.evaluate(()=>OrbisVRuntime.engine.showGrid),false);await page.locator('#visGridToggle').check();await page.locator('#snapSelect').selectOption('integer');assert.equal(await page.evaluate(()=>OrbisVRuntime.AppUI.viewPrefs.snap),'integer');await close('visualizationSheet');});
await test('Acessibilidade: tema, contraste e botões com superfícies comuns',async()=>{await page.locator('#a11yBtn').click();await page.locator('[data-theme-choice=dark]').click();await page.screenshot({animations:'disabled',path:path.join(root,'tests/preferencias-caderno-escuro.png')});assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.locator('#highContrastToggle').check();assert.ok(await page.locator('html').evaluate(e=>e.classList.contains('high-contrast')));await page.locator('#highContrastToggle').uncheck();await close('a11ySheet');await openScene();await page.screenshot({animations:'disabled',path:path.join(root,'tests/acoes-cena-escuro.png')});assert.equal(await page.locator('#continueProjectBtn').evaluate(e=>getComputedStyle(e).backgroundImage),'none');await close('projectSheet');await page.locator('#platformLabBar [data-platform-theme]').click();});
await test('Guia de investigação abre dentro do novo laboratório',async()=>{await page.locator('#manualBtn').click();await page.frameLocator('#manualFrame').locator('h1').waitFor();assert.equal(await page.frameLocator('#manualFrame').locator('h1').innerText(),'Caderno de investigação');await page.locator('#manualDockCloseBtn').click();});
await test('Sete modos: seleção usa o novo menu e indica o modo ativo',async()=>{await page.setViewportSize({width:390,height:844});for(const mode of ['function','parametric','vector','geometry','washers','curve3d','line3d']){await page.locator('#moreModesBtn').click();await page.locator('[data-more-mode="'+mode+'"]').click();assert.equal(await page.evaluate(()=>OrbisVRuntime.AppUI.activeMode),mode);assert.equal(await page.locator('#moreModesSheet').isVisible(),false);await page.locator('#moreModesBtn').click();assert.equal(await page.locator('[data-more-mode="'+mode+'"]').getAttribute('aria-current'),'page');await close('moreModesSheet');}await page.locator('#moreModesBtn').click();await page.screenshot({animations:'disabled',path:path.join(root,'tests/modos-caderno-mobile.png')});await close('moreModesSheet');});
await test('320px: menus e janelas sem estouro e fechamento acessível',async()=>{await page.setViewportSize({width:320,height:568});for(const id of ['projectSheet','moreModesSheet','modelsSheet','importSheet','exportSheet','a11ySheet','visualizationSheet']){await page.evaluate(id=>{const u=OrbisVRuntime.AppUI;u.closeAllModals();if(id==='modelsSheet'){u.setMode('function',false);u.openModels();}else u.openModal(id);},id);const r=await page.locator('#'+id).boundingBox();assert.ok(r.x>=0&&r.x+r.width<=320,id);assert.ok(r.y>=0&&r.y+r.height<=568,id);assert.ok(await page.locator('#'+id).evaluate(e=>e.scrollWidth<=e.clientWidth+1),id);await page.locator('#'+id).evaluate(e=>e.scrollTop=e.scrollHeight);const b=await page.locator('#'+id+' [data-close-modal]').boundingBox();assert.ok(b.y>=0&&b.y+b.height<=568,id+' fechar');await close(id);}await openScene();await page.screenshot({animations:'disabled',path:path.join(root,'tests/acoes-cena-mobile.png')});await close('projectSheet');});
await test('Teclado conserva notação e ações no mesmo padrão',async()=>{await page.evaluate(()=>{const u=OrbisVRuntime.AppUI;u.setMode('function');u.sheetState='expanded';u.applySheetState();});await page.locator('#modeForm [data-edit-path=expression]').click();await page.locator('#mathDisplay').focus();await page.keyboard.press('Control+a');await page.keyboard.type('sqrt(x+1)/2');await page.screenshot({animations:'disabled',path:path.join(root,'tests/teclado-caderno-mobile.png')});assert.equal(await page.locator('#mathSaveBtn').evaluate(e=>getComputedStyle(e).borderRadius),'4px');await page.locator('#mathSaveBtn').click();assert.equal(await page.evaluate(()=>OrbisVRuntime.AppUI.drafts.function.expression),'sqrt(x+1)/2');});
await test('Celular deitado: painel e editor continuam acessíveis',async()=>{await page.setViewportSize({width:740,height:420});await go('fund-funcoes');assert.equal(await page.evaluate(()=>OrbisVRuntime.AppUI.isMobile()),true);await page.evaluate(()=>{const u=OrbisVRuntime.AppUI;u.sheetState='mid';u.applySheetState();});await page.locator('#sheetExpandBtn').click();assert.ok(await page.locator('#inspectorPanel').evaluate(e=>e.classList.contains('sheet-expanded')));await page.locator('#modeForm [data-edit-path=expression]').click();const b=await page.locator('#mathSaveBtn').boundingBox();assert.ok(b.y>=0&&b.y+b.height<=420);await page.locator('#mathCancelBtn').click();});
await test('Sem exceções JavaScript',async()=>assert.deepEqual(errors,[]));
}finally{await browser.close();await new Promise(r=>server.close(r));}
fs.writeFileSync(path.join(root,'tests/actions-results.json'),JSON.stringify(report,null,2));const failures=report.filter(r=>!r.ok);console.log(JSON.stringify({total:report.length,passed:report.length-failures.length,failures},null,2));if(failures.length)process.exitCode=1;
