const fs=require('fs');
const html=fs.readFileSync('index.html','utf8');
const ui=fs.readFileSync('js/ui.js','utf8');
const css=fs.readFileSync('css/style.css','utf8');
const modal=html.indexOf('<div class="settings-modal hidden" id="extrasModal"');
const bodyOpen=html.indexOf('<body>');
const mainClose=html.lastIndexOf('</main>');
if(modal<0) throw new Error('Modal ausente');
if(modal<mainClose) throw new Error('Modal ainda dentro do app-shell');
if(modal<bodyOpen) throw new Error('Modal antes do body');
if(!ui.includes('document.body.appendChild(this.$.extrasModal)')) throw new Error('Modal não é portalizado para body');
if(!ui.includes("if(modal && !modal.classList.contains('hidden'))")) throw new Error('Modal não possui fluxo independente de teclado');
if(!css.includes('.settings-modal{position:fixed!important')) throw new Error('Modal sem overlay global');
console.log('extras modal global OK');
