const fs=require('fs');
const html=fs.readFileSync('index.html','utf8');
const ui=fs.readFileSync('js/ui.js','utf8');
if(!html.includes('id=\"extrasModal\"')) throw new Error('extras modal missing');
if(!html.includes('role=\"dialog\"')) throw new Error('extras dialog missing');
if(!html.includes('id=\"closeExtrasModalBtn\"')) throw new Error('extras close button missing');
if(!html.includes('id=\"exportBtn\"')||!html.includes('id=\"exportSvgBtn\"')) throw new Error('export buttons missing from extras modal');
if(!html.includes('id=\"extrasBtn\"')) throw new Error('extras button missing');
if((html.match(/id=\"exportBtn\"/g)||[]).length!==1) throw new Error('duplicate exportBtn');
if((html.match(/id=\"exportSvgBtn\"/g)||[]).length!==1) throw new Error('duplicate exportSvgBtn');
if(ui.includes('toggleControlsPanel()')) throw new Error('obsolete duplicate control toggle remains');
if((ui.match(/controlsCollapse\?\.addEventListener\('click'/g)||[]).length!==1) throw new Error('duplicate controls collapse handler');
if(ui.includes('extrasSection?.open')||ui.includes('extrasSection.open')) throw new Error('old inline extras behavior remains');
if(!ui.includes('openExtrasModal()')||!ui.includes('closeExtrasModal()')) throw new Error('modal handlers missing');
console.log('extra settings modal OK');
