import {chromium} from 'playwright';
import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),report=[],errors=[];
const server=http.createServer((req,res)=>{let rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(rel.endsWith('/'))rel+='index.html';const f=path.resolve(root,'.'+rel);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json'})[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(res);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({headless:true,...(process.env.ORBISV_CHROMIUM?{executablePath:process.env.ORBISV_CHROMIUM}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
async function test(name,f){try{await f();report.push({name,ok:true});}catch(e){report.push({name,ok:false,error:e.message});}}
const go=async id=>{await page.goto(url+'#laboratorio/'+id);await page.waitForFunction(()=>document.body.classList.contains('platform-editor-open'));};
try{
await go('fund-funcoes');
const scenes=await page.evaluate(()=>Object.values(OrbisCatalog.labs).filter(l=>!l.fields).map(l=>({id:l.id,mode:l.mode,title:l.title})));
for(const lab of scenes)await test('Cena gráfica: '+lab.id,async()=>{await go(lab.id);assert.equal(await page.locator('#sceneTitle').innerText(),lab.title);assert.equal(await page.evaluate(()=>OrbisVRuntime.AppUI.activeMode),lab.mode);await page.evaluate(()=>OrbisVRuntime.AppUI.submitCurrent());assert.ok(await page.evaluate(()=>OrbisVRuntime.AppUI.objects.items.length)>0);const box=await page.locator('#graphCanvas').boundingBox();assert.ok(box.width>600&&box.height>400);const pixel=await page.locator('#graphCanvas').evaluate(c=>[...c.getContext('2d').getImageData(1,1,1,1).data]);assert.deepEqual(pixel.slice(0,3),[255,253,248]);});
await test('Duas páginas: gráfico à esquerda e registro à direita',async()=>{await go('fund-funcoes');await page.evaluate(()=>{const u=OrbisVRuntime.AppUI;u.drafts.function.expression='x^2';u.submitCurrent();u.drafts.function.expression='x^2-3';u.submitCurrent();});await page.locator('[data-native-inquiry]').click();assert.equal(await page.locator('#nativeInquiryPanel').isVisible(),true);const a=await page.locator('#graphCanvas').boundingBox(),b=await page.locator('#nativeInquiryPanel').boundingBox();assert.ok(b.x>=a.x+a.width-1);await page.locator('#iqPrediction').fill('Mudar o termo constante deslocará a curva, mantendo a sua forma.');await page.screenshot({animations:'disabled',path:path.join(root,'tests/grafico-caderno-claro.png')});});
await test('Escuro mantém a identidade e atualiza a área gráfica',async()=>{await page.locator('#platformLabBar [data-platform-theme]').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.screenshot({animations:'disabled',path:path.join(root,'tests/grafico-caderno-escuro.png')});await page.locator('#platformLabBar [data-platform-theme]').click();});
await test('Pontos de partida têm fórmulas formatadas e pergunta de exploração',async()=>{await page.locator('[data-inspector-tab="entry"]').click();await page.locator('.models-open-btn').click();assert.equal(await page.locator('#modelsSheet').isVisible(),true);assert.ok(await page.locator('.model-formula math').count()>10);assert.ok(await page.locator('.model-question').count()>10);await page.screenshot({animations:'disabled',path:path.join(root,'tests/modelos-exploracao.png')});const before=await page.evaluate(()=>OrbisVRuntime.AppUI.objects.items.length);await page.locator('[data-model-id]').first().click();assert.equal(await page.evaluate(()=>OrbisVRuntime.AppUI.objects.items.length),before);assert.equal(await page.locator('#modelsSheet').isVisible(),false);});
await test('A preferência antiga de barra recolhida não quebra os modos',async()=>{await page.locator('#workspace').evaluate(e=>e.classList.add('rail-collapsed'));assert.equal(await page.locator('.mode-rail .mode-btn span:visible').count(),7);const a=await page.locator('#graphCanvas').boundingBox(),b=await page.locator('#inspectorPanel').boundingBox();assert.ok(b.x>=a.x+a.width-1);});
await test('Modelo espacial conserva sua câmera e formulário',async()=>{await go('calc2-curvas3d');await page.evaluate(()=>OrbisVRuntime.AppUI.submitCurrent());await page.screenshot({animations:'disabled',path:path.join(root,'tests/grafico-espacial.png')});assert.equal(await page.evaluate(()=>OrbisVRuntime.AppUI.objects.items.at(-1).type),'curve3d');});
await test('Mobile: painel ajusta ao espaço disponível e mantém o editor',async()=>{await page.setViewportSize({width:390,height:844});await go('fund-funcoes');await page.evaluate(()=>{OrbisVRuntime.AppUI.submitCurrent();OrbisVRuntime.AppUI.setInspectorTab('entry');OrbisVRuntime.AppUI.sheetState='mid';OrbisVRuntime.AppUI.applySheetState();});await page.locator('#resetViewBtn').click();await page.screenshot({animations:'disabled',path:path.join(root,'tests/grafico-mobile.png')});for(const w of [390,320]){await page.setViewportSize({width:w,height:844});assert.ok(await page.locator('#appShell').evaluate(e=>e.scrollWidth<=innerWidth+1));await page.evaluate(()=>{OrbisVRuntime.AppUI.sheetState='expanded';OrbisVRuntime.AppUI.applySheetState();});await page.waitForFunction(()=>document.getElementById('inspectorPanel').getBoundingClientRect().top>=document.querySelector('.topbar').getBoundingClientRect().bottom-1);const head=await page.locator('.topbar').boundingBox(),sheet=await page.locator('#inspectorPanel').boundingBox();assert.ok(sheet.y>=head.y+head.height-1,JSON.stringify({w,head,sheet,styles:await page.locator('#inspectorPanel').evaluate(e=>({h:getComputedStyle(e).height,parent:e.parentElement.getBoundingClientRect().toJSON()}))}));await page.locator('#modeForm [data-edit-path]').first().click();assert.equal(await page.locator('#mathEditorModal').isVisible(),true);await page.locator('#mathCancelBtn').click();}await page.locator('[data-native-inquiry]').click();assert.equal(await page.locator('#nativeInquiryPanel').isVisible(),true);});
await test('Sem exceções JavaScript',async()=>assert.deepEqual(errors,[]));
}finally{await browser.close();await new Promise(r=>server.close(r));}
fs.writeFileSync(path.join(root,'tests/graphical-results.json'),JSON.stringify(report,null,2));const failures=report.filter(r=>!r.ok);console.log(JSON.stringify({total:report.length,passed:report.length-failures.length,failures},null,2));if(failures.length)process.exitCode=1;
