const fs=require('fs');const vm=require('vm');const assert=require('assert');
const ctx={window:{},console,document:{documentElement:{classList:{contains:()=>false}},getElementById:()=>null},ResizeObserver:class{observe(){}},requestAnimationFrame:(fn)=>fn()};
ctx.window=ctx;vm.createContext(ctx);
vm.runInContext(fs.readFileSync('js/mathEngine.js','utf8'),ctx);
vm.runInContext(fs.readFileSync('js/graphObjects.js','utf8'),ctx);
const M=ctx.MathEngine; const G=ctx.GraphObjects;
assert.strictEqual(M.evalExpr('x+y+z',{x:1,y:2,z:3}),6);
assert.ok(Number.isFinite(M.evalExpr('x^2+y^2',{x:2,y:3})));
const g=new G();
const s=g.addSurface('x^2+y^2','#5ac8fa'); s.data.range=5;
const c=g.addCurve3D('cos(t)','sin(t)','t',0,2*Math.PI,'#b28cff');
const l=g.addLine3D([0,0,0],[1,2,3],'#ff6fae');
assert.strictEqual(s.data.expression,'x^2+y^2'); assert.strictEqual(s.data.range,5);
assert.strictEqual(c.type,'curve3d'); assert.strictEqual(c.data.zExpr,'t');
assert.deepStrictEqual(Array.from(l.data.p2),[1,2,3]);
console.log('graph3d OK');
