const fs=require('fs');const path=require('path');const vm=require('vm');
const root=path.resolve(__dirname,'..');
const storage=new Map();
const localStorage={setItem:(k,v)=>storage.set(k,v),getItem:(k)=>storage.get(k)||null,removeItem:(k)=>storage.delete(k)};
const context={window:{localStorage},localStorage,JSON,Math,Number,String,Object,Array,Date};
vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'js/graphObjects.js'),'utf8'),context);const GraphObjects=context.window.GraphObjects;
const g=new GraphObjects();
g.add('point',{x:1,y:2},'#fff');g.add('vector',{x1:0,y1:0,x2:3,y2:4},'#000');
if(g.items.length!==2)throw new Error('add');
g.toggle(1);if(g.items[0].visible!==false)throw new Error('toggle');
g.update(1,{x:5,y:6});if(g.items[0].data.x!==5)throw new Error('update');
g.remove(2);if(g.items.length!==1)throw new Error('remove');
g.undo();if(g.items.length!==2)throw new Error('undo remove');
g.redo();if(g.items.length!==1)throw new Error('redo remove');
g.save();const g2=new GraphObjects();g2.load();if(g2.items.length!==1||g2.items[0].data.x!==5)throw new Error('persistence');
console.log('graphObjects OK');
