import {chromium} from 'playwright';
import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),report=[],errors=[];
const server=http.createServer((req,res)=>{let rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(rel.endsWith('/'))rel+='index.html';const f=path.resolve(root,'.'+rel);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json'})[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(res);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({headless:true,...(process.env.ORBISV_CHROMIUM?{executablePath:process.env.ORBISV_CHROMIUM}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:1440,height:1060},serviceWorkers:'block'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
async function test(name,f){try{await f();report.push({name,ok:true});}catch(e){report.push({name,ok:false,error:e.message});}}
const go=async h=>{await page.goto(url+h);await page.waitForFunction(()=>window.OrbisPlatform&&window.OrbisInquiry);};
const calc=async()=>{await page.locator('#wbCalculate').click();await page.locator('#wbRecord').waitFor({timeout:15000});};
const edit=async(id,v)=>{await page.locator('#wb-'+id+'-edit').click();await page.locator('#mathDisplay').focus();await page.keyboard.press('Control+a');await page.keyboard.type(v);await page.locator('#mathSaveBtn').click();};
try{
await test('Abertura em papel, cinco áreas e navegação',async()=>{await go('');assert.equal(await page.locator('html').getAttribute('data-theme'),'light');assert.equal(await page.locator('.book-area').count(),5);await page.screenshot({animations:'disabled',path:path.join(root,'tests/abertura-clara.png')});});
await test('Currículo: ano, código e extensão sem enquadramento falso',async()=>{await go('#curriculo');await page.locator('#curriculumStage').selectOption('EF05');await page.locator('#curriculumSearch').fill('EF05MA04');assert.equal(await page.locator('.curriculum-card:visible').count(),1);assert.match(await page.locator('.curriculum-card:visible').innerText(),/Frações exatas/);await page.locator('#curriculumSearch').fill('');await page.locator('#curriculumStage').selectOption('EXT');assert.ok(await page.locator('.curriculum-card:visible').count()>40);await page.locator('#curriculumSearch').fill('Taylor');assert.equal(await page.locator('.curriculum-card:visible').count(),1);assert.match(await page.locator('.curriculum-card:visible').innerText(),/Sem código BNCC/);});
await test('Professor: roteiro editável e exportação',async()=>{await go('#professor');await page.locator('#teacherLab').selectOption('fund-malha');await page.locator('#teacher-question').fill('Como cercar duas hortas com área igual e contornos diferentes?');await page.locator('#teacher-audience').fill('4º ano · turma A');await page.locator('#teacherForm button[type=submit]').click();assert.match(await page.locator('#teacherStatus').innerText(),/salvo/);const waiting=page.waitForEvent('download');await page.locator('#teacherExport').click();const dl=await waiting,raw=JSON.parse(fs.readFileSync(await dl.path(),'utf8'));assert.equal(raw.plan.labId,'fund-malha');assert.equal(raw.plan.audience,'4º ano · turma A');});
await test('Importação inválida de roteiro preserva a versão local',async()=>{const before=await page.evaluate(()=>OrbisInquiry.data().plans['fund-malha']);await page.locator('#teacherImport').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"format":"orbisv-teacher-plan","version":1,"plan":{"labId":"inexistente"}}')});await page.locator('#teacherStatus.error').waitFor();assert.deepEqual(await page.evaluate(()=>OrbisInquiry.data().plans['fund-malha']),before);});
await test('Roteiro acompanha laboratório e previsão sobrevive ao reload',async()=>{await page.locator('#teacherOpen').click();await page.locator('#iqPrediction').waitFor();assert.match(await page.locator('.iq-question').innerText(),/hortas/);await page.locator('#iqPrediction').fill('A área pode ser igual, mas o perímetro pode mudar.');await page.reload();await page.locator('#iqPrediction').waitFor();assert.match(await page.locator('#iqPrediction').inputValue(),/perímetro/);});
await test('Dois ensaios capturados com o teclado matemático original',async()=>{await page.locator('[data-iq-stage="1"]').click();assert.ok(await page.locator('#iqCapture').isDisabled());await calc();await page.locator('#iqCapture').click();assert.equal(await page.locator('.iq-trial').count(),1);await page.locator('#iqCapture').click();assert.match(await page.locator('#iqStatus').innerText(),/iguais/);await edit('a','8');await edit('b','3');assert.ok(await page.locator('#iqCapture').isDisabled());await calc();await page.locator('#iqCapture').click();assert.equal(await page.locator('.iq-trial').count(),2);});
await test('Comparação numérica e produção de conclusão',async()=>{await page.locator('[data-iq-stage="2"]').click();assert.match(await page.locator('.iq-table').innerText(),/20/);assert.match(await page.locator('.iq-table').innerText(),/22/);await page.locator('#iqComparison').fill('Os dois ensaios têm 24 u²; os perímetros são 20 u e 22 u.');await page.locator('[data-iq-stage="3"]').click();await page.locator('#iqConclusion').fill('A igualdade das áreas não implica igualdade dos perímetros.');await page.locator('#iqExtension').fill('Comparar 1 × 9 e 4 × 6: mesmo perímetro, áreas distintas.');await page.locator('#iqAssessment').selectOption({label:'Consigo justificar e apontar limites'});await page.screenshot({animations:'disabled',path:path.join(root,'tests/investigacao-clara.png')});await page.locator('#iqRecord').click();await page.locator('#platformNoteText').waitFor();assert.match(await page.locator('#platformNoteText').inputValue(),/20 u e 22 u/);assert.equal(await page.evaluate(()=>OrbisPlatform.data().notes[0].inquiry.trials.length),2);});
await test('Devolutiva docente persistente e backup com evidências',async()=>{await page.locator('#noteTeacherFeedback').fill('Agora justifique a diferença usando os comprimentos dos lados.');await page.locator('[data-note-save]').click();await page.reload();await page.locator('#noteTeacherFeedback').waitFor();assert.match(await page.locator('#noteTeacherFeedback').inputValue(),/comprimentos/);const waiting=page.waitForEvent('download');await page.locator('[data-note-export]').click();const dl=await waiting,file=await dl.path(),raw=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(raw.notes[0].inquiry.trials.length,2);assert.equal(raw.notes[0].inquiry.plan.audience,'4º ano · turma A');const count=raw.notes.length;await page.locator('#platformNotebookImport').setInputFiles(file);await page.waitForFunction(()=>document.getElementById('platformStatus').textContent.includes('adicionada'));assert.equal(await page.evaluate(()=>OrbisPlatform.data().notes.length),count);await page.screenshot({animations:'disabled',path:path.join(root,'tests/caderno-registros.png')});});
await test('Restauração retoma valores e processo da investigação',async()=>{await page.locator('[data-note-investigation]').click();await page.locator('#wb-a').waitFor({state:'attached'});assert.equal(await page.locator('#wb-a').inputValue(),'8');assert.equal(await page.evaluate(()=>OrbisInquiry.data().drafts['fund-malha'].trials.length),2);await go('#inicio');assert.match(await page.locator('.book-resume').innerText(),/Retomar investigação/);assert.match(await page.locator('.book-resume').innerText(),/Área e perímetro/);});
await test('Compatibilidade com anotações antigas e texto sem execução',async()=>{await go('#caderno');await page.locator('#platformNotebookImport').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'orbisv-platform',version:1,notes:[{id:'legacy-note',title:'Legado',text:'<img src=x onerror=alert(1)>',labId:'',snapshot:null}]}))});await page.waitForFunction(()=>document.getElementById('platformStatus').textContent.includes('adicionada'));assert.equal(await page.locator('#platformNoteTitle').inputValue(),'Legado');assert.equal(await page.locator('.platform-note-editor img').count(),0);});
await test('Caderno livre exporta e reimporta sem duplicação',async()=>{await page.locator('[data-note-new]').click();await page.locator('#platformNoteTitle').fill('Nota livre');await page.locator('[data-note-save]').click();const n=await page.evaluate(()=>OrbisPlatform.data().notes.length),wait=page.waitForEvent('download');await page.locator('[data-note-export]').click();const dl=await wait;await page.locator('#platformNotebookImport').setInputFiles(await dl.path());await page.waitForFunction(()=>document.getElementById('platformStatus').textContent.includes('adicionada'));assert.equal(await page.evaluate(()=>OrbisPlatform.data().notes.length),n);});
await test('Editor gráfico também registra uma investigação com cena',async()=>{await go('#laboratorio/fund-funcoes');await page.evaluate(()=>{const u=OrbisVRuntime.AppUI;u.drafts.function.expression='x^2';u.submitCurrent();});await page.locator('[data-native-inquiry]').click();await page.locator('#nativeInquiryPanel [data-iq-stage="1"]').click();await page.locator('#iqCapture').click();await page.locator('#nativeInquiryPanel [data-iq-stage="3"]').click();await page.locator('#iqConclusion').fill('O gráfico apresenta simetria em relação ao eixo y.');await page.locator('#iqRecord').click();await page.locator('#platformNoteText').waitFor();assert.equal(await page.evaluate(()=>OrbisPlatform.data().notes[0].snapshot.kind),'scene');});
await test('Claro e escuro: rótulos e superfícies atualizados',async()=>{await go('#inicio');await page.locator('#platformHub [data-platform-theme]').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.screenshot({animations:'disabled',path:path.join(root,'tests/abertura-escura.png')});await page.locator('#platformHub [data-platform-theme]').click();});
await test('320px: índice, currículo, laboratório, Caderno e professor sem estouro',async()=>{await page.setViewportSize({width:320,height:900});for(const route of ['#inicio','#curriculo','#laboratorio/fund-malha','#caderno','#professor']){await go(route);if(route.includes('laboratorio'))await calc();assert.ok(await page.locator('#platformHub').evaluate(e=>e.scrollWidth<=e.clientWidth+2),route);}await go('#laboratorio/fund-malha');await calc();await page.screenshot({animations:'disabled',path:path.join(root,'tests/investigacao-mobile.png')});const svg=page.locator('#wbPlot svg');assert.ok(Number((await svg.getAttribute('viewBox')).split(' ')[2])<=300);});
await test('Roteiro importado válido abre com textos personalizados',async()=>{await go('#professor');const p=await page.evaluate(()=>OrbisInquiryCatalog.get('fund-chances'));p.question='Nossa frequência se aproxima da chance com mais sorteios?';await page.locator('#teacherImport').setInputFiles({name:'roteiro.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'orbisv-teacher-plan',version:1,plan:p}))});await page.waitForFunction(()=>document.getElementById('teacherStatus').textContent.includes('importado'));await page.locator('#teacherOpen').click();await page.locator('.iq-question').waitFor();assert.match(await page.locator('.iq-question').innerText(),/Nossa frequência/);});
await test('Sem exceções JavaScript',async()=>assert.deepEqual(errors,[]));
}finally{await browser.close();await new Promise(r=>server.close(r));}
const failures=report.filter(r=>!r.ok);fs.writeFileSync(path.join(root,'tests/inquiry-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({total:report.length,passed:report.length-failures.length,failures},null,2));if(failures.length)process.exitCode=1;
