const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const ui=fs.readFileSync(path.join(root,'js','ui.js'),'utf8');
const engine=fs.readFileSync(path.join(root,'js','mathEngine.js'),'utf8');
const css=fs.readFileSync(path.join(root,'css','style.css'),'utf8');
for(const text of ['√','x²','x³','π','÷','sen','cos','tan','arcsen','arccos','arctg','|x|','eˣ']) if(!html.includes(text) && !ui.includes(text)) throw new Error(`symbol missing: ${text}`);
if(html.includes('>sin<') || html.includes('>asin<') || html.includes('>acos<') || html.includes('>atan<')) throw new Error('raw trigonometric programming labels remain visible in HTML');
if(ui.includes("['sin','sin(']") || ui.includes("['sin⁻¹','asin(']") || ui.includes("['cos⁻¹','acos(']") || ui.includes("['tan⁻¹','atan(']")) throw new Error('old trigonometric labels remain in symbol menu');
if(!ui.includes("['sen','sen(']") || !ui.includes("['arcsen','arcsen(']") || !ui.includes("['arccos','arccos(']") || !ui.includes("['arctg','arctg(']")) throw new Error('localized trigonometric labels missing');
if(!ui.includes('\\operatorname{sen}') || !ui.includes('\\operatorname{arcsen}') || !ui.includes('\\operatorname{arccos}') || !ui.includes('\\operatorname{arctg}')) throw new Error('localized KaTeX operators missing');
if(!engine.includes(".replace(/\\bsen\\b/gi, 'sin')") || !engine.includes(".replace(/\\barcsen\\b/gi, 'asin')") || !engine.includes(".replace(/\\barccos\\b/gi, 'acos')") || !engine.includes(".replace(/\\barctg\\b/gi, 'atan')")) throw new Error('MathEngine aliases missing');
if(!html.includes('value="sen(x)"') || !html.includes('value="sen(t)"')) throw new Error('Portuguese trigonometric defaults missing');
if(!css.includes('Cambria Math')) throw new Error('math font stack missing');
console.log('math notation UI OK');
