const fs = require('fs');
const path = require('path');
const html = fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const ui = fs.readFileSync(path.join(__dirname,'..','js','ui.js'),'utf8');
const css = fs.readFileSync(path.join(__dirname,'..','css','style.css'),'utf8');
if ((html.match(/id="globalMathBtn"/g)||[]).length !== 1) throw new Error('globalMathBtn must appear once');
if ((html.match(/id="globalMathMenu"/g)||[]).length !== 1) throw new Error('globalMathMenu must appear once');
if (!ui.includes('toggleGlobalMenu')) throw new Error('explicit global menu toggle missing');
if (!ui.includes('closeGlobalMenu();')) throw new Error('explicit close missing');
if (!ui.includes('globalBtn.classList.toggle(\'is-active\', open)')) throw new Error('active state missing');
if (!css.includes('#globalMathMenu.hidden { display:none !important; }')) throw new Error('hidden state rule missing');
console.log('math menu explicit toggle OK');
