const fs=require('fs');
const html=fs.readFileSync('index.html','utf8');
const ui=fs.readFileSync('js/ui.js','utf8');
const css=fs.readFileSync('css/style.css','utf8');
if(!html.includes('id=\"globalMathMenu\"')) throw new Error('Global math menu missing');
if(!ui.includes('menus.forEach((m) => {')) throw new Error('Math menu consolidation missing');
if(!ui.includes("m.classList.add('hidden')")) throw new Error('Local menus not hidden');
if(!ui.includes('floating-math-menu')) throw new Error('Floating math menu missing');
if(!css.includes('.select-input {')) throw new Error('Select styling missing');
if(!css.includes('appearance:none')) throw new Error('Native select appearance not suppressed');
console.log('math menu/select style OK');
