const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root,'index.html'),'utf8');
const css = fs.readFileSync(path.join(root,'css','style.css'),'utf8');
const ui = fs.readFileSync(path.join(root,'js','ui.js'),'utf8');
const sw = fs.readFileSync(path.join(root,'sw.js'),'utf8');
if (!html.includes('viewport-fit=cover')) throw new Error('viewport-fit missing');
if (!html.includes('id="mobileMenuBtn"')) throw new Error('mobile FAB missing');
if (!html.includes('id="backdrop"')) throw new Error('backdrop missing');
if (!css.includes('@media (max-width:899px)')) throw new Error('mobile media query missing');
if (!css.includes('height:var(--mobile-sheet-height)')) throw new Error('mobile bottom sheet height missing');
if (!css.includes('.controls-panel.open')) throw new Error('bottom sheet open state missing');
if (!css.includes('.fab{')) throw new Error('FAB style missing');
if (!css.includes('.tabs{display:flex;overflow-x:auto')) throw new Error('horizontal mobile tabs missing');
if (!css.includes('min-height:44px;font-size:16px')) throw new Error('touch input sizing missing');
for (const token of ['openSidebar(','closeSidebar(','toggleSidebar(']) if (!ui.includes(token)) throw new Error(`${token} missing`);
if (!ui.includes("global.addEventListener('orientationchange'")) throw new Error('orientation handler missing');
if (!ui.includes('requestAnimationFrame(()=>requestAnimationFrame(()')) throw new Error('double RAF missing');
if (!sw.includes('calc-grafica-v30')) throw new Error('service worker cache not bumped');
console.log('mobile_responsive OK');
