const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'css/style.css'), 'utf8');
const ui = fs.readFileSync(path.join(root, 'js/ui.js'), 'utf8');
const sw = fs.readFileSync(path.join(root, 'sw.js'), 'utf8');
if (!html.includes('viewport-fit=cover')) throw new Error('viewport-fit missing');
if (!html.includes('id="showControlsBtn"')) throw new Error('show controls button missing');
if (!css.includes('.workspace {\n  display: flex;\n  flex-direction: column;')) throw new Error('mobile-first workspace missing');
if (!css.includes('grid-template-columns: minmax(320px, 380px) 1fr')) throw new Error('desktop grid missing');
if (!css.includes('grid-template-rows: minmax(60dvh, 1fr) auto')) throw new Error('mobile graph sizing missing');
if (!css.includes('.tabs {\n  display: flex;') && !css.includes('.tabs {display:flex')) throw new Error('horizontal mobile tabs missing');
if (!css.includes('min-height: 44px; font-size: 16px')) throw new Error('touch input sizing missing');
if (!ui.includes('initMobileLayout()')) throw new Error('mobile init missing');
if (!ui.includes("global.addEventListener('orientationchange'")) throw new Error('orientation handler missing');
if (!ui.includes("requestAnimationFrame(()=>requestAnimationFrame(()")) throw new Error('double RAF missing');
if (!sw.includes("calc-grafica-v27")) throw new Error('service worker cache not bumped');
console.log('mobile_responsive OK');
