'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..');
const storage=new Map();const localStorage={setItem:(k,v)=>storage.set(k,v),getItem:(k)=>storage.get(k)||null,removeItem:(k)=>storage.delete(k)};
const context={window:{localStorage},localStorage,JSON,Math,Number,String,Object,Array,Date};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'js/graphObjects.js'),'utf8'),context);
const G=context.window.GraphObjects,g=new G();const a=g.add('function',{expression:'x'},'#0ff'),b=g.add('function',{expression:'x^2'},'#f0f');
if(!g.duplicate(a.id)||g.items.length!==3)throw new Error('duplicate failed');
const before=g.getById(a.id).visible; if(!g.toggle(a.id)||g.getById(a.id).visible===before)throw new Error('visibility failed');
if(!g.setLocked(a.id,true)||!g.getById(a.id).locked)throw new Error('lock failed');if(!g.setLocked(a.id,false)||g.getById(a.id).locked)throw new Error('unlock failed');
const i=g.items.findIndex(o=>o.id===a.id);if(i<g.items.length-1&&!g.reorder(a.id,'up'))throw new Error('move up failed');
if(!g.remove(b.id))throw new Error('delete failed');
const ui=fs.readFileSync(path.join(root,'js/ui.js'),'utf8');for(const action of ["action==='edit'","action==='duplicate'","action==='visibility'","action==='lock'","action==='up'||action==='down'","action==='notables'","action==='delete'"])if(!ui.includes(action))throw new Error(`menu handler missing ${action}`);
console.log('object menu actions OK');
