const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const engine=fs.readFileSync(path.join(root,'js/graphEngine.js'),'utf8');
const ui=fs.readFileSync(path.join(root,'js/ui.js'),'utf8');
const main=fs.readFileSync(path.join(root,'js/main.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'css/style.css'),'utf8');
if((engine.match(/const lightTheme = document\.documentElement\.classList\.contains\('theme-light'\);/g)||[]).length<2) throw new Error('lightTheme guard missing from drawGrid/drawAxes');
if(!ui.includes('el.setValue(latex)')) throw new Error('MathLive setValue missing');
if(!ui.includes("el.getValue('ascii-math')")) throw new Error('MathLive getValue ascii-math missing');
if(!ui.includes("input.executeCommand(['insert',latex])") && !ui.includes("input.executeCommand(['insert', latex])")) throw new Error('MathLive executeCommand insert missing');
if(!ui.includes('global.mathlive || global.MathLive')) throw new Error('MathLive dual global reference missing');
if(!main.includes('window.mathlive || window.MathLive')) throw new Error('main MathLive global fallback missing');
if(!html.includes('id="paramError"')) throw new Error('paramError missing');
if(!html.includes('mathlive@0.110.0')) throw new Error('MathLive script missing');
if(!css.includes('.action-btn{')) throw new Error('action button styling missing');
if(!html.includes('id="mobileControlsToggle"')) throw new Error('mobile toggle missing');
console.log('regressions OK');
