'use strict';
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict'),root=path.resolve(__dirname,'..'),ctx={};ctx.window=ctx;vm.createContext(ctx);
for(const file of ['mathEngine','vendor/nerdamer-1.1.13.min',...['kernel','fundamentals','geometry','vectors','calculus1','calculus2','multivariable','school','math-fields','representations'].map(x=>'labs/'+x)])vm.runInContext(fs.readFileSync(path.join(root,'js',file+'.js'),'utf8'),ctx);
const K=ctx.LabKit,MF=ctx.OrbisMathFields,R=ctx.OrbisRepresentations,report=[];function test(name,fn){try{fn();report.push({name,ok:true});}catch(e){report.push({name,ok:false,error:e.message});}}
function run(id,overrides={}){const m=K.modules.find(m=>m.id===id),p=Object.fromEntries(m.fields.map(f=>[f.key,overrides[f.key]??f.value])),r=R.prepare(id,p,K.run(id,p));return {p,r};}
for(const m of K.modules){test('Representação: '+m.id,()=>{const {p,r}=run(m.id);assert.ok(r.plot||r.diagram,'Sem representação');if(r.plot){assert.ok(r.plot.series.length<=120);assert.ok(r.plot.series.reduce((s,x)=>s+x.points.length,0)<=15000);for(const s of r.plot.series)for(const point of s.points)assert.ok(point.every(v=>v===null||Number.isFinite(v)));}if(r.diagram)assert.ok(R.render(m.id,p,r).length>100);});}
test('278 campos com esquema, prévia e validação de exemplos',()=>{let count=0;for(const m of K.modules)for(const f of m.fields){if(f.type==='select')continue;count++;const s=MF.schema(m,f);MF.validate(f.value,s);assert.match(MF.format(f.value,s),/<math/);}assert.equal(count,278);});
test('Frações de 40 dígitos permanecem exatas',()=>{const s={kind:'fraction'},v='1234567890123456789012345678901234567890/7';assert.equal(MF.normalize(v,s),v);assert.ok(MF.format(v,s).includes('1234567890123456789012345678901234567890'));});
test('Variáveis específicas de cada campo são respeitadas',()=>{MF.validate('u^2',{kind:'expression',vars:['u']});assert.throws(()=>MF.validate('x^2',{kind:'expression',vars:['u']}));assert.throws(()=>MF.validate('x',{kind:'number'}));});
test('Matrizes e vetores rejeitam dimensões inválidas',()=>{assert.throws(()=>MF.validate('1;2\n3',{kind:'matrix',min:1,max:8,minCols:1,maxCols:8}));assert.throws(()=>MF.validate('1;2;3;4',{kind:'vector',min:2,max:3}));});
test('Representação de proporção direta usa correspondência correta',()=>{const {r}=run('fund-proporcoes');const p=r.plot.series[1].points[0];assert.equal(p[0],50);assert.equal(p[1],75);});
test('Conversão gráfica: 0 °C corresponde a 32 °F',()=>{const {r}=run('fund-unidades',{x:'0',from:'c',to:'f'});assert.equal(r.plot.series[1].points[0][1],32);});
for(const shape of ['rectangle','circle','trapezoid','polygon'])test('Figura plana: '+shape,()=>{const {r}=run('fund-medidas-planas',{shape});assert.ok(r.plot.series[0].points.length>=5);});
for(const shape of ['sphere','cylinder','cone','box','pyramid'])test('Sólido: '+shape,()=>{const {r}=run('fund-solidos',{shape});assert.equal(r.plot.dimensions,3);assert.ok(r.plot.series.every(s=>s.points.every(p=>p.length===3)));});
test('Cônica imaginária tem contorno vazio',()=>{const {r}=run('geo-conica-geral',{coef:'1;0;1;0;0;1'});assert.equal(r.plot.series[0].points.length,0);});
test('Famílias impróprias: integral truncada converge ou cresce conforme p',()=>{const {r}=run('calc2-improprias',{mode:'p-tail',p:'2'});assert.ok(Math.abs(r.plot.series[0].points.at(-1)[1]-.9999)<1e-8);const divergent=run('calc2-improprias',{mode:'p-edge',p:'2'}).r;assert.ok(divergent.plot.series[0].points.at(-1)[1]>9998);});
test('Primitivas variam por constante aditiva',()=>{const {r}=run('calc2-primitivas',{f:'x'}),p=r.plot.series;assert.ok(Math.abs(p[2].points[10][1]-p[0].points[10][1]-4)<1e-8);});
test('Região tripla respeita limites de tetraedro',()=>{const {r}=run('calc2-triplas');for(const s of r.plot.series)for(const [x,y,z] of s.points)assert.ok(x>=-1e-9&&y>=-1e-9&&z>=-1e-9&&x+y+z<=1+1e-9);});
test('Malha polar transformada permanece no quarto de disco',()=>{const {r}=run('calc2-jacobiano');for(const s of r.plot.series)for(const [x,y] of s.points)assert.ok(x>=-1e-9&&y>=-1e-9&&Math.hypot(x,y)<=2+1e-9);});
test('Textos de conjuntos são escapados na representação',()=>{const {p,r}=run('fund-conjuntos',{a:'<img src=x onerror=alert(1)>;A',b:'A'});const html=R.render('fund-conjuntos',p,r);assert.ok(!html.includes('<img'));assert.ok(html.includes('&lt;img'));});
fs.writeFileSync(path.join(__dirname,'representations-results.json'),JSON.stringify(report,null,2));const failed=report.filter(x=>!x.ok);console.log(JSON.stringify({total:report.length,passed:report.length-failed.length,failures:failed},null,2));if(failed.length)process.exitCode=1;
