const fs=require('fs');
const html=fs.readFileSync('index.html','utf8');
const ui=fs.readFileSync('js/ui.js','utf8');
const css=fs.readFileSync('css/style.css','utf8');
if(!html.includes('id=\"controlsCollapseBtn\"')) throw new Error('controls arrow missing');
if((html.match(/controls-arrow-left/g)||[]).length<1 || (html.match(/controls-arrow-right/g)||[]).length<1) throw new Error('both controls arrows missing');
if(!ui.includes("left?.classList.toggle('hidden', !collapsed)")) throw new Error('collapsed arrow direction not wired');
if(!ui.includes("right?.classList.toggle('hidden', collapsed)")) throw new Error('open arrow direction not wired');
if(!html.includes('id=\"extrasModal\"') || !html.includes('aria-modal=\"true\"')) throw new Error('central settings modal missing');
if(!css.includes('.settings-modal') || !css.includes('place-items:center')) throw new Error('central modal styling missing');
if (!fs.readFileSync('sw.js','utf8').includes("calc-grafica-v49")) throw new Error('PWA cache version not bumped');
console.log('right controls/modal OK');
