const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root,'index.html'),'utf8');
const css = fs.readFileSync(path.join(root,'css/style.css'),'utf8');
const ui = fs.readFileSync(path.join(root,'js/ui.js'),'utf8');
const sw = fs.readFileSync(path.join(root,'sw.js'),'utf8');
for (const id of ['sidebarToggle','backdrop','mobileMenuBtn','closeControlsBtn']) if (!html.includes(`id=\"${id}\"`)) throw new Error(`${id} missing`);
for (const cls of ['.controls-panel.open','.backdrop.show','.fab','.workspace.sidebar-collapsed']) if (!css.includes(cls)) throw new Error(`${cls} missing`);
for (const method of ['openSidebar','closeSidebar','toggleSidebar']) if (!ui.includes(`${method}(`)) throw new Error(`${method} missing`);
if (!ui.includes('requestAnimationFrame(() => requestAnimationFrame(() => { this.engine.resize(); this.engine.requestRender(); }))')) throw new Error('double RAF resize missing');
if (!/CACHE_NAME\s*=\s*['\"]calc-grafica-v\d+['\"]/.test(sw)) throw new Error('SW version not bumped');
console.log('sidebar drawer OK');
