const fs=require('fs');
const html=fs.readFileSync('index.html','utf8');
const ui=fs.readFileSync('js/ui.js','utf8');
const css=fs.readFileSync('css/style.css','utf8');
for (const id of ['backdrop','mobileMenuBtn','closeControlsBtn','saveSessionBtn']) if(!html.includes(`id="${id}"`)) throw new Error(`${id} missing`);
if(html.includes('id="sidebarToggle"')) throw new Error('desktop topbar mode button must be removed');
if(!css.includes('.workspace.sidebar-collapsed{grid-template-columns:56px')) throw new Error('desktop icon rail missing');
if(!css.includes('.controls-panel.open{transform:translateY(0)}')) throw new Error('mobile sheet missing');
if(!ui.includes('focusFirstSidebarControl')) throw new Error('focus management missing');
if(!ui.includes("event.key!=='Escape'")) throw new Error('escape close missing');
console.log('sidebar hybrid OK');
