const fs=require('fs');const vm=require('vm');const assert=require('assert');
const ctx={window:{},console,Math,Number,String,RegExp,Error,Object};ctx.window=ctx;vm.createContext(ctx);
vm.runInContext(fs.readFileSync('js/mathEngine.js','utf8'),ctx);
const M=ctx.MathEngine;
assert.deepStrictEqual(Array.from(M.defaultVariables),['x','y','z','t']);
assert.strictEqual(M.evalExpr('x+y+z',{x:1,y:2,z:3}),6);
assert.strictEqual(M.evalExpr('x+y',{x:7}),7);
assert.strictEqual(M.evalExpr('z',{z:4}),4);
assert.strictEqual(M.evalExpr('t',{t:2}),2);
console.log('variables OK');
