/* Atualiza as tabelas de documentação a partir do catálogo usado no aplicativo. */
const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..'),ctx={console};ctx.window=ctx;vm.createContext(ctx);
for(const f of ['mathEngine','catalog',...['kernel','fundamentals','geometry','vectors','calculus1','calculus2','multivariable','school','extend-catalog'].map(x=>'labs/'+x),'curriculum','inquiry-catalog'])vm.runInContext(fs.readFileSync(path.join(root,'js',f+'.js'),'utf8'),ctx,{filename:f});
const csv=x=>'"'+String(x??'').replaceAll('"','""')+'"',md=x=>String(x??'').replaceAll('|','\\|').replaceAll('\n',' ');
const rows=[['ID','Área','Grupo','Laboratório','Etapas','Unidade/tema','Códigos BNCC','Relação','Recorte e limites','Pergunta de investigação','Fonte oficial','Página impressa de referência']];
let doc='# Catálogo completo — OrbisV 9.1.0\n\n101 laboratórios: 89 bancadas e 12 ambientes gráficos livres. As perguntas são pontos de partida editáveis pelo professor. Não há sequência obrigatória nem níveis de acesso.\n\n';
const counts=[];
for(const a of ctx.OrbisCatalog.areas){const kinds=a.labs.filter(l=>l.kind==='scene').length;counts.push({area:a.title,total:a.labs.length,scenes:kinds,benches:a.labs.length-kinds});doc+='## '+a.title+'\n\n'+a.description+'\n\n';for(const group of [...new Set(a.labs.map(l=>l.group))]){doc+='### '+group+'\n\n| Laboratório | Exploração disponível | Pergunta de investigação |\n|---|---|---|\n';for(const l of a.labs.filter(l=>l.group===group))doc+='| '+[l.title+' (`'+l.id+'`)',l.summary,ctx.OrbisInquiryCatalog.get(l.id).question].map(md).join(' | ')+' |\n';doc+='\n';}for(const l of a.labs){const c=ctx.OrbisCurriculum.info(l.id);rows.push([l.id,a.title,l.group,l.title,ctx.OrbisCurriculum.stages(l.id).join(', '),c.unit,c.codes.join(', '),c.relation,c.scope,ctx.OrbisInquiryCatalog.get(l.id).question,ctx.OrbisCurriculum.source,c.page??'']);}}
fs.writeFileSync(path.join(root,'docs/CATALOGO_COMPLETO.md'),doc);fs.writeFileSync(path.join(root,'docs/MAPEAMENTO_BNCC.csv'),'\uFEFF'+rows.map(r=>r.map(csv).join(';')).join('\r\n')+'\r\n');
console.log(JSON.stringify({counts,mapped:ctx.OrbisCurriculum.all().filter(c=>c.codes.length).length,extension:ctx.OrbisCurriculum.all().filter(c=>!c.codes.length).length,uniqueCodes:new Set(ctx.OrbisCurriculum.all().flatMap(c=>c.codes)).size},null,2));
