#!/usr/bin/env python3
"""Rebuild the self-contained Blob Worker; no network or build dependencies."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
files=['mathEngine.js','vendor/nerdamer-1.1.13.min.js']+['labs/'+x+'.js' for x in ['kernel','fundamentals','geometry','vectors','calculus1','calculus2','multivariable','school','representations']]
code='self.window=self;\n'+ '\n;\n'.join((root/'js'/p).read_text() for p in files)
code+='\nself.onmessage=function(e){try{const result=LabKit.run(e.data.id,e.data.values);try{OrbisRepresentations.prepare(e.data.id,e.data.values,result);}catch(visualError){result.visualNote="Não foi possível desenhar esta expressão: "+visualError.message;}self.postMessage({ok:true,result});}catch(error){self.postMessage({ok:false,error:error.message||"Não foi possível calcular."});}};'
(root/'js/labs/worker-source.js').write_text('/* Generated by scripts/build-worker.py. */\nwindow.OrbisWorkerSource='+json.dumps(code,ensure_ascii=True)+';\n')
print('Worker generated:',len(code),'characters')
