(function(g){'use strict';
const K=g.LabKit,M=g.MathEngine,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const expressionFields={
 'fund-expressoes':{e:[]},'fund-algebra':{e:['x']},'fund-equacoes':{e:['x']},'fund-composicao':{f:['x'],g:['x']},
 'calc1-aproximacoes':{f:['x']},'calc1-epsilon-delta':{f:['x']},'calc1-derivacao':{f:['x']},'calc1-tangentes':{f:['x']},'calc1-implicitas':{f:['x','y']},'calc1-taxas':{f:['x','y']},'calc1-analise':{f:['x']},'calc1-otimizacao':{f:['x']},'calc1-newton':{f:['x']},'calc1-lhopital':{f:['x'],g:['x']},'calc1-taylor':{f:['x']},'calc1-riemann':{f:['x']},'calc1-fundamental':{f:['x'],primitive:['x']},
 'calc2-primitivas':{f:['x']},'calc2-substituicao':{f:['x'],g:['u']},'calc2-partes':{u:['x'],dv:['x']},'calc2-fracoes-parciais':{f:['x']},'calc2-substituicao-trig':{f:['x']},'calc2-quadratura':{f:['x']},'calc2-improprias':{f:['x']},'calc2-areas':{f:['x'],g:['x']},'calc2-cascas':{f:['x']},'calc2-arcos':{f:['x']},'calc2-aplicacoes':{f:['x']},'calc2-parametricas-medidas':{x:['t'],y:['t']},'calc2-edo':{f:['x','y']},'calc2-sequencias':{f:['n']},
 'calc2-superficies':{f:['x','y']},'calc2-limites-caminhos':{f:['x','y']},'calc2-parciais':{f:['x','y']},'calc2-direcionais':{f:['x','y']},'calc2-duplas':{f:['x','y'],lower:['x'],upper:['x']},'calc2-polares':{f:['x','y'],lower:['t'],upper:['t']},'calc2-triplas':{f:['x','y','z'],yl:['x'],yu:['x'],zl:['x','y'],zu:['x','y']},'calc2-jacobiano':{x:['u','v'],y:['u','v'],f:['x','y']},'calc2-lagrange':{f:['x','y'],g:['x','y']},'calc2-campos':{p:['x','y','z'],q:['x','y','z'],r:['x','y','z']},'calc2-integral-linha':{p:['x','y','z'],q:['x','y','z'],r:['x','y','z'],x:['t'],y:['t'],z:['t']},'calc2-fluxo-superficie':{h:['x','y'],p:['x','y','z'],q:['x','y','z'],r:['x','y','z']}
};
const composite={
 'fund-conjuntos':{a:['set',0,30],b:['set',0,30]},'fund-complexos':{a:['vector',2,2],b:['vector',2,2]},'fund-estatistica':{data:['list',1,500]},
 'geo-distancias':{a:['vector',2,3],b:['vector',2,3]},'geo-retas-medidas':{r:['vector',3,3],s:['vector',3,3],p:['vector',2,2]},'geo-circunferencia':{c:['vector',2,2],line:['vector',3,3]},'geo-conica-geral':{coef:['vector',6,6]},'geo-reta-plano':{p:['vector',3,3],v:['vector',3,3],n:['vector',3,3]},'geo-planos':{n1:['vector',3,3],n2:['vector',3,3]},'geo-coordenadas':{p:['vector',3,3]},'geo-poligonos':{points:['rows',3,100,2,2]},
 'alg-produtos':{u:['vector',2,3],v:['vector',2,3]},'alg-produto-misto':{u:['vector',3,3],v:['vector',3,3],w:['vector',3,3]},'alg-matrizes':{a:['matrix',1,8,1,8],b:['matrix',1,8,1,8]},'alg-sistemas':{a:['matrix',1,8,1,8],b:['list',1,8]},'alg-bases':{a:['matrix',1,8,1,8]},'alg-gram-schmidt':{vectors:['matrix',1,8,1,8]},'alg-transformacoes':{a:['matrix',2,2,2,2],v:['vector',2,2],t:['vector',2,2]},'alg-autovalores':{a:['matrix',2,2,2,2]},'alg-minimos-quadrados':{data:['rows',2,500,2,2]},
 'calc2-direcionais':{point:['vector',2,2],v:['vector',2,2],h:['vector',2,2]},'calc2-lagrange':{guess:['vector',3,3]},'calc2-campos':{point:['vector',3,3]}
};
function schema(lab,field){const id=typeof lab==='string'?lab:lab.id,key=field.key;if(field.type==='select')return {kind:'select'};
 if(id==='fund-fracoes')return {kind:'fraction'};
 if(id==='fund-logica')return {kind:'logic'};
 const comp=composite[id]?.[key];if(comp)return {kind:comp[0],min:comp[1],max:comp[2],minCols:comp[3],maxCols:comp[4]};
 const vars=expressionFields[id]?.[key];return vars?{kind:'expression',vars}:{kind:'number',vars:[]};
}
const structured=s=>['matrix','rows','vector','list','set'].includes(s.kind);
function split(value,s){const str=String(value).replace(/\r/g,'').replace(/\t/g,';');if(['matrix','rows'].includes(s.kind))return str.trim().split('\n').filter(x=>x.trim()).map(x=>x.split(';').map(t=>t.trim()));return [str.split(/[;\n]/).map(x=>x.trim())];}
function fraction(value){const v=String(value).replace(/\s/g,'').replace(/[−–]/g,'-'),token='(?:\\([+-]?\\d{1,40}\\)|[+-]?\\d{1,40})';if(!(new RegExp('^'+token+'(?:/'+token+')?$')).test(v))throw new Error('Use um inteiro ou uma fração de inteiros, como 2/3, com até 40 dígitos.');const [a,b]=v.replace(/[()]/g,'').split('/');if(b!==undefined&&BigInt(b)===0n)throw new Error('O denominador não pode ser zero.');return b===undefined?a:`${a}/${b}`;}
function validate(value,s){if(String(value).length>4000)throw new Error('Entrada excede 4.000 caracteres.');if(s.kind==='fraction'){fraction(value);return;}
 if(s.kind==='logic'){K.run('fund-logica',{e:value});return;}
 if(structured(s)){const rows=split(value,s);if(s.kind==='set'){const values=rows[0].filter(Boolean);if(values.length>s.max)throw new Error(`Use até ${s.max} elementos.`);return;}
 const count=['matrix','rows'].includes(s.kind)?rows.length:rows[0].length;
 if(count<s.min||count>s.max)throw new Error(`Use entre ${s.min} e ${s.max} ${['matrix','rows'].includes(s.kind)?'linhas':'componentes'}.`);
 if(['matrix','rows'].includes(s.kind)&&(rows.some(r=>r.length!==rows[0].length)||rows[0].length<s.minCols||rows[0].length>s.maxCols))throw new Error(`Use linhas com ${s.minCols===s.maxCols?s.minCols:`${s.minCols} a ${s.maxCols}`} colunas.`);
 rows.forEach((row,i)=>row.forEach((v,j)=>{try{K.num(v);}catch(e){throw new Error(`${rows.length>1?`Linha ${i+1}, coluna ${j+1}`:`Componente ${j+1}`}: ${e.message}`);}}));return;}
 if(s.kind==='number')K.num(value);else K.ast(value,s.vars||[]);
}
function normalize(value,s){if(s.kind==='fraction')return fraction(value);if(s.kind==='logic')return String(value).trim();if(s.kind==='set')return split(value,s)[0].filter(Boolean).join(';');if(structured(s))return split(value,s).map(r=>r.map(M.normalize).join(';')).join('\n');return M.normalize(value);}
function cellML(v){try{return M.toMathML(v).replace(/^<math[^>]*>/,'').replace(/<\/math>$/,'');}catch{return `<mtext>${esc(v||'□')}</mtext>`;}}
function format(value,s){const wrap=x=>`<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">${x}</math>`;
 if(!String(value).trim()&&s.kind!=='set')return '<span class="math-placeholder">Toque para editar</span>';
 if(s.kind==='fraction'){try{const [a,b]=fraction(value).split('/');return wrap(b?`<mfrac><mn>${esc(a)}</mn><mn>${esc(b)}</mn></mfrac>`:`<mn>${esc(a)}</mn>`);}catch{return wrap(`<mtext>${esc(value)}</mtext>`);}}
 if(s.kind==='logic'){const pretty=String(value).replace(/<->/g,'↔').replace(/->/g,'→').replace(/!/g,'¬').replace(/&/g,'∧').replace(/\|/g,'∨');return wrap(`<mrow>${[...pretty].map(c=>/[pqr]/.test(c)?`<mi>${c}</mi>`:`<mo>${esc(c)}</mo>`).join('')}</mrow>`);}
 if(structured(s)){const rows=split(value,s);if(['matrix','rows'].includes(s.kind)){const visible=rows.slice(0,8);return wrap(`<mrow><mo stretchy="true">[</mo><mtable>${visible.map(row=>`<mtr>${row.slice(0,8).map(v=>`<mtd>${cellML(v)}</mtd>`).join('')}</mtr>`).join('')}${rows.length>8?'<mtr><mtd><mo>⋮</mo></mtd></mtr>':''}</mtable><mo stretchy="true">]</mo></mrow>`);}
 const items=s.kind==='set'?rows[0].filter(Boolean):rows[0],open=s.kind==='set'?'{':s.kind==='list'?'[':'(',close=s.kind==='set'?'}':s.kind==='list'?']':')';return wrap(`<mrow><mo stretchy="true">${open}</mo>${items.slice(0,12).map(v=>s.kind==='set'?`<mtext>${esc(v)}</mtext>`:cellML(v)).join('<mo>;</mo>')}${items.length>12?'<mo>;</mo><mo>…</mo>':''}<mo stretchy="true">${close}</mo></mrow>`);}
 try{return M.toMathML(value);}catch{return wrap(`<mtext>${esc(value)}</mtext>`);}
}
function markup(id,label,value,s){return `<div class="wb-field wb-math-field"><span id="${esc(id)}-label">${esc(label)}</span><input type="hidden" id="${esc(id)}" name="${esc(id.replace(/^wb-/,''))}" value="${esc(value)}"><button class="math-field wb-math-button" id="${esc(id)}-edit" type="button" data-math-source="${esc(id)}" aria-labelledby="${esc(id)}-label" aria-haspopup="dialog"><span class="math-render">${format(value,s)}</span><span class="math-edit-label">Editar</span></button></div>`;}
function refresh(input,s){const button=document.getElementById(input.id+'-edit');if(button)button.querySelector('.math-render').innerHTML=format(input.value,s);}
function customKeyboard(kind,ui){const key=(label,token,action='')=>`<button class="math-key ${action?'command':'function'}" type="button" ${action?`data-action="${action}"`:`data-token="${esc(token)}" data-kind="text"`}>${esc(label)}</button>`;const commands=[['Desfazer','','undo'],['Refazer','','redo'],['←','','cursor-left'],['→','','cursor-right'],['Apagar','','backspace'],['Limpar','','clear']];const keys=kind==='logic'?[['p','p'],['q','q'],['r','r'],['¬','!'],['∧','&'],['∨','|'],['→','->'],['↔','<->'],['(','('],[')',')']]:[...'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'].map(c=>[c,c]).concat([['Espaço',' '],['−','-'],[',',',']]);return `<div class="math-calculator-shell"><div class="math-command-pad">${commands.map(a=>key(...a)).join('')}</div><div class="math-scientific-pad math-symbol-pad">${keys.map(a=>key(...a)).join('')}</div><button class="primary-inline" data-action="apply" type="button">Salvar</button></div>`;}
function editableLogic(expr,cursor,ui){const tokens=expr.match(/<->|->|./g)||[],parts=[];let i=0;for(const t of tokens){const start=i,end=i+t.length,label=({'<->':'↔','->':'→','!':'¬','&':'∧','|':'∨'})[t]||t;if(cursor>=start&&cursor<end)parts.push('<span class="math-cursor"><span class="math-cursor-handle"></span></span>');parts.push(`<span class="math-unit ${/[pqr]/.test(t)?'var':'op'}" data-start="${start}" data-end="${end}">${esc(label)}</span>`);i=end;}if(cursor>=expr.length)parts.push('<span class="math-cursor"><span class="math-cursor-handle"></span></span>');return `<span class="math-editable">${parts.join('')}</span>`;}
function open(input,label,s){const ui=g.OrbisVRuntime.AppUI,commit=v=>{if(!input.isConnected)return;validate(v,s);input.value=v;refresh(input,s);input.dispatchEvent(new Event('input',{bubbles:true}));};
 if(!structured(s)){ui.openMathInput({label,value:input.value,vars:(s.vars||[]).join(','),allowedVariables:s.vars||[],allowCalculus:false,hideTabs:s.kind==='logic',context:s.kind==='logic'?'LÓGICA':s.kind==='fraction'?'FRAÇÃO':s.vars?.length?'NOTAÇÃO MATEMÁTICA':'VALOR NUMÉRICO',validate:v=>validate(v,s),normalize:v=>normalize(v,s),onSave:commit,acceptCharacter:c=>s.kind==='logic'&&/[&|]/.test(c),keyboard:s.kind==='logic'?()=>customKeyboard('logic',ui):undefined,editable:s.kind==='logic'?editableLogic:undefined,afterRender:(u,state)=>{const preview=document.getElementById('mathFormattedPreview');preview.hidden=false;preview.innerHTML=format(state.expr,s);}});return;}
 let rows=split(input.value,s);if(!rows.length)rows=[['']];let row=0,col=0,page=0;const tabular=['matrix','rows'].includes(s.kind),isSet=s.kind==='set',serial=()=>rows.map(r=>r.join(';')).join('\n'),update=state=>{if(rows[row])rows[row][col]=state.expr;};
 function select(r,c,u,state){update(state);row=r;col=c;page=Math.floor((row*rows[0].length+col)/64);state.expr=rows[row][col];state.cursor=state.expr.length;state.undo=[];state.redo=[];state.selectAll=false;u.renderMathEditor();u.focusMathEditor();}
 function renderStructure(u,state){const root=document.getElementById('mathExtraFields'),columns=tabular?rows[0].length:Math.min(4,rows[0].length),count=tabular?rows.length:rows[0].length,all=rows.flatMap((r,i)=>r.map((v,j)=>({v,i,j}))),slice=all.slice(page*64,(page+1)*64);root.hidden=false;
 const control=(action,text,disabled)=>`<button class="secondary-btn" type="button" data-structure-action="${action}" ${disabled?'disabled':''}>${text}</button>`;
 root.innerHTML=`<div class="math-structure-toolbar"><strong>${tabular?`${rows.length} × ${rows[0].length}`:`${rows[0].filter(v=>!isSet||v.trim()).length} ${isSet?'elementos':'componentes'}`}</strong><div>${control('add-row',tabular?'+ linha':'+ componente',count>=s.max)}${control('remove-row',tabular?'− linha':'− componente',count<=Math.max(1,s.min))}${tabular&&s.maxCols>s.minCols?control('add-col','+ coluna',rows[0].length>=s.maxCols)+control('remove-col','− coluna',rows[0].length<=s.minCols):''}</div></div><div class="math-component-grid" style="--component-cols:${columns}">${slice.map(({v,i,j})=>`<button type="button" class="math-component ${i===row&&j===col?'active':''}" data-row="${i}" data-col="${j}" aria-pressed="${i===row&&j===col}" aria-label="${tabular?`Linha ${i+1}, coluna ${j+1}`:`Componente ${j+1}`}"><small>${tabular?`${i+1}, ${j+1}`:j+1}</small><span>${isSet?esc(v||'□'):format(v,{kind:'number'})}</span></button>`).join('')}</div>${all.length>64?`<div class="math-structure-pages">${control('previous','Anterior',page===0)}<span>${page*64+1}–${Math.min(all.length,(page+1)*64)} de ${all.length}</span>${control('next','Próximos',(page+1)*64>=all.length)}</div>`:''}<p class="math-structure-help">${tabular?'Selecione uma célula para editar. Cole tabelas com tabulações ou colunas separadas por ;.':'Selecione um componente para editar. Você também pode colar valores separados por ;.'}</p>`;
 root.onclick=e=>{const cell=e.target.closest('[data-row]'),button=e.target.closest('[data-structure-action]');if(cell){select(Number(cell.dataset.row),Number(cell.dataset.col),u,state);return;}if(!button||button.disabled)return;update(state);const action=button.dataset.structureAction;if(action==='next'||action==='previous'){page+=action==='next'?1:-1;renderStructure(u,state);return;}if(action==='add-row'){if(tabular){rows.push(Array(rows[0].length).fill('0'));row=rows.length-1;col=0;}else{rows[0].push(isSet?'':'0');row=0;col=rows[0].length-1;}}if(action==='remove-row'){if(tabular)rows.pop();else rows[0].pop();row=Math.min(row,rows.length-1);col=Math.min(col,rows[row].length-1);}if(action==='add-col'){rows.forEach(r=>r.push('0'));col=rows[0].length-1;}if(action==='remove-col'){rows.forEach(r=>r.pop());col=Math.min(col,rows[0].length-1);}page=Math.floor((row*rows[0].length+col)/64);state.expr=rows[row][col];state.cursor=state.expr.length;state.undo=[];state.redo=[];state.selectAll=false;u.renderMathEditor();u.focusMathEditor();};
 }
 ui.openMathInput({label,value:rows[0][0],vars:'',allowedVariables:[],allowCalculus:false,hideTabs:isSet,literalText:isSet,allowEmpty:isSet,context:tabular?'MATRIZ / TABELA':isSet?'CONJUNTO':'COMPONENTES',validMessage:'Valores válidos',validate:()=>validate(serial(),s),normalize:()=>normalize(serial(),s),onSave:commit,keyboard:isSet?()=>customKeyboard('set',ui):undefined,acceptCharacter:()=>isSet,beforeRender:(u,state)=>update(state),afterRender:(u,state)=>{renderStructure(u,state);const preview=document.getElementById('mathFormattedPreview');preview.hidden=false;preview.innerHTML=isSet?`<span class="math-text-preview">${esc(state.expr)}</span>`:format(state.expr,{kind:'number'});},onPaste:(text,u,state)=>{if(!/[;\t\n]/.test(text))return false;try{const parsed=split(text,s);validate(text,s);rows=parsed;row=col=page=0;state.expr=rows[0][0];state.cursor=state.expr.length;state.undo=[];state.redo=[];state.selectAll=false;u.renderMathEditor();}catch(e){u.$.mathValidation.textContent=e.message;u.$.mathValidation.className='math-source-hint invalid';}return true;}});
}
g.OrbisMathFields={schema,format,markup,refresh,open,validate,normalize};
})(window);
