/* Topic-specific, bounded visual models. Shared by the local Worker and the UI. */
(function(g){'use strict';
const K=g.LabKit,{num:N,expr:E,vector:V,matrix:M,series:L,curve:C,graph:G}=K,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const metric=(r,label)=>r.metrics.find(m=>m.label===label)?.value,finite=v=>typeof v==='number'&&Number.isFinite(v),lin=(a,b,n,fn)=>Array.from({length:n+1},(_,i)=>fn(a+(b-a)*i/n)),origin=d=>Array(d).fill(0),arrow=(name,v,base=origin(v.length))=>({...L(name,[base,base.map((x,i)=>x+v[i])]),arrow:true});
function contour(f,a,b,c,d,name='Contorno amostrado'){
 const n=52,pts=[],at=(x,y)=>{try{return f(x,y);}catch{return NaN;}},grid=Array.from({length:n+1},(_,i)=>Array.from({length:n+1},(_,j)=>{const x=a+(b-a)*i/n,y=c+(d-c)*j/n;return [x,y,at(x,y)];}));
 for(let i=0;i<n;i++)for(let j=0;j<n;j++){const q=[grid[i][j],grid[i+1][j],grid[i+1][j+1],grid[i][j+1]],cross=[];for(let k=0;k<4;k++){const u=q[k],v=q[(k+1)%4];if(!finite(u[2])||!finite(v[2]))continue;if((u[2]<0&&v[2]>=0)||(u[2]>=0&&v[2]<0)){const t=u[2]/(u[2]-v[2]);cross.push([u[0]+t*(v[0]-u[0]),u[1]+t*(v[1]-u[1])]);}}for(let k=0;k+1<cross.length;k+=2)pts.push(cross[k],cross[k+1],[null,null]);}
 return L(name,pts.slice(0,14500));
}
function planeGrid(n,d,name){const base=K.scale(n,-d/K.dot(n,n)),seed=[0,0,0];seed[n.map(Math.abs).indexOf(Math.min(...n.map(Math.abs)))]=1;const raw=K.cross(n,seed),u=K.scale(raw,1/K.norm(raw)),w=K.cross(n,u),v=K.scale(w,1/K.norm(w)),point=(a,b)=>base.map((x,i)=>x+a*u[i]+b*v[i]),lines=[];for(let i=-5;i<=5;i++){lines.push(L(name,[point(i,-5),point(i,5)]),L(name,[point(-5,i),point(5,i)]));}return lines;}
function prepare(id,p,r){
 const diagram=kind=>r.diagram={kind},plot=(title,series,extra={})=>{r.plot={series,...extra};r.visualTitle=title;},setTitle=t=>r.visualTitle=t;
 if(id==='fund-expressoes')plot('Valor na reta numérica',[L('Zero',[[0,0]],'points'),L('Resultado',[[r.primary,0]],'points')],{axes:['Valor','']});
 if(id==='fund-fracoes')diagram('fractions');
 if(id==='fund-divisibilidade')diagram('factors');
 if(id==='fund-proporcoes'){const a=N(p.a),b=N(p.b),c=N(p.c),span=Math.max(1,Math.abs(a),Math.abs(c))*1.2,f=p.op==='inverse'?x=>a*b/x:p.op==='percent'?x=>x*b/100:x=>b*x/a;plot(p.op==='percent'?'Percentual aplicado a diferentes valores':'Variação da correspondência',[C(p.op==='inverse'?'Relação inversa':p.op==='percent'?`${p.b}% do valor`:'Relação direta',f,p.op==='inverse'&&a>0&&c>0?Math.min(a,c)*.2:Math.min(0,a,c)-span*.1,span),L('Valor escolhido',[[p.op==='percent'?a:c,r.primary]],'points')],{axes:['Valor A','Correspondente B']});}
 if(id==='fund-unidades'){const x=N(p.x),v=r.primary,slope=K.run(id,{...p,x:String(x+1)}).primary-v,span=Math.max(1,Math.abs(x)*.5),minimum=({c:-273.15,f:-459.67,k:0})[p.from]??-Infinity;plot('Correspondência entre unidades',[C('Conversão',t=>v+slope*(t-x),Math.max(minimum,x-span),x+span),L('Medida escolhida',[[x,v]],'points')],{axes:[`Origem (${p.from})`,`Destino (${p.to})`]});}
 if(id==='fund-conjuntos')diagram('sets');
 if(id==='fund-logica')diagram('logic');
 if(id==='fund-algebra'||id==='calc2-fracoes-parciais'){const original=E(p.e||p.f),out=E(r.metrics[0].value);plot('Expressão original e expressão transformada',[C('Original',original,-5,5),C('Transformada, no domínio original',x=>finite(original(x))?out(x):NaN,-5,5)]);r.visualNote='Janela x ∈ [−5; 5]. A coincidência visual não é uma demonstração de identidade; as restrições do domínio original permanecem.';}
 if(id==='fund-medidas-planas'){const a=N(p.a),b=N(p.b),h=N(p.h),n=N(p.n);let pts;if(p.shape==='rectangle')pts=[[0,0],[a,0],[a,b],[0,b],[0,0]];if(p.shape==='trapezoid')pts=[[0,0],[a,0],[(a+b)/2,h],[(a-b)/2,h],[0,0]];if(p.shape==='circle')pts=lin(0,2*Math.PI,180,t=>[a*Math.cos(t),a*Math.sin(t)]);if(p.shape==='polygon'){const R=a/(2*Math.sin(Math.PI/n));pts=lin(0,2*Math.PI,n,t=>[R*Math.cos(t),R*Math.sin(t)]);}plot('Contorno da figura nas medidas informadas',[L('Figura',pts)],{equal:true});}
 if(id==='fund-solidos'){const a=N(p.a),b=N(p.b),h=N(p.h),lines=[];if(p.shape==='sphere'){for(let i=1;i<8;i++){const t=Math.PI*i/8;lines.push(L('Paralelos',lin(0,2*Math.PI,64,u=>[a*Math.sin(t)*Math.cos(u),a*Math.sin(t)*Math.sin(u),a*Math.cos(t)])));}for(let i=0;i<8;i++){const u=Math.PI*i/4;lines.push(L('Meridianos',lin(0,2*Math.PI,64,t=>[a*Math.sin(t)*Math.cos(u),a*Math.sin(t)*Math.sin(u),a*Math.cos(t)])));}}else if(['cone','cylinder'].includes(p.shape)){lines.push(L('Base',lin(0,2*Math.PI,80,t=>[a*Math.cos(t),a*Math.sin(t),0])));if(p.shape==='cylinder')lines.push(L('Topo',lin(0,2*Math.PI,80,t=>[a*Math.cos(t),a*Math.sin(t),h])));for(let i=0;i<12;i++){const t=i*Math.PI/6,q=[a*Math.cos(t),a*Math.sin(t),0];lines.push(L('Geratrizes',[q,p.shape==='cone'?[0,0,h]:[q[0],q[1],h]]));}}else{const base=[[0,0,0],[a,0,0],[a,p.shape==='pyramid'?a:b,0],[0,p.shape==='pyramid'?a:b,0],[0,0,0]];lines.push(L('Base',base));if(p.shape==='box')lines.push(L('Topo',base.map(q=>[q[0],q[1],h])));base.slice(0,4).forEach(q=>lines.push(L('Arestas',[q,p.shape==='pyramid'?[a/2,a/2,h]:[q[0],q[1],h]])));}plot('Forma e dimensões do sólido',lines,{dimensions:3,equal:true});}
 if(id==='geo-conica-geral'){const [a,b,c,d,e,f]=K.list(p.coef,6,6),center=metric(r,'Centro'),q=center==='Sem centro único'?[0,0]:V(center,2),det=4*a*c-b*b,at=a*q[0]**2+b*q[0]*q[1]+c*q[1]**2+d*q[0]+e*q[1]+f,ev=[(a+c+Math.hypot(a-c,b))/2,(a+c-Math.hypot(a-c,b))/2].map(Math.abs).filter(x=>x>1e-10),span=Math.max(4,Math.min(1e6,2.5*Math.sqrt(Math.abs(at)/(Math.min(...ev)||1)))) ;plot('Cônica no plano cartesiano',[contour((x,y)=>a*x*x+b*x*y+c*y*y+d*x+e*y+f,q[0]-span,q[0]+span,q[1]-span,q[1]+span)],{equal:true});r.visualNote='Contorno numérico em uma janela ao redor do centro, quando existe. Pontos isolados, traços muito estreitos ou fora da janela podem não aparecer.';if(metric(r,'Classificação').includes('imaginária'))r.visualNote='A classificação indica ausência de pontos reais para esta cônica.';}
 if(id==='geo-reta-plano'){r.plot.series.push(...planeGrid(V(p.n,3),N(p.d),'Plano'));setTitle('Reta, plano e projeção do ponto');}
 if(id==='geo-planos'){const lines=[...planeGrid(V(p.n1,3),N(p.d1),'Plano 1'),...planeGrid(V(p.n2,3),N(p.d2),'Plano 2'),...(r.plot?.series||[])];plot('Planos e sua posição relativa',lines,{dimensions:3,equal:true});r.visualNote='Os planos são infinitos; a malha mostra um recorte de cada um.';}
 if(id==='alg-matrizes')diagram('matrices');
 if(id==='alg-sistemas'){const a=M(p.a),b=K.list(p.b);diagram('matrices');if(a[0].length===2){const lines=[];a.forEach(([u,v],i)=>{if(!u&&!v)return;const pts=Math.abs(v)>Math.abs(u)?[[-6,(b[i]+6*u)/v],[6,(b[i]-6*u)/v]]:[[(b[i]+6*v)/u,-6],[(b[i]-6*v)/u,6]];lines.push(L(`Equação ${i+1}`,pts));});plot('Equações como retas no plano',lines,{equal:true,axes:['x₁','x₂']});r.visualNote='Janela de amostragem fixa; interseções muito distantes podem ficar fora dos segmentos desenhados.';}}
 if(id==='alg-bases'||id==='alg-gram-schmidt'){const input=M(id==='alg-bases'?p.a:p.vectors),rows=id==='alg-bases'?K.transpose(input):input,dim=rows[0].length;diagram('matrices');if(dim===2||dim===3){const lines=rows.map((v,i)=>arrow(`Vetor ${i+1}`,v));if(id==='alg-gram-schmidt')r.rows.forEach((v,i)=>lines.push(arrow(`Ortonormal ${i+1}`,v)));plot(id==='alg-bases'?'Vetores originais no espaço':'Vetores originais e base ortonormal',lines,{dimensions:dim,equal:true});}}
 if(id==='alg-autovalores'){const a=M(p.a),apply=v=>a.map(row=>K.dot(row,v)),circle=lin(0,2*Math.PI,160,t=>[Math.cos(t),Math.sin(t)]),lines=[L('Círculo unitário',circle),L('Imagem por A',circle.map(apply)),arrow('e₁',[1,0]),arrow('A·e₁',apply([1,0])),arrow('e₂',[0,1]),arrow('A·e₂',apply([0,1]))];for(const [lambda,basis] of r.rows||[]){if(basis==='R²')continue;const v=V(basis,2);lines.push(arrow(`Autovetor λ=${K.fmt(lambda)}`,v),arrow(`Imagem λ=${K.fmt(lambda)}`,apply(v)));}plot('Ação da matriz e direções próprias',lines,{equal:true});r.visualNote=r.rows?'Um autovetor e sua imagem pertencem à mesma reta.':'Sem direção própria real não nula: a transformação do círculo permanece visível.';}
 if(id==='calc1-taxas'){const x=N(p.x),y=N(p.y),span=Math.max(2,Math.abs(x),Math.abs(y))*1.5,rate=N(p.rate),dy=metric(r,'dy/dt');plot('Relação implícita e vetor velocidade',[contour(E(p.f,['x','y']),x-span,x+span,y-span,y+span,'F(x,y) = 0'),L('Ponto atual',[[x,y]],'points'),arrow('Velocidade (dx/dt; dy/dt)',[rate,dy],[x,y])],{equal:true});r.visualNote='O vetor parte do ponto atual e usa uma unidade de tempo como escala. O contorno é amostrado.';}
 if(id==='calc1-lhopital'||id==='calc2-limites-caminhos'){const start=1,count=r.columns.length,series=[];for(let i=start;i<count;i++)series.push(L(r.columns[i],r.rows.map((row,k)=>[k+1,finite(row[i])?row[i]:null])));plot('Aproximações por ordens decimais',series,{axes:[id==='calc1-lhopital'?'k em x = c + 10⁻ᵏ':'k em t = 10⁻ᵏ','Valor observado']});}
 if(id==='calc2-primitivas'){const raw=r.metrics[0].value.replace(/\s*\+\s*C$/,''),f=E(raw);plot('Família de primitivas: variação da constante C',[-2,0,2].map(c=>C(`C = ${c}`,x=>f(x)+c,-5,5)));r.visualNote='Janela x ∈ [−5; 5]. A constante desloca verticalmente a primitiva no domínio em que ela está definida.';}
 if(id==='calc2-improprias'){let pts;if(p.mode.startsWith('p-')){const power=N(p.p),tail=p.mode==='p-tail';pts=Array.from({length:40},(_,i)=>{const k=(i+1)/10,q=1-power,value=power===1?k*Math.LN10:tail?Math.expm1(q*k*Math.LN10)/q:-Math.expm1(-q*k*Math.LN10)/q;return [k,finite(value)?value:null];});r.visualNote=tail?'Integral de 1 até 10ᵏ. A classificação analítica da família aparece nos resultados.':'Integral de 10⁻ᵏ até 1. A classificação analítica da família aparece nos resultados.';}else{pts=r.rows.map((row,i)=>[i+1,finite(row[2])?row[2]:null]);r.visualNote='Pontos sem quadratura estabilizada são omitidos. A aparência de estabilização não certifica convergência.';}plot('Evolução das integrais truncadas',[L('Integral truncada',pts)],{axes:['Ordem k do truncamento','Integral aproximada']});}
 if(id==='calc2-triplas'){const a=N(p.a),b=N(p.b),yl=E(p.yl),yu=E(p.yu),zl=E(p.zl,['x','y']),zu=E(p.zu,['x','y']),lines=[],point=(x,t,upper)=>{const y=yl(x)+t*(yu(x)-yl(x));return [x,y,(upper?zu:zl)(x,y)];};for(let i=0;i<=10;i++){const x=a+(b-a)*i/10,t=i/10;for(const upper of [false,true]){lines.push(L(upper?'Limite superior de z':'Limite inferior de z',lin(0,1,24,s=>point(x,s,upper))),L(upper?'Limite superior de z':'Limite inferior de z',lin(a,b,24,q=>point(q,t,upper))));}if(i===0||i===10)for(let j=0;j<=10;j++)lines.push(L('Limites laterais',[point(x,j/10,false),point(x,j/10,true)]));}plot('Região de integração no espaço',lines,{dimensions:3,equal:true});r.visualNote='Malha da região definida pelos limites, independente do valor do integrando.';}
 if(id==='calc2-jacobiano'){const a=N(p.a),b=N(p.b),c=N(p.c),d=N(p.d),x=E(p.x,['u','v']),y=E(p.y,['u','v']),lines=[];for(let i=0;i<=10;i++){const u=a+(b-a)*i/10,v=c+(d-c)*i/10;lines.push(L('u constante',lin(c,d,40,q=>[x(u,q),y(u,q)])),L('v constante',lin(a,b,40,q=>[x(q,v),y(q,v)])));}plot('Imagem da malha do retângulo uv',lines,{equal:true});r.visualNote='Cada linha vem de u ou v constante. Sobreposições indicam possíveis multiplicidades; o desenho não verifica injetividade.';}
 if(id==='calc2-lagrange'){const q=V(metric(r,'Candidato x; y'),2),span=Math.max(2,K.norm(q)*1.5),f=E(p.f,['x','y']),value=metric(r,'Objetivo no candidato');plot('Restrição e nível do objetivo no candidato',[contour(E(p.g,['x','y']),q[0]-span,q[0]+span,q[1]-span,q[1]+span,'Restrição g = 0'),contour((x,y)=>f(x,y)-value,q[0]-span,q[0]+span,q[1]-span,q[1]+span,'Nível de f no candidato'),L('Candidato',[q],'points')],{equal:true});r.visualNote='Contornos amostrados. O ponto é um candidato numérico e não está classificado como máximo ou mínimo.';}
 if(id==='calc2-campos'){const q=V(p.point,3),field=[p.p,p.q,p.r].map(s=>E(s,['x','y','z'])),sample=[];for(let i=-2;i<=2;i++)for(let j=-2;j<=2;j++){const pt=[q[0]+i,q[1]+j,q[2]],v=field.map(f=>f(...pt));if(v.every(finite))sample.push({pt,v});}const mx=Math.max(1,...sample.map(s=>K.norm(s.v))),scale=.7/mx,lines=sample.map(s=>arrow('Campo no plano z = z₀',K.scale(s.v,scale),s.pt)),vp=field.map(f=>f(...q));lines.push(arrow('Campo no ponto selecionado',K.scale(vp,scale),q));plot('Campo vetorial em uma seção do espaço',lines,{dimensions:3,equal:true});r.visualNote=`Seção z = ${K.fmt(q[2])}. Todos os vetores usam o mesmo fator visual ${K.fmt(scale)}; os valores reais constam nos resultados.`;}
 // Reinforce existing diagrams with the geometric objects used in the calculation.
 if(id==='fund-trigonometria'){const t=N(p.angle)*(p.unit==='deg'?Math.PI/180:1),x=Math.cos(t),y=Math.sin(t);r.plot.series.push(L('Cosseno',[[0,0],[x,0]]),L('Seno',[[x,0],[x,y]]));}
 if(id==='geo-circunferencia'){const [a,b,c]=V(p.line,3),q=V(p.c,2),rad=N(p.r)*1.5,pts=Math.abs(b)>Math.abs(a)?[[q[0]-rad,(-c-a*(q[0]-rad))/b],[q[0]+rad,(-c-a*(q[0]+rad))/b]]:[[(-c-b*(q[1]-rad))/a,q[1]-rad],[(-c-b*(q[1]+rad))/a,q[1]+rad]];r.plot.series.push(L('Reta',pts));}
 if(id==='calc2-areas'){const a=N(p.a),b=N(p.b),f=E(p.f),h=E(p.g),pts=[...lin(a,b,100,x=>[x,f(x)]),...lin(b,a,100,x=>[x,h(x)])];r.plot.series.unshift({...L('Região entre as curvas',pts),fill:true});}
 if(id==='calc2-duplas'){const a=N(p.a),b=N(p.b),lo=E(p.lower),hi=E(p.upper);r.plot.series.unshift({...L('Região de integração',[...lin(a,b,100,x=>[x,lo(x)]),...lin(b,a,100,x=>[x,hi(x)])]),fill:true});}
 if(id==='calc1-riemann')r.plot.series.forEach(s=>{if(s.name==='Retângulo')s.fill=true;});
 if(r.plot){r.plot.axes=r.plot.axes||({'fund-progressoes':['n','aₙ'],'fund-combinatoria':['k','P(X = k)'],'fund-estatistica':['Valor','Frequência'],'fund-juros':['Período','Montante'],'fund-complexos':['Parte real','Parte imaginária']})[id]||(r.plot.dimensions===3?['x','y','z']:['x','y']);r.visualTitle=r.visualTitle||'Representação do experimento';for(const s of r.plot.series)s.points=s.points.map(pt=>pt.map(x=>finite(x)?x:null));}
 return r;
}
function svg(body,title,height=250){return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 680 ${height}" role="img" aria-label="${esc(title)}"><title>${esc(title)}</title>${body}</svg>`;}
const label=(x,y,text,anchor='middle',size=15)=>`<text x="${x}" y="${y}" text-anchor="${anchor}" font-size="${size}" fill="currentColor">${esc(text)}</text>`;
function matrixCard(title,rows){if(!rows?.length)return `<div class="wb-matrix-card"><strong>${esc(title)}</strong><p>Sem vetores na base.</p></div>`;const max=Math.max(1,...rows.flat().map(Math.abs));return `<div class="wb-matrix-card"><strong>${esc(title)}</strong><div class="wb-cell-matrix" style="--matrix-columns:${rows[0].length}">${rows.flatMap((row,i)=>row.map((v,j)=>`<span title="Linha ${i+1}, coluna ${j+1}: ${esc(K.fmt(v))}" style="background:rgba(${v<0?'205,78,114':'38,156,177'},${(.08+.25*Math.abs(v)/max).toFixed(3)})">${esc(K.fmt(v))}</span>`)).join('')}</div></div>`;}
function render(id,p,r,context={}){if(!r.diagram)return '';const kind=r.diagram.kind;
 if(kind==='fractions'){const number=s=>{const [a,b='1']=String(s).split('/');return Number(a)/Number(b);},values=[number(p.a),number(p.b),r.primary??metric(r,'Decimal aproximado')],lo=Math.min(0,...values,...(context.fractionRange||[])),hi=Math.max(1,...values,...(context.fractionRange||[])),x=v=>135+495*(v-lo)/(hi-lo),labels=[`A = ${p.a}`,`B = ${p.b}`,`Resultado = ${metric(r,'Fração irredutível')}`],colors=['var(--cyan)','var(--pink)','var(--violet)'];let body='';values.forEach((v,i)=>{const y=43+i*60;body+=label(15,y,labels[i].length>27?labels[i].slice(0,24)+'…':labels[i],'start',12)+`<rect x="${Math.min(x(0),x(v))}" y="${y+8}" width="${Math.max(1,Math.abs(x(v)-x(0)))}" height="21" fill="${colors[i]}" opacity=".7"/><path d="M${x(0)} ${y+4}v29" stroke="currentColor"/>`;const denominator=Math.abs(Number((i===0?p.a:i===1?p.b:metric(r,'Fração irredutível')).split('/')[1]||1));if(denominator<=24&&Math.abs(v)*denominator<=100)for(let j=1;j<Math.abs(v)*denominator;j++){const xx=x(Math.sign(v)*j/denominator);body+=`<path d="M${xx} ${y+8}v21" stroke="var(--surface)"/>`;}});for(let i=0;i<=4;i++){const v=lo+(hi-lo)*i/4;body+=label(x(v),243,K.fmt(Number(v.toPrecision(4))),'middle',11);}body+=`<path d="M135 222H630" stroke="currentColor"/>`;return svg(body,'Comparação das frações na mesma escala')+'<p class="wb-visual-caption">Comprimentos na mesma escala. Marcas de partes iguais são exibidas quando legíveis; o desenho usa aproximações decimais.</p>';}
 if(kind==='factors'){const factor=n=>{const map=new Map();for(let d=2;d*d<=n;d+=(d===2?1:2))while(n%d===0){map.set(d,(map.get(d)||0)+1);n/=d;}if(n>1)map.set(n,(map.get(n)||0)+1);return map;},a=factor(N(p.a)),b=factor(N(p.b)),primes=[...new Set([...a.keys(),...b.keys()])].sort((a,b)=>a-b),common=new Map(primes.map(q=>[q,Math.min(a.get(q)||0,b.get(q)||0)])),multiple=new Map(primes.map(q=>[q,Math.max(a.get(q)||0,b.get(q)||0)]));return '<div class="wb-factor-diagram">'+[['A',a],['B',b],['MDC',common],['MMC',multiple]].map(([name,m])=>`<div><strong>${name}</strong>${primes.filter(q=>m.get(q)).map((q)=>`<span style="border-color:hsl(${primes.indexOf(q)*67%360} 55% 55%)">${q}${m.get(q)>1?`<sup>${m.get(q)}</sup>`:''}</span>`).join('<i>×</i>')||'<span>1</span>'}</div>`).join('')+'</div><p class="wb-visual-caption">A mesma cor identifica o mesmo primo. Os expoentes permanecem explícitos em cada decomposição.</p>';}
 if(kind==='sets'){const set=s=>[...new Set(s.split(';').map(x=>x.trim()).filter(Boolean))],a=set(p.a),b=set(p.b),left=a.filter(x=>!b.includes(x)),mid=a.filter(x=>b.includes(x)),right=b.filter(x=>!a.includes(x));return svg(`<circle cx="265" cy="132" r="108" fill="var(--cyan)" fill-opacity=".12" stroke="var(--cyan)" stroke-width="2"/><circle cx="415" cy="132" r="108" fill="var(--pink)" fill-opacity=".12" stroke="var(--pink)" stroke-width="2"/>${label(212,110,'A − B')+label(340,110,'A ∩ B')+label(468,110,'B − A')+label(212,152,left.length,'middle',28)+label(340,152,mid.length,'middle',28)+label(468,152,right.length,'middle',28)}`,'Diagrama de Venn: quantidades por região')+`<div class="wb-set-regions">${[['A − B',left],['A ∩ B',mid],['B − A',right]].map(([title,items])=>`<div><strong>${title}</strong><p>${esc(items.join('; ')||'∅')}</p></div>`).join('')}</div><p class="wb-visual-caption">Números indicam quantidades. As áreas dos círculos são esquemáticas.</p>`;}
 if(kind==='logic'){const w=580/r.columns.length,h=38;let body=r.columns.map((c,j)=>label(50+w*(j+.5),27,c)).join('');r.rows.forEach((row,i)=>row.forEach((v,j)=>{body+=`<rect x="${50+j*w+3}" y="${42+i*h}" width="${w-6}" height="${h-5}" rx="5" fill="${v==='V'?'var(--cyan)':'var(--pink)'}" fill-opacity=".2"/>`+label(50+w*(j+.5),65+i*h,v);}));return svg(body,'Mapa de valorações: V verdadeiro e F falso',55+r.rows.length*h)+'<p class="wb-visual-caption">Cada linha representa uma valoração completa. V = verdadeiro; F = falso.</p>';}
 if(kind==='matrices'){const input=M(id==='alg-gram-schmidt'?p.vectors:p.a),cards=[matrixCard(id==='alg-gram-schmidt'?'Vetores de entrada':'Matriz A',input)];if(id==='alg-matrizes'&&['sum','product'].includes(p.op))cards.push(matrixCard('Matriz B',M(p.b)));if(id==='alg-sistemas')cards.push(matrixCard('Termos independentes',K.list(p.b).map(x=>[x])));if(r.rows)cards.push(matrixCard(id==='alg-sistemas'?'Matriz aumentada reduzida':id==='alg-bases'?'Base do núcleo (vetores nas linhas)':id==='alg-gram-schmidt'?'Base ortonormal':'Resultado',r.rows));return `<div class="wb-matrix-diagram">${cards.join('')}</div><p class="wb-visual-caption">Sinal e magnitude destacam as células; a intensidade é relativa ao maior valor absoluto de cada matriz. Os números são a referência quantitativa.</p>`;}
 return '';
}
g.OrbisRepresentations={prepare,render,contour};
})(window);
