/* Explorações dos anos iniciais. Cálculos limitados e reproduzíveis. */
(function(g){'use strict';
const K=g.LabKit,{field:F,select:S,integer:I,result:R,table:T,graph:G,series:L,fail}=K;
const reg=(id,title,group,summary,fields,fn)=>K.register('fundamentos','fund-'+id,title,group,summary,fields,fn);
const pts=(n,columns=10,y=0)=>Array.from({length:n},(_,i)=>[i%columns,Math.floor(i/columns)+y]);
reg('contagem','Coleções e contagem','Primeiras explorações','Agrupe e compare duas coleções de objetos.',[F('a','Objetos da coleção A (0 a 100)','17'),F('b','Objetos da coleção B (0 a 100)','12'),F('grupo','Objetos por fileira (1 a 10)','5')],p=>{const a=I(p.a,0,100),b=I(p.b,0,100),n=I(p.grupo,1,10);return R([['Coleção A',a],['Coleção B',b],['Diferença A − B',a-b],['Comparação',a===b?'Mesma quantidade':a>b?'A tem mais':'B tem mais']],{primary:a-b,plot:{...G(L('Coleção A',pts(a,n),'points'),L('Coleção B',pts(b,n,Math.ceil(a/n)+2),'points')),equal:true,axes:['Posição na fileira','Fileira']},visualTitle:'Cada ponto representa um objeto',method:'A organização em fileiras não altera a quantidade de objetos.'});});
reg('decimal','Valor posicional e decomposição','Primeiras explorações','Compare números e investigue o papel de cada algarismo.',[F('a','Número A (0 a 999999)','203'),F('b','Número B (0 a 999999)','230')],p=>{const a=I(p.a,0,999999),b=I(p.b,0,999999),names=['Unidade','Dezena','Centena','Unidade de milhar','Dezena de milhar','Centena de milhar'],rows=names.map((n,i)=>[n,Math.floor(a/10**i)%10,Math.floor(b/10**i)%10,10**i]);return R([['Número A',a],['Número B',b],['Comparação',a===b?'A = B':a>b?'A > B':'A < B'],['Decomposição de A',rows.filter(r=>r[1]).reverse().map(r=>`${r[1]} × ${r[3]}`).join(' + ')||'0']],{primary:a,...T(rows,['Ordem','Algarismo A','Algarismo B','Valor da unidade']),plot:G(L('Algarismos de A',rows.map((r,i)=>[i+1,r[1]]),'points'),L('Algarismos de B',rows.map((r,i)=>[i+1,r[2]]),'points')),visualTitle:'Algarismo em cada ordem (1 = unidade)',method:'Algarismos de 0 a 9; o valor representado depende da posição.'});});
reg('agrupamentos','Multiplicação e repartição','Primeiras explorações','Monte grupos iguais e observe quociente e resto.',[F('total','Quantidade de objetos (0 a 100)','23'),F('grupos','Número de grupos (1 a 10)','4')],p=>{const n=I(p.total,0,100),d=I(p.grupos,1,10),q=Math.floor(n/d),r=n%d;const series=Array.from({length:d},(_,i)=>L('Grupo '+(i+1),Array.from({length:q},(_,j)=>[i+1,j+1]),'points'));series.push(L('Resto',Array.from({length:r},(_,i)=>[d+2,i+1]),'points'));return R([['Objetos por grupo',q],['Número de grupos',d],['Resto',r],['Recomposição',`${n} = ${d} × ${q} + ${r}`]],{primary:q,...T(Array.from({length:d},(_,i)=>[i+1,q]),['Grupo','Quantidade']),plot:{...G(...series),equal:true,axes:['Grupo (resto à direita)','Objeto']},visualTitle:'Distribuição em partes iguais'});});
reg('padroes','Sequências e regularidades','Primeiras explorações','Crie sequências numéricas e investigue a regra de formação.',[F('inicio','Primeiro número','2'),F('passo','Quanto muda a cada posição','3'),F('n','Quantidade de termos (2 a 30)','8')],p=>{const a=I(p.inicio,0,10000),d=I(p.passo,-100,100),n=I(p.n,2,30),rows=Array.from({length:n},(_,i)=>[i+1,a+i*d]);if(rows.some(r=>r[1]<0))fail('Nesta exploração use uma sequência de números naturais. Ajuste o início ou o passo.');return R([['Último termo',rows.at(-1)[1]],['Próximo termo',a+n*d],['Variação por posição',d]],{primary:a+n*d,...T(rows,['Posição','Número']),plot:G(L('Termos',rows,'points')),visualTitle:'Cada posição corresponde a um termo',method:'Explore o próximo termo antes de revelar o resultado.'});});
reg('malha','Área e perímetro na malha','Primeiras explorações','Conte quadradinhos e compare contorno e superfície.',[F('a','Colunas (1 a 12)','6'),F('b','Linhas (1 a 12)','4')],p=>{const a=I(p.a,1,12),b=I(p.b,1,12),series=[L('Contorno',[[0,0],[a,0],[a,b],[0,b],[0,0]])];for(let i=1;i<a;i++)series.push(L('Malha',[[i,0],[i,b]]));for(let j=1;j<b;j++)series.push(L('Malha',[[0,j],[a,j]]));return R([['Quadrados unitários',a*b],['Área (u²)',a*b],['Perímetro (u)',2*(a+b)]],{primary:a*b,plot:{...G(...series),equal:true,axes:['Comprimento (u)','Comprimento (u)']},visualTitle:'Cada quadradinho tem área 1 u²',method:'Compare retângulos com a mesma área e contornos diferentes.'});});
reg('pesquisa','Tabelas e colunas','Primeiras explorações','Registre três contagens e compare frequências.',[F('a','Contagem da categoria 1','8'),F('b','Contagem da categoria 2','5'),F('c','Contagem da categoria 3','12')],p=>{const a=[I(p.a,0,1000),I(p.b,0,1000),I(p.c,0,1000)],total=a.reduce((s,x)=>s+x,0),rows=a.map((n,i)=>['Categoria '+(i+1),n,total?n/total*100:0]);return R([['Total de observações',total],['Maior frequência',Math.max(...a)],['Menor frequência',Math.min(...a)]],{primary:total,...T(rows,['Categoria','Frequência','Percentual (%)']),plot:G(...a.map((n,i)=>({...L('Categoria '+(i+1),[[i+.7,0],[i+.7,n],[i+1.3,n],[i+1.3,0],[i+.7,0]]),fill:true}))),visualTitle:'Frequências por categoria',method:'Defina no Caderno o significado das categorias e a origem dos dados.',notice:total?'Percentuais relativos ao total informado.':'Sem observações: os percentuais apresentados são zero por convenção; não há distribuição estimada.'});});
reg('chances','Acaso e frequência experimental','Primeiras explorações','Compare chance teórica e resultados de sorteios com reposição.',[F('a','Fichas do tipo A','3'),F('b','Fichas do tipo B','7'),F('n','Sorteios (1 a 1000)','100'),F('semente','Identificador do experimento (1 a 999999)','42')],p=>{const a=I(p.a,0,100),b=I(p.b,0,100),n=I(p.n,1,1000);let seed=I(p.semente,1,999999),hits=0;const rows=[];if(a+b===0)fail('Inclua pelo menos uma ficha.');for(let i=1;i<=n;i++){seed=(1664525*seed+1013904223)>>>0;const hit=seed/4294967296<a/(a+b);hits+=+hit;rows.push([i,hit?'A':'B',hits/i]);}return R([['Chance teórica de A',a/(a+b)],['Ocorrências de A',hits],['Frequência observada de A',hits/n]],{primary:a/(a+b),...T(rows,['Sorteio','Resultado','Frequência acumulada de A']),plot:G(L('Frequência acumulada',rows.map(r=>[r[0],r[2]])),L('Chance teórica',[[1,a/(a+b)],[n,a/(a+b)]])),visualTitle:'Frequência e chance não são a mesma medida',method:'Sorteio pseudoaleatório com reposição; mesmo identificador reproduz a mesma sequência. Cada ficha tem a mesma chance.',notice:'Uma amostra não garante a frequência exata da probabilidade teórica.'});});
reg('percurso','Localização e deslocamento','Primeiras explorações','Descreva um trajeto e compare pontos de referência.',[F('x','Posição inicial x','1'),F('y','Posição inicial y','2'),F('dx','Deslocamento horizontal','3'),F('dy','Deslocamento vertical','2')],p=>{const x=I(p.x,-20,20),y=I(p.y,-20,20),dx=I(p.dx,-20,20),dy=I(p.dy,-20,20);return R([['Posição final x',x+dx],['Posição final y',y+dy],['Distância do trajeto em duas etapas',Math.abs(dx)+Math.abs(dy)]],{primary:x+dx,plot:{...G(L('Trajeto horizontal e vertical',[[x,y],[x+dx,y],[x+dx,y+dy]]),L('Início',[[x,y]],'points'),L('Chegada',[[x+dx,y+dy]],'points')),equal:true,axes:['Horizontal (u)','Vertical (u)']},visualTitle:'Trajeto relativo aos eixos fixos',method:'Direita e cima são os sentidos positivos dos eixos. Os eixos permanecem fixos.'});});
})(window);
