(function(g){'use strict';
const K=g.LabKit,MF=g.OrbisMathFields,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),clone=v=>JSON.parse(JSON.stringify(v)),$=id=>document.getElementById(id),KEY='orbisvWorkbenchV1';
const references={};
let active=null,worker=null,timer=null,saveTimer=null,inputs={},chartView=null;
function destroyChart(){chartView?.destroy();chartView=null;}
try{const saved=JSON.parse(localStorage.getItem(KEY)||'{}');for(const m of K.modules)if(saved[m.id])inputs[m.id]=cleanValues(m,saved[m.id]);}catch{}
function cleanValues(m,raw){if(!raw||typeof raw!=='object')throw new Error('Dados de laboratório inválidos.');return Object.fromEntries(m.fields.map(f=>{const v=String(raw[f.key]??f.value);if(v.length>4000)throw new Error('Entrada muito extensa.');if(f.type==='select'&&!f.options.some(o=>o[0]===v))throw new Error('Opção inválida no registro.');return [f.key,v];}));}
function values(){return Object.fromEntries(active.lab.fields.map(f=>[f.key,$('wb-'+f.key).value]));}
function save(){if(!active)return;inputs[active.lab.id]=values();try{localStorage.setItem(KEY,JSON.stringify(inputs));$('wbSaveStatus').textContent='Entradas salvas neste dispositivo.';}catch{$('wbSaveStatus').textContent='Sem espaço para salvar entradas. Exporte o resultado ou registre no Caderno.';}}
function stop(){clearTimeout(timer);if(worker){worker.terminate();worker=null;}if($('wbCancel'))$('wbCancel').hidden=true;if($('wbCalculate'))$('wbCalculate').disabled=false;}
function close(){destroyChart();if(active){if(g.OrbisVRuntime.AppUI.mathState?.options)g.OrbisVRuntime.AppUI.closeModal('mathEditorModal');clearTimeout(saveTimer);save();}stop();active=null;}
function field(f,v){if(f.type!=='select')return MF.markup('wb-'+f.key,f.label,v,MF.schema(active.lab,f));return `<label class="wb-field" for="wb-${esc(f.key)}"><span>${esc(f.label)}</span><select id="wb-${esc(f.key)}" name="${esc(f.key)}">${f.options.map(([value,label])=>`<option value="${esc(value)}" ${value===v?'selected':''}>${esc(label)}</option>`).join('')}</select></label>`;}
function editField(e){const button=e.target.closest('[data-math-source]');if(!button||!active)return;const input=$(button.dataset.mathSource),f=active.lab.fields.find(f=>'wb-'+f.key===input.id);if(f)MF.open(input,f.label,MF.schema(active.lab,f));}

function mount(id,node){close();const lab=g.OrbisCatalog.labs[id],v=inputs[id]||cleanValues(lab,{});active={lab,result:null,values:null,revealed:false,yaw:-35,pitch:25,reference:references[id]||null,plotView:'both'};node.innerHTML=`<div class="platform-breadcrumb"><button data-platform-area="${lab.areaId}" type="button">${esc(lab.areaTitle)}</button><span>/</span><span>${esc(lab.group)}</span></div><section class="platform-catalog-head"><div><span class="platform-kicker">LABORATÓRIO</span><h1>${esc(lab.title)}</h1><p>${esc(lab.summary)}</p></div><button class="platform-secondary" data-platform-page="notebook" type="button">Caderno</button></section><div class="investigation-spread"><div class="investigation-workspace"><div class="wb-layout"><section class="wb-input-panel"><div class="wb-panel-head"><h2>Defina sua atividade</h2><button class="platform-link" type="button" id="wbReset">Restaurar exemplo</button></div><form id="wbForm">${lab.fields.map(f=>field(f,v[f.key])).join('')}<div class="wb-syntax">Toque em um campo para abrir o editor e o teclado matemático. Em vetores e matrizes, selecione o componente que deseja editar.</div><label class="wb-practice-toggle"><input type="checkbox" id="wbPractice"> Treinar antes de ver os resultados</label><div class="platform-actions"><button class="platform-primary" id="wbCalculate" type="submit">Calcular e visualizar</button><button class="platform-secondary" id="wbCancel" type="button" hidden>Cancelar</button></div><p id="wbSaveStatus" class="wb-save-status" role="status">Entradas independentes para cada laboratório.</p></form></section><section class="wb-output-panel" aria-label="Resultados"><div id="wbStatus" role="status" aria-live="polite"></div><div id="wbOutput"><div class="wb-empty"><span aria-hidden="true">∴</span><h2>Prepare seu experimento</h2><p>Altere os dados e use “Calcular e visualizar”. Você poderá comparar resultados e registrar a atividade no Caderno.</p></div></div></section></div></div><aside id="inquiryPanel" class="iq-panel" aria-label="Registro da investigação"></aside></div>`;
g.OrbisInquiry.mount(id,$('inquiryPanel'));$('wbForm').addEventListener('click',editField);$('wbForm').addEventListener('submit',e=>{e.preventDefault();calculate();});$('wbForm').addEventListener('input',e=>{if(!e.target.name)return;destroyChart();stop();active.result=null;active.revealed=false;g.OrbisInquiry.available();$('wbOutput').innerHTML='<p class="wb-empty-small">Dados alterados. Calcule novamente para atualizar o resultado.</p>';$('wbStatus').textContent='';clearTimeout(saveTimer);saveTimer=setTimeout(save,200);});$('wbCancel').onclick=()=>{stop();$('wbStatus').textContent='Cálculo cancelado.';};$('wbReset').onclick=()=>{destroyChart();active.camera=null;stop();for(const f of lab.fields){const input=$('wb-'+f.key);input.value=f.value;if(f.type!=='select')MF.refresh(input,MF.schema(lab,f));}active.result=null;g.OrbisInquiry.available();$('wbOutput').innerHTML='<p class="wb-empty-small">Exemplo restaurado. Calcule para visualizar.</p>';$('wbStatus').textContent='';save();};
}
function calculate(){destroyChart();active.camera=null;stop();save();active.result=null;active.attempt=null;active.values=values();$('wbStatus').className='wb-status';$('wbStatus').textContent='Calculando…';$('wbOutput').innerHTML='';$('wbCalculate').disabled=true;$('wbCancel').hidden=false;try{const url=URL.createObjectURL(new Blob([g.OrbisWorkerSource],{type:'text/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);timer=setTimeout(()=>{stop();$('wbStatus').className='wb-status error';$('wbStatus').textContent='O cálculo atingiu 12 segundos. Simplifique a expressão ou divida o intervalo.';},12000);worker.onmessage=e=>{stop();if(!active)return;if(!e.data.ok){$('wbStatus').className='wb-status error';$('wbStatus').textContent=e.data.error;return;}active.result=e.data.result;active.revealed=false;$('wbStatus').textContent='Cálculo concluído.';if($('wbPractice').checked)practice();else reveal();};worker.onerror=()=>{stop();$('wbStatus').className='wb-status error';$('wbStatus').textContent='Não foi possível iniciar o cálculo. Verifique se o navegador permite processamento local por Web Workers.';};worker.postMessage({id:active.lab.id,values:active.values});}catch(e){stop();$('wbStatus').textContent=e.message;}}
function practice(){const metrics=active.result.metrics.filter(m=>typeof m.value==='number'&&Number.isFinite(m.value));if(!metrics.length){$('wbOutput').innerHTML='<div class="wb-practice"><h2>Registre sua previsão</h2><label for="wbHypothesis">Sua resposta ou hipótese</label><textarea id="wbHypothesis" rows="4" maxlength="4000"></textarea><p>Este resultado é simbólico ou textual. A comparação será feita por você após a revelação.</p><button class="platform-primary" id="wbReveal" type="button">Revelar resultado</button></div>';}else{$('wbOutput').innerHTML=`<div class="wb-practice"><span class="platform-kicker">TREINO</span><h2>Qual resultado você espera?</h2><label for="wbTarget">Grandeza a conferir</label><select id="wbTarget">${metrics.map((m,i)=>`<option value="${i}">${esc(m.label)}</option>`).join('')}</select>${MF.markup('wbGuess','Sua resposta numérica','',{kind:'number'})}<p>Tolerância: 0,01% × máx(1, |resultado|).</p><div class="platform-actions"><button class="platform-primary" id="wbCheck" type="button">Conferir resposta</button><button class="platform-secondary" id="wbReveal" type="button">Revelar resultado</button></div><p id="wbFeedback" role="status"></p></div>`;$('wbGuess-edit').onclick=()=>MF.open($('wbGuess'),'Sua resposta numérica',{kind:'number'});$('wbCheck').onclick=()=>{try{const target=metrics[Number($('wbTarget').value)],guess=K.num($('wbGuess').value),ok=Math.abs(guess-target.value)<=1e-4*Math.max(1,Math.abs(target.value));active.attempt={label:target.label,answer:$('wbGuess').value,correct:ok};$('wbFeedback').textContent=ok?'Resposta dentro da tolerância.':'Ainda não coincide. Revise o cálculo ou revele o resultado.';}catch(e){$('wbFeedback').textContent=e.message;}};}$('wbReveal').onclick=()=>{if($('wbHypothesis'))active.attempt={label:'Hipótese',answer:$('wbHypothesis').value};reveal();};}
function tableHtml(r,limit=120){if(!r.columns?.length)return '';return `<div class="wb-table-wrap" tabindex="0" aria-label="Tabela de resultados"><table><thead><tr>${r.columns.map(c=>`<th scope="col">${esc(c)}</th>`).join('')}</tr></thead><tbody>${(r.rows||[]).slice(0,limit).map(row=>`<tr>${row.map(v=>`<td>${esc(K.fmt(v))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${r.rows.length>limit?`<p class="wb-method">Mostrando ${limit} de ${r.rows.length} linhas. O CSV contém a tabela completa.</p>`:''}`;}
function reveal(){destroyChart();active.revealed=true;const r=active.result;$('wbOutput').innerHTML=`<div class="wb-result-head"><h2>Resultados</h2><span class="wb-result-tag">${r.plot?.dimensions===3?'VISUALIZAÇÃO 3D':'EXPERIMENTO'}</span></div><dl class="wb-metrics">${r.metrics.map(m=>`<div><dt>${esc(m.label)}</dt><dd>${esc(K.fmt(m.value))}</dd></div>`).join('')}</dl>${r.plot?`<div class="wb-chart-card"><h3 class="wb-visual-title">${esc(r.visualTitle||'Representação do experimento')}</h3>${plotControls()}<div id="wbPlot" class="wb-plot-surface" tabindex="0" role="group" aria-label="Gráfico interativo" aria-describedby="wbPlotHelp"></div><p id="wbPlotHelp" class="wb-plot-hint">Toque no gráfico para interagir. Use os controles para ajustar a vista; a roda atua quando o gráfico está selecionado.</p><div id="wbViewControls" class="wb-view-controls"></div><div id="wbLegend" class="wb-legend"></div></div>`:''}${diagramHtml()}${r.visualNote?`<p class="wb-visual-caption">${esc(r.visualNote)}</p>`:''}${comparisonHtml()}${tableHtml(r)}<p class="wb-method">${esc(r.method||'')}</p>${r.notice?`<p class="wb-notice">${esc(r.notice)}</p>`:''}<div class="wb-result-actions"><button class="platform-primary" type="button" id="wbRecord">Registrar no Caderno</button><button class="platform-secondary" type="button" id="wbJson">Exportar resultado</button>${r.rows?.length||r.plot?'<button class="platform-secondary" type="button" id="wbCsv">Exportar CSV</button>':''}${r.plot?'<button class="platform-secondary" type="button" id="wbSvg">Exportar gráfico SVG</button>':''}</div>`;
bindComparison();if(r.plot){chartView=g.OrbisPlotView.create({host:$('wbPlot'),controls:$('wbViewControls'),legend:$('wbLegend'),plot:displayPlot,title:active.lab.title,state:active.camera});active.camera=chartView.state;bindPlotControls();$('wbSvg').onclick=()=>download($('wbPlot').innerHTML,'image/svg+xml',`${active.lab.id}.svg`);}
g.OrbisInquiry.available();$('wbRecord').onclick=()=>{const snap=snapshot();g.OrbisPlatform.recordCalculation(snap,(active.attempt?`${active.attempt.label}: ${active.attempt.answer}${typeof active.attempt.correct==='boolean'?`\nConferência: ${active.attempt.correct?'dentro':'fora'} da tolerância.`:''}`:'')+comparisonNote());};$('wbJson').onclick=()=>download(JSON.stringify({format:'orbisv-calculation',version:1,snapshot:snapshot(),...(active.reference?{reference:{labId:active.lab.id,values:active.reference.values,result:active.reference.result}}:{})},null,2),'application/json',`${active.lab.id}.json`);if($('wbCsv'))$('wbCsv').onclick=exportCsv;
}
function snapshot(){return {kind:'calculation',labId:active.lab.id,labTitle:active.lab.title,savedAt:new Date().toISOString(),values:clone(active.values),result:clone(active.result)};}
function download(text,mime,name){g.OrbisVRuntime.AppUI.download(text,mime,name);}
function exportCsv(){const r=active.result,rows=r.rows?.length?[r.columns,...r.rows]:[['Série','x','y','z'],...r.plot.series.flatMap(s=>s.points.map(p=>[s.name,...p]))],cell=v=>{let s=typeof v==='number'?String(v).replace('.',','):String(v??'');if(typeof v!=='number'&&/^[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};download('\uFEFF'+rows.map(r=>r.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8',`${active.lab.id}.csv`);}
function compatiblePlots(){const ref=active.reference?.result.plot,p=active.result?.plot;return !!(ref&&p&&(ref.dimensions||2)===(p.dimensions||2)&&JSON.stringify(ref.axes||[])===JSON.stringify(p.axes||[]));}
function displayPlot(){const current=active.result.plot,ref=active.reference?.result.plot;if(active.plotView==='reference'&&compatiblePlots())return {...ref,series:ref.series.map(s=>({...s,name:'Referência · '+s.name,reference:true}))};if(active.plotView==='both'&&compatiblePlots())return {...current,series:[...ref.series.map(s=>({...s,name:'Referência · '+s.name,reference:true})),...current.series]};return current;}
function plotControls(){return `<div class="wb-plot-controls">${active.reference&&compatiblePlots()?'<label>Comparação<select id="wbPlotView"><option value="both">Atual + referência</option><option value="current">Somente atual</option><option value="reference">Somente referência</option></select></label>':''}</div>`;}
function bindPlotControls(){if($('wbPlotView')){$('wbPlotView').value=active.plotView;$('wbPlotView').onchange=()=>{active.plotView=$('wbPlotView').value;chartView?.adapter.fit();chartView?.adapter.flush();};}}
function diagramHtml(){const r=active.result,ref=active.reference,range=r.diagram?.kind==='fractions'?[active.values.a,active.values.b,r.metrics.find(m=>m.label==='Decimal aproximado')?.value,...(ref?[ref.values.a,ref.values.b,ref.result.metrics.find(m=>m.label==='Decimal aproximado')?.value]:[])].map(v=>K.num(String(v))):[],render=(p,r)=>g.OrbisRepresentations.render(active.lab.id,p,r,{fractionRange:range});if(!r.diagram)return '';return `<section class="wb-diagram-card" aria-label="Representação visual"><h3 class="wb-visual-title">Representação visual</h3><div class="wb-diagram-comparison">${ref?.result.diagram?`<div><h4>Referência</h4>${render(ref.values,ref.result)}</div>`:''}<div>${ref?'<h4>Atual</h4>':''}${render(active.values,r)}</div></div></section>`;}
function comparisonHtml(){const ref=active.reference,r=active.result;let html='<section class="wb-comparison"><div class="wb-comparison-head"><h3>Explore as variações</h3><button class="platform-secondary" id="wbPinReference" type="button">'+(ref?'Atualizar referência':'Fixar como referência')+'</button></div>';
 if(!ref)return html+'<p>Fixe este resultado, altere os dados e calcule novamente para comparar.</p></section>';
 const fields=active.lab.fields.filter(f=>ref.values[f.key]!==active.values[f.key]);html+=`<p>Referência guardada nesta sessão. ${compatiblePlots()?'Traços cinza representam a referência no gráfico.':''}</p><p id="wbChangedInputs">${fields.length?fields.length+' campo(s) alterado(s): '+fields.map(f=>esc(f.label)).join(', '):'Os dados atuais são iguais aos da referência.'}</p>`;
 const rows=r.metrics.map(m=>{const old=ref.result.metrics.find(x=>x.label===m.label);return old?[m.label,K.fmt(old.value),K.fmt(m.value)]:null;}).filter(Boolean);
 if(rows.length)html+=tableHtml({columns:['Grandeza','Referência','Atual'],rows});
 if(fields.length)html+=`<details><summary>Comparar entradas</summary><div class="wb-table-wrap"><table><thead><tr><th>Campo</th><th>Referência</th><th>Atual</th></tr></thead><tbody>${fields.map(f=>`<tr><th scope="row">${esc(f.label)}</th><td>${esc(ref.values[f.key])}</td><td>${esc(active.values[f.key])}</td></tr>`).join('')}</tbody></table></div></details>`;
 if(r.plot&&ref.result.plot&&!compatiblePlots())html+='<p>Os gráficos usam dimensões ou unidades diferentes. A sobreposição está desativada; compare as entradas e os resultados na tabela.</p>';
 return html+'<button class="platform-link" type="button" id="wbClearReference">Limpar referência</button></section>';
}
function bindComparison(){$('wbPinReference').onclick=()=>{active.reference={values:clone(active.values),result:clone(active.result)};references[active.lab.id]=active.reference;active.plotView='both';reveal();};if($('wbClearReference'))$('wbClearReference').onclick=()=>{delete references[active.lab.id];active.reference=null;active.plotView='both';reveal();};}
function comparisonNote(){if(!active.reference)return '';const ref=active.reference,fields=active.lab.fields.filter(f=>ref.values[f.key]!==active.values[f.key]);return '\n\nComparação com referência:\n'+fields.map(f=>`${f.label}: ${ref.values[f.key]} → ${active.values[f.key]}`).join('\n')+'\nResultados da referência:\n'+ref.result.metrics.map(m=>`${m.label}: ${K.fmt(m.value)}`).join('\n');}

function drawPlot(){chartView?.draw();}
function validateSnapshot(raw){const lab=g.OrbisCatalog.labs[raw?.labId];if(!lab||lab.kind!=='workbench')throw new Error('Laboratório do registro não reconhecido.');const cell=v=>{if(typeof v==='number'&&Number.isFinite(v))return v;if(typeof v==='string'&&v.length<=5000)return v;throw new Error('Valor inválido no registro.');};const r=raw.result;if(!r||!Array.isArray(r.metrics)||r.metrics.length>60)throw new Error('Resultado inválido no Caderno.');const result={metrics:r.metrics.map(m=>({label:String(m.label).slice(0,200),value:cell(m.value)})),method:String(r.method||'').slice(0,3000),notice:String(r.notice||'').slice(0,3000)};if(r.columns){if(!Array.isArray(r.columns)||r.columns.length>20||!Array.isArray(r.rows)||r.rows.length>5000)throw new Error('Tabela inválida no registro.');result.columns=r.columns.map(cell);result.rows=r.rows.map(row=>{if(!Array.isArray(row)||row.length!==r.columns.length)throw new Error('Linha inválida.');return row.map(cell);});}if(r.plot){if(!Array.isArray(r.plot.series)||r.plot.series.length>120)throw new Error('Gráfico inválido.');let count=0;result.plot={dimensions:r.plot.dimensions===3?3:2,equal:!!r.plot.equal,axes:Array.isArray(r.plot.axes)?r.plot.axes.slice(0,3).map(x=>String(x).slice(0,100)):undefined,series:r.plot.series.map(s=>{if(!Array.isArray(s.points)||(count+=s.points.length)>15000)throw new Error('Gráfico excede o limite.');return {name:String(s.name).slice(0,200),kind:s.kind==='points'?'points':'line',arrow:!!s.arrow,fill:!!s.fill,points:s.points.map(p=>{if(!Array.isArray(p)||p.length<2||p.length>3||p.some(x=>x!==null&&(typeof x!=='number'||!Number.isFinite(x))))throw new Error('Coordenada inválida.');return p;})};})};}return {kind:'calculation',labId:lab.id,labTitle:lab.title,savedAt:Number.isFinite(Date.parse(raw.savedAt))?raw.savedAt:new Date().toISOString(),values:cleanValues(lab,raw.values),result};}
function snapshotHtml(raw){const s=raw,r=s.result,lab=g.OrbisCatalog.labs[s.labId];return `<section class="platform-snapshot"><strong>Experimento registrado · ${esc(s.labTitle)}</strong><span>${esc(new Date(s.savedAt).toLocaleString('pt-BR'))}</span><details><summary>Consultar entradas e resultados</summary><dl class="wb-note-data">${lab.fields.map(f=>`<div><dt>${esc(f.label)}</dt><dd>${esc(s.values[f.key])}</dd></div>`).join('')}${r.metrics.map(m=>`<div><dt>${esc(m.label)}</dt><dd>${esc(K.fmt(m.value))}</dd></div>`).join('')}</dl><p>${esc(r.method)}</p>${r.notice?`<p>${esc(r.notice)}</p>`:''}${tableHtml(r,30)}</details><button class="platform-secondary" type="button" data-note-restore>Reabrir experimento</button></section>`;}
function restore(s){const valid=validateSnapshot(s);inputs[s.labId]=valid.values;g.OrbisPlatform.openLab(s.labId);}
g.addEventListener('resize',()=>{if(active?.result?.plot&&active.revealed)drawPlot();});
g.addEventListener('pagehide',()=>{clearTimeout(saveTimer);save();});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')save();});
g.OrbisWorkbench={experiment:()=>active?.result&&active.revealed?snapshot():null,setInputs:(id,raw)=>{inputs[id]=cleanValues(g.OrbisCatalog.labs[id],raw);},redraw:()=>{if(active?.result?.plot&&active.revealed)drawPlot();},mount,close,validateSnapshot,snapshotHtml,restore,calculate,tableHtml};
})(window);
